from .grupo_verificacao_regularidade import GrupoVerificacaoRegularidade
from .item_verificacao_regularidade import ItemVerificacaoRegularidade
from .lista_verificacao_regularidade import ListaVerificacaoRegularidade
