# Generated by Django 2.2.10 on 2020-03-26 14:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_auto_20200318_1504'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoReceita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=160, verbose_name='Nome')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alterado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo de receita',
                'verbose_name_plural': 'Tipos de receita',
            },
        ),
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alterado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('data', models.DateField(blank=True, null=True, verbose_name='Data Receita')),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Valor Receita')),
                ('descricao', models.TextField(blank=True, max_length=400, null=True, verbose_name='Descrição')),
                ('acao_associacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receitas_da_associacao', to='core.AcaoAssociacao')),
                ('associacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receitas', to='core.Associacao')),
                ('conta_associacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receitas_da_conta', to='core.ContaAssociacao')),
                ('tipo_receita', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='receitas.TipoReceita')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
