# Generated by Django 2.2.10 on 2020-04-06 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Valor Receita'),
        ),
    ]
