# Generated by Django 2.2.10 on 2020-04-13 21:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_periodo'),
        ('receitas', '0002_auto_20200406_1140'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repasse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alterado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('valor_capital', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Valor Capital')),
                ('valor_custeio', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Valor Custeio')),
                ('acao_associacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='repasses_da_associacao', to='core.AcaoAssociacao')),
                ('associacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='repasses', to='core.Associacao')),
                ('conta_associacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='repasses_da_conta', to='core.ContaAssociacao')),
                ('periodo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.Periodo')),
            ],
            options={
                'verbose_name': 'Repasse',
                'verbose_name_plural': 'Repasses',
            },
        ),
    ]
