# Generated by Django 2.2.10 on 2020-04-16 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0003_repasse'),
    ]

    operations = [
        migrations.AddField(
            model_name='repasse',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('REALIZADO', 'Realizado')], default='Pendente', max_length=15),
        ),
    ]
