# Generated by Django 2.2.10 on 2020-04-17 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0004_repasse_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiporeceita',
            name='e_repasse',
            field=models.BooleanField(default=False, verbose_name='É repasse?'),
        ),
    ]
