# Generated by Django 2.2.10 on 2020-05-12 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0006_receita_conferido'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiporeceita',
            name='aceita_capital',
            field=models.BooleanField(default=False, verbose_name='Aceita capital?'),
        ),
        migrations.AddField(
            model_name='tiporeceita',
            name='aceita_custeio',
            field=models.BooleanField(default=False, verbose_name='Aceita custeio?'),
        ),
    ]
