# Generated by Django 2.2.10 on 2020-05-12 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0007_auto_20200512_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='categoria_receita',
            field=models.CharField(choices=[('CAPITAL', 'Capital'), ('CUSTEIO', 'Custeio')], default='CUSTEIO', max_length=15, null=True, verbose_name='Categoria da receita'),
        ),
    ]
