# Generated by Django 2.2.10 on 2020-05-28 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0008_receita_categoria_receita'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiporeceita',
            name='e_rendimento',
            field=models.BooleanField(default=False, verbose_name='É rendimento?'),
        ),
    ]
