# Generated by Django 2.2.10 on 2020-06-19 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0010_receita_prestacao_conta'),
    ]

    operations = [
        migrations.AddField(
            model_name='repasse',
            name='realizado_capital',
            field=models.BooleanField(default=False, verbose_name='Realizado Capital?'),
        ),
        migrations.AddField(
            model_name='repasse',
            name='realizado_custeio',
            field=models.BooleanField(default=False, verbose_name='Realizado Custeio?'),
        ),
    ]
