# Generated by Django 2.2.10 on 2020-06-19 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0011_auto_20200619_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='repasse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receitas', to='receitas.Repasse'),
        ),
    ]
