# Generated by Django 2.2.10 on 2020-06-29 15:42

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0012_receita_repasse'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalhaTipoReceita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=160, verbose_name='Nome')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alterado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('tipo_receita', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='receitas.TipoReceita')),
            ],
            options={
                'verbose_name': 'Detalhe de tipo de receita',
                'verbose_name_plural': 'Detalhes de tipos de receita',
            },
        ),
    ]
