# Generated by Django 2.2.10 on 2020-06-29 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0013_detalhatiporeceita'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DetalhaTipoReceita',
            new_name='DetalheTipoReceita',
        ),
    ]
