# Generated by Django 2.2.10 on 2020-06-29 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0014_auto_20200629_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='detalhe_outros',
            field=models.CharField(blank=True, default='', max_length=160, verbose_name='Detalhe da despesa (outros)'),
        ),
        migrations.AddField(
            model_name='receita',
            name='detalhe_tipo_receita',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='receitas.DetalheTipoReceita'),
        ),
    ]
