# Generated by Django 2.2.10 on 2020-06-29 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0015_auto_20200629_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalhetiporeceita',
            name='tipo_receita',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detalhes_tipo_receita', to='receitas.TipoReceita'),
        ),
    ]
