# Generated by Django 2.2.10 on 2020-06-30 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0016_auto_20200629_1713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receita',
            name='descricao',
        ),
    ]
