# Generated by Django 2.2.10 on 2020-07-15 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0017_remove_receita_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='repasse',
            name='realizado_livre',
            field=models.BooleanField(default=False, verbose_name='Realizado Livre Aplicação?'),
        ),
    ]
