# Generated by Django 2.2.10 on 2020-07-15 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0018_repasse_realizado_livre'),
    ]

    operations = [
        migrations.AddField(
            model_name='repasse',
            name='valor_livre',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Valor Custeio'),
        ),
    ]
