# Generated by Django 2.2.10 on 2020-07-17 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0019_repasse_valor_livre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='categoria_receita',
            field=models.CharField(choices=[('CAPITAL', 'Capital'), ('CUSTEIO', 'Custeio'), ('LIVRE', 'Livre Aplicação')], default='CUSTEIO', max_length=15, null=True, verbose_name='Categoria da receita'),
        ),
    ]
