# Generated by Django 2.2.10 on 2020-07-17 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0020_auto_20200717_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiporeceita',
            name='aceita_livre',
            field=models.BooleanField(default=False, verbose_name='Aceita livre aplicação?'),
        ),
    ]
