# Generated by Django 2.2.10 on 2020-07-17 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0021_tiporeceita_aceita_livre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repasse',
            name='valor_livre',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Valor Livre Aplicação'),
        ),
    ]
