# Generated by Django 2.2.10 on 2020-07-22 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_auto_20200720_1432'),
        ('receitas', '0022_auto_20200717_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='referencia_devolucao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.Periodo'),
        ),
        migrations.AddField(
            model_name='tiporeceita',
            name='e_devolucao',
            field=models.BooleanField(default=False, verbose_name='É devolução?'),
        ),
    ]
