# Generated by Django 2.2.10 on 2020-08-31 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_observacaoconciliacao'),
        ('receitas', '0023_auto_20200722_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='periodo_conciliacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receitas_conciliadas_no_periodo', to='core.Periodo', verbose_name='período de conciliação'),
        ),
    ]
