# Generated by Django 2.2.10 on 2020-08-31 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0024_receita_periodo_conciliacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receita',
            name='prestacao_conta',
        ),
    ]
