# Generated by Django 2.2.10 on 2020-09-08 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0025_remove_receita_prestacao_conta'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='update_conferido',
            field=models.BooleanField(default=False, verbose_name='Atualiza conferido?'),
        ),
    ]
