# Generated by Django 2.2.10 on 2020-09-23 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0094_auto_20200922_1356'),
        ('receitas', '0026_receita_update_conferido'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiporeceita',
            name='tipos_conta',
            field=models.ManyToManyField(blank=True, null=True, to='core.TipoConta'),
        ),
    ]
