# Generated by Django 2.2.10 on 2020-09-29 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0027_tiporeceita_tipos_conta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiporeceita',
            name='tipos_conta',
            field=models.ManyToManyField(blank=True, to='core.TipoConta'),
        ),
    ]
