# Generated by Django 2.2.10 on 2020-12-10 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0028_auto_20200929_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiporeceita',
            name='e_recursos_proprios',
            field=models.BooleanField(default=False, verbose_name='Aceita recursos próprios?'),
        ),
    ]
