# Generated by Django 2.2.10 on 2021-05-25 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0030_auto_20210107_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='saida_do_recurso',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Saída do Recurso (Despesa Uuid)'),
        ),
    ]
