# Generated by Django 2.2.10 on 2021-06-29 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0031_receita_saida_do_recurso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receita',
            name='saida_do_recurso',
        ),
    ]
