# Generated by Django 2.2.10 on 2021-07-15 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0034_auto_20210630_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiporeceita',
            name='mensagem_usuario',
            field=models.TextField(blank=True, default='', verbose_name='Mensagem usuario'),
        ),
    ]
