# Generated by Django 2.2.10 on 2021-07-19 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0035_tiporeceita_mensagem_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiporeceita',
            name='mensagem_usuario',
            field=models.TextField(blank=True, default='', verbose_name='Mensagem para o usuario'),
        ),
    ]
