# Generated by Django 2.2.10 on 2021-07-20 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0036_auto_20210719_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiporeceita',
            name='possui_detalhamento',
            field=models.BooleanField(default=False, verbose_name='Deve exibir detalhamento?'),
        ),
    ]
