# Generated by Django 2.2.10 on 2021-10-11 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0038_repasse_carga_origem'),
    ]

    operations = [
        migrations.AddField(
            model_name='repasse',
            name='carga_origem_linha_id',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Id da linha de carga'),
        ),
    ]
