# Generated by Django 2.2.10 on 2021-10-11 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0039_repasse_carga_origem_linha_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repasse',
            name='carga_origem_linha_id',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Id da linha de carga'),
        ),
    ]
