# Generated by Django 2.2.10 on 2022-01-04 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0040_auto_20211011_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='conferido',
            field=models.BooleanField(default=True, verbose_name='Conferido?'),
        ),
    ]
