# Generated by Django 2.2.10 on 2022-02-24 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0041_auto_20220104_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiporeceita',
            name='e_estorno',
            field=models.BooleanField(default=False, verbose_name='É estorno?'),
        ),
    ]
