# Generated by Django 2.2.10 on 2022-02-24 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0039_especificacaomaterialservico_ativa'),
        ('receitas', '0042_tiporeceita_e_estorno'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='rateio_estornado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estorno', to='despesas.RateioDespesa', verbose_name='Rateio estornado'),
        ),
    ]
