# Generated by Django 2.2.10 on 2022-03-22 14:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0043_receita_rateio_estornado'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotivoEstorno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alterado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('motivo', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Motivo de estorno',
                'verbose_name_plural': 'Motivos de estorno',
            },
        ),
        migrations.AddField(
            model_name='receita',
            name='outros_motivos_estorno',
            field=models.TextField(blank=True, default='', verbose_name='Outros motivos para estorno'),
        ),
        migrations.AddField(
            model_name='receita',
            name='motivos_estorno',
            field=models.ManyToManyField(blank=True, to='receitas.MotivoEstorno'),
        ),
    ]
