# Generated by Django 2.2.10 on 2022-03-28 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0045_auto_20220328_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='motivos_estorno',
            field=models.ManyToManyField(blank=True, related_name='receitas_do_motivo', to='receitas.MotivoEstorno'),
        ),
    ]
