# Generated by Django 2.2.10 on 2022-09-05 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0046_auto_20220328_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='data_e_hora_de_inativacao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data e hora de inativação'),
        ),
        migrations.AddField(
            model_name='receita',
            name='status',
            field=models.CharField(choices=[('COMPLETO', 'Completo'), ('INATIVO', 'Inativo')], default='COMPLETO', max_length=15, verbose_name='status'),
        ),
    ]
