# Generated by Django 4.2.7 on 2023-11-23 11:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0363_itemdespesa_valor_total"),
        ("receitas", "0047_auto_20220905_0950"),
    ]

    operations = [
        migrations.AddField(
            model_name="tiporeceita",
            name="unidades",
            field=models.ManyToManyField(blank=True, null=True, to="core.unidade"),
        ),
    ]
