# Generated by Django 4.2.7 on 2024-05-23 08:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("receitas", "0048_tiporeceita_unidades"),
    ]

    operations = [
        migrations.AlterField(
            model_name="repasse",
            name="status",
            field=models.CharField(
                choices=[("PENDENTE", "Previsto"), ("REALIZADO", "Realizado")],
                default="Previsto",
                max_length=15,
            ),
        ),
    ]
