# Generated by Django 4.2.11 on 2024-06-03 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0395_arquivo_tipo_de_conta"),
        ("receitas", "0049_alter_repasse_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tiporeceita",
            name="unidades",
            field=models.ManyToManyField(blank=True, to="core.unidade"),
        ),
    ]
