# Generated by Django 4.2.20 on 2026-05-19 10:43

from django.db import migrations, models
import django.db.models.deletion

def atualiza_recurso_tipo_receita(apps, schema_editor):
    Recurso = apps.get_model('core', 'Recurso')
    TipoReceita = apps.get_model('receitas', 'TipoReceita')

    recurso_legado = Recurso.objects.get(legado=True)

    TipoReceita.objects.filter(recurso__isnull=True).update(recurso=recurso_legado)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0441_alter_tipoconta_unique_together"),
        ("receitas", "0051_tiporeceita_detalhes"),
    ]

    operations = [
        migrations.AddField(
            model_name="tiporeceita",
            name="recurso",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.recurso",
                verbose_name="Recurso",
            ),
        ),
        migrations.RunPython(atualiza_recurso_tipo_receita, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name="tiporeceita",
            name="recurso",
            field=models.ForeignKey(
                blank=False,
                null=False,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.recurso",
                verbose_name="Recurso",
            ),
        ),
    ]
