# Generated by Django 4.2.20 on 2026-05-26 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("receitas", "0052_tiporeceita_recurso"),
    ]

    operations = [
        migrations.AlterField(
            model_name="receita",
            name="detalhe_tipo_receita",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="receitas",
                to="receitas.detalhetiporeceita",
            ),
        ),
    ]
