# Generated by Django 4.2.7 on 2023-11-28 09:38

from django.db import migrations, models
import sme_ptrf_apps.sme.models.parametros_sme
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ParametrosSme",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "alterado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Alterado em"),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "tipos_unidade_adm_da_sme",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text='O campo deve seguir o padrão "0, 00, 00" ou ser um único dígito.',
                        max_length=50,
                        validators=[
                            sme_ptrf_apps.sme.models.parametros_sme.validate_tipos_unidade
                        ],
                        verbose_name="Tipos unidade adm da SME",
                    ),
                ),
            ],
            options={
                "verbose_name": "Parâmetro SME",
                "verbose_name_plural": "01.0) Parâmetros SME",
            },
        ),
    ]
