# Generated by Django 4.2.7 on 2023-12-13 11:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sme", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="parametrossme",
            name="valida_unidades_login",
            field=models.BooleanField(
                default=False, verbose_name="Valida unidades ao logar"
            ),
        ),
    ]
