# Generated by Django 4.2.11 on 2024-04-22 07:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sme", "0004_remove_parametrossme_tipos_unidade_adm_da_sme"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parametrossme",
            name="valida_unidades_login",
            field=models.BooleanField(
                default=False,
                help_text="Remove definitivamente os acessos indevidos.",
                verbose_name="Valida unidades ao logar",
            ),
        ),
    ]
