STATUS_PERIODO_ASSOCIACAO_EM_ANDAMENTO = 'EM_ANDAMENTO'
STATUS_PERIODO_ASSOCIACAO_PENDENTE = 'PENDENTE'
STATUS_PERIODO_ASSOCIACAO_CONCILIADO = 'CONCILIADO'
STATUS_PERIODO_ASSOCIACAO_APROVADO = 'APROVADO'
STATUS_PERIODO_ASSOCIACAO_REJEITADO = 'REJEITADO'

STATUS_NOMES = {
    STATUS_PERIODO_ASSOCIACAO_EM_ANDAMENTO: 'Em andamento',
    STATUS_PERIODO_ASSOCIACAO_PENDENTE: 'Pendente',
    STATUS_PERIODO_ASSOCIACAO_CONCILIADO: 'Conciliado',
    STATUS_PERIODO_ASSOCIACAO_APROVADO: 'Aprovado',
    STATUS_PERIODO_ASSOCIACAO_REJEITADO: 'Rejeitado',
}
