# Generated by Django 2.2.10 on 2020-06-05 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_remove_associacao_usuario'),
        ('users', '0003_remove_user_associacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='associacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='core.Associacao'),
        ),
    ]
