# Generated by Django 2.2.10 on 2020-07-10 12:56

from django.db import migrations, models
import uuid


def gen_uuid(apps, schema_editor):
    User = apps.get_model('users', 'User')
    for row in User.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=['uuid'])


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200710_1250'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
