# Generated by Django 2.2.10 on 2020-07-31 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_parametros_tempo_notificar_nao_demonstrados'),
        ('users', '0006_auto_20200710_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='unidades',
            field=models.ManyToManyField(blank=True, to='core.Unidade'),
        ),
    ]
