# Generated by Django 2.2.10 on 2020-08-03 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_unidades'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='associacao',
        ),
    ]
