# Generated by Django 2.2.10 on 2020-08-05 19:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_user_associacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=160, verbose_name='Nome')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alterado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
            options={
                'verbose_name': 'Visão',
                'verbose_name_plural': 'Visões',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='visoes',
            field=models.ManyToManyField(blank=True, to='users.Visao'),
        ),
    ]
