# Generated by Django 2.2.10 on 2020-10-28 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_grupo_visoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tipo_usuario',
            field=models.CharField(choices=[('SERVIDOR', 'Servidor'), ('PAI_RESPONSAVEL', 'Pai_ou_responsável'), ('ESTUDANTE', 'Estudante')], default='Servidor', max_length=25, verbose_name='Tipo Usuário'),
        ),
    ]
