# Generated by Django 2.2.10 on 2021-04-26 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_user_tipo_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='e_servidor',
            field=models.BooleanField(default=False, verbose_name='servidor?'),
        ),
    ]
