# Generated by Django 2.2.10 on 2021-04-26 08:03

from django.db import migrations

def atualiza_e_servidor(apps, schema_editor):
    model_user = apps.get_model('users', 'User')
    for user in model_user.objects.filter(tipo_usuario='SERVIDOR'):
        user.e_servidor = True
        user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_user_e_servidor'),
    ]

    operations = [
        migrations.RunPython(atualiza_e_servidor, reverse_code=migrations.RunPython.noop),
    ]
