# Generated by Django 2.2.10 on 2021-09-03 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20210903_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='visoes_log',
            field=models.TextField(blank=True, help_text='Visões do grupo (audtilog)'),
        ),
    ]
