# Generated by Django 2.2.10 on 2021-09-27 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_grupo_visoes_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='grupos',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='usuarios', related_query_name='usuario', to='users.Grupo', verbose_name='grupos'),
        ),
    ]
