# Generated by Django 2.2.10 on 2021-09-27 13:38

from django.db import migrations


def copia_grupos(apps, schema_editor):
    model_usuarios = apps.get_model('users', 'User')
    for user in model_usuarios.objects.all():
        user.grupos.add(*user.groups.all())


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_user_grupos'),
    ]

    operations = [
        migrations.RunPython(copia_grupos, reverse_code=migrations.RunPython.noop)
    ]

