# Generated by Django 2.2.10 on 2022-06-20 08:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0260_merge_20220613_1532'),
        ('users', '0021_auto_20210927_1401'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadeEmSuporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alterado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acessos_de_suporte', to='core.Unidade')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acessos_de_suporte', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Unidade em suporte',
                'verbose_name_plural': 'Unidades em suporte',
                'unique_together': {('unidade', 'user')},
            },
        ),
    ]
