# Generated by Django 4.1.12 on 2023-11-07 07:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0024_acessoconcedidosme"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="acessoconcedidosme",
            options={
                "verbose_name": "Acesso concedido pela SME",
                "verbose_name_plural": "Acessos concedidos pela SME",
            },
        ),
    ]
