# Generated by Django 4.2.7 on 2024-01-08 13:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0025_alter_acessoconcedidosme_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="pode_acessar_sme",
            field=models.BooleanField(default=False, verbose_name="Pode acessar SME ?"),
        ),
    ]
