# Generated by Django 4.2.7 on 2024-01-10 15:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0026_user_pode_acessar_sme"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="pode_acessar_sme",
            field=models.BooleanField(
                default=False,
                help_text="Permissão para usuários que não possuem acesso direto a SME.",
                verbose_name="Pode acessar SME ?",
            ),
        ),
    ]
