# Generated by Django 4.2.7 on 2024-01-17 11:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0028_grupo_suporte"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grupo",
            name="suporte",
            field=models.BooleanField(
                default=False, help_text="Grupo usado para acessos de suporte?"
            ),
        ),
    ]
