# Generated by Django 3.1.14 on 2023-08-03 09:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0346_funcuemembrosdaassociacao'),
        ('mandatos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Composicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alterado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('data_inicial', models.DateField(blank=True, null=True, verbose_name='Data de início da composição')),
                ('data_final', models.DateField(blank=True, null=True, verbose_name='Data de término da composição')),
                ('associacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='composicoes_da_associacao', to='core.associacao', verbose_name='Associação')),
                ('mandato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='composicoes_do_mandato', to='mandatos.mandato', verbose_name='Mandato')),
            ],
            options={
                'verbose_name': 'Composição',
                'verbose_name_plural': 'Composições',
            },
        ),
    ]
