# Generated by Django 3.1.14 on 2023-08-03 09:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mandatos', '0002_composicao'),
    ]

    operations = [
        migrations.CreateModel(
            name='OcupanteCargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alterado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nome', models.CharField(max_length=160, verbose_name='Nome')),
                ('codigo_identificacao', models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='Código EOL ou RF')),
                ('cargo_educacao', models.CharField(blank=True, default='', max_length=160, null=True, verbose_name='Cargo Educação')),
                ('representacao', models.CharField(choices=[('SERVIDOR', 'Servidor'), ('PAI_RESPONSAVEL', 'Pai ou responsável'), ('ESTUDANTE', 'Estudante')], default='SERVIDOR', max_length=15, verbose_name='Representação')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('cpf_responsavel', models.CharField(blank=True, default='', max_length=14, null=True, verbose_name='CPF Responsável')),
                ('telefone', models.CharField(blank=True, default='', max_length=20, verbose_name='Telefone')),
                ('cep', models.CharField(blank=True, default='', max_length=20, verbose_name='CEP')),
                ('bairro', models.CharField(blank=True, default='', max_length=255, verbose_name='Bairro')),
                ('endereco', models.CharField(blank=True, default='', max_length=255, verbose_name='Endereço')),
            ],
            options={
                'verbose_name': 'Ocupante Cargo',
                'verbose_name_plural': 'Ocupantes Cargo',
            },
        ),
    ]
