# Generated by Django 3.1.14 on 2023-08-03 09:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mandatos', '0003_ocupantecargo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargoComposicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alterado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('cargo_associacao', models.CharField(choices=[('PRESIDENTE_DIRETORIA_EXECUTIVA', 'Presidente da diretoria executiva'), ('VICE_PRESIDENTE_DIRETORIA_EXECUTIVA', 'Vice-Presidente da diretoria executiva'), ('SECRETARIO', 'Secretário'), ('TESOUREIRO', 'Tesoureiro'), ('VOGAL_1', 'Vogal 1'), ('VOGAL_2', 'Vogal 2'), ('VOGAL_3', 'Vogal 3'), ('VOGAL_4', 'Vogal 4'), ('VOGAL_5', 'Vogal 5'), ('PRESIDENTE_CONSELHO_FISCAL', 'Presidente do conselho fiscal'), ('CONSELHEIRO_1', 'Conselheiro 1'), ('CONSELHEIRO_2', 'Conselheiro 2'), ('CONSELHEIRO_3', 'Conselheiro 3'), ('CONSELHEIRO_4', 'Conselheiro 4')], default='PRESIDENTE_DIRETORIA_EXECUTIVA', max_length=50, verbose_name='Cargo Associação')),
                ('substituto', models.BooleanField(default=False, verbose_name='Substituto')),
                ('substituido', models.BooleanField(default=False, verbose_name='Substituido')),
                ('composicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargos_da_composicao_da_composicao', to='mandatos.composicao', verbose_name='Composição')),
                ('ocupante_do_cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cargos_da_composicao_do_ocupante', to='mandatos.ocupantecargo', verbose_name='Ocupante do Cargo')),
            ],
            options={
                'verbose_name': 'Cargo Composição',
                'verbose_name_plural': 'Cargos Composições',
            },
        ),
    ]
