# Generated by Django 3.2.21 on 2023-10-26 13:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0356_transferenciaeol_periodo_inicial_associacao'),
        ('mandatos', '0004_cargocomposicao'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoDeMigracao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alterado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('todas_as_unidades', models.BooleanField(default=False, help_text='Selecione esta opção se você deseja migrar todas as unidades de uma vez', verbose_name='Migrar todas as unidades')),
                ('dre', models.ForeignKey(blank=True, help_text='Escolha a DRE que você deseja migrar', limit_choices_to={'tipo_unidade': 'DRE'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='migracoes_da_dre', to='core.unidade', verbose_name='Migrar as unidades da DRE')),
                ('eol_unidade', models.ForeignKey(blank=True, help_text='Busque pelo código EOL da Unidade', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='migracoes_da_unidade', to='core.unidade', verbose_name='Migrar apenas uma unidade')),
            ],
            options={
                'verbose_name': 'Solicitação de migração',
                'verbose_name_plural': 'Solicitações de migração',
            },
        ),
    ]
