# Generated by Django 3.2.21 on 2023-10-26 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandatos', '0005_solicitacaodemigracao'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaodemigracao',
            name='log_execucao',
            field=models.TextField(blank=True, help_text='Log de execução da migração.', null=True, verbose_name='Log de migração'),
        ),
        migrations.AddField(
            model_name='solicitacaodemigracao',
            name='status_processamento',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('PROCESSANDO', 'Processando...'), ('SUCESSO', 'Sucesso'), ('ERRO', 'Erro')], default='PENDENTE', help_text='Status do processamento da migração.', max_length=20, verbose_name='Status do processamento'),
        ),
    ]
