# Generated by Django 3.2.21 on 2023-10-28 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandatos', '0006_auto_20231026_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargocomposicao',
            name='data_fim_no_cargo',
            field=models.DateField(blank=True, null=True, verbose_name='Data de término no cargo'),
        ),
        migrations.AddField(
            model_name='cargocomposicao',
            name='data_inicio_no_cargo',
            field=models.DateField(blank=True, null=True, verbose_name='Data de início no cargo'),
        ),
    ]
