# Generated by Django 4.2.7 on 2024-01-23 14:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mandatos", "0007_auto_20231028_1310"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cargocomposicao",
            name="substituido",
            field=models.BooleanField(
                blank=True, default=False, null=True, verbose_name="Substituido"
            ),
        ),
        migrations.AlterField(
            model_name="cargocomposicao",
            name="substituto",
            field=models.BooleanField(
                blank=True, default=False, null=True, verbose_name="Substituto"
            ),
        ),
    ]
