# Generated by Django 4.2.20 on 2026-08-24 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mandatos", "0008_alter_cargocomposicao_substituido_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cargocomposicao",
            name="cargo_associacao",
            field=models.CharField(
                choices=[
                    (
                        "PRESIDENTE_DIRETORIA_EXECUTIVA",
                        "Presidente da Diretoria Executiva",
                    ),
                    (
                        "VICE_PRESIDENTE_DIRETORIA_EXECUTIVA",
                        "Vice-Presidente da Diretoria Executiva",
                    ),
                    ("SECRETARIO", "Secretário"),
                    ("TESOUREIRO", "Tesoureiro"),
                    ("VOGAL_1", "Vogal 1"),
                    ("VOGAL_2", "Vogal 2"),
                    ("VOGAL_3", "Vogal 3"),
                    ("VOGAL_4", "Vogal 4"),
                    ("VOGAL_5", "Vogal 5"),
                    ("PRESIDENTE_CONSELHO_FISCAL", "Presidente do Conselho Fiscal"),
                    ("CONSELHEIRO_1", "Conselheiro 1"),
                    ("CONSELHEIRO_2", "Conselheiro 2"),
                    ("CONSELHEIRO_3", "Conselheiro 3"),
                    ("CONSELHEIRO_4", "Conselheiro 4"),
                ],
                default="PRESIDENTE_DIRETORIA_EXECUTIVA",
                max_length=50,
                verbose_name="Cargo Associação",
            ),
        ),
    ]
