# Generated by Django 4.2.20 on 2026-08-21 16:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0455_merge_20260810_1104"),
        ("mandatos", "0008_alter_cargocomposicao_substituido_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComposicaoVacancia",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "alterado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Alterado em"),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "data_inicial",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Data de início da composição",
                    ),
                ),
                (
                    "data_final",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Data de término da composição",
                    ),
                ),
                (
                    "associacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="composicoes_vacancia_da_associacao",
                        to="core.associacao",
                        verbose_name="Associação",
                    ),
                ),
                (
                    "mandato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="composicoes_vacancia_do_mandato",
                        to="mandatos.mandato",
                        verbose_name="Mandato",
                    ),
                ),
            ],
            options={
                "verbose_name": "Composição de Vacância",
                "verbose_name_plural": "Composições de Vacância",
            },
        ),
        migrations.CreateModel(
            name="CargoComposicaoVacancia",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "alterado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Alterado em"),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "cargo_associacao",
                    models.CharField(
                        choices=[
                            (
                                "PRESIDENTE_DIRETORIA_EXECUTIVA",
                                "Presidente da diretoria executiva",
                            ),
                            (
                                "VICE_PRESIDENTE_DIRETORIA_EXECUTIVA",
                                "Vice-Presidente da diretoria executiva",
                            ),
                            ("SECRETARIO", "Secretário"),
                            ("TESOUREIRO", "Tesoureiro"),
                            ("VOGAL_1", "Vogal 1"),
                            ("VOGAL_2", "Vogal 2"),
                            ("VOGAL_3", "Vogal 3"),
                            ("VOGAL_4", "Vogal 4"),
                            ("VOGAL_5", "Vogal 5"),
                            (
                                "PRESIDENTE_CONSELHO_FISCAL",
                                "Presidente do conselho fiscal",
                            ),
                            ("CONSELHEIRO_1", "Conselheiro 1"),
                            ("CONSELHEIRO_2", "Conselheiro 2"),
                            ("CONSELHEIRO_3", "Conselheiro 3"),
                            ("CONSELHEIRO_4", "Conselheiro 4"),
                        ],
                        default="PRESIDENTE_DIRETORIA_EXECUTIVA",
                        max_length=50,
                        verbose_name="Cargo Associação",
                    ),
                ),
                (
                    "data_inicio_no_cargo",
                    models.DateField(verbose_name="Data de início no cargo"),
                ),
                (
                    "data_fim_no_cargo",
                    models.DateField(verbose_name="Data de término no cargo"),
                ),
                (
                    "composicao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cargos_da_composicao_vacancia",
                        to="mandatos.composicaovacancia",
                        verbose_name="Composição",
                    ),
                ),
                (
                    "ocupante_do_cargo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cargos_da_composicao_vacancia_do_ocupante",
                        to="mandatos.ocupantecargo",
                        verbose_name="Ocupante do Cargo",
                    ),
                ),
                (
                    "substituido_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="substitui",
                        to="mandatos.cargocomposicaovacancia",
                        verbose_name="Substituído por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cargo Composição Vacância",
                "verbose_name_plural": "Cargos Composições Vacâncias",
            },
        ),
        migrations.AddConstraint(
            model_name="composicaovacancia",
            constraint=models.UniqueConstraint(
                fields=("associacao", "mandato"),
                name="uniq_composicao_vacancia_por_associacao_mandato",
            ),
        ),
    ]
