# Generated by Django 4.2.20 on 2026-08-24 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mandatos", "0009_composicaovacancia_cargocomposicaovacancia_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="composicaovacancia",
            name="data_final",
        ),
        migrations.RemoveField(
            model_name="composicaovacancia",
            name="data_inicial",
        ),
    ]
