# Generated by Django 4.2.20 on 2026-08-27 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mandatos", "0009_alter_cargocomposicao_cargo_associacao"),
        ("mandatos", "0010_remove_composicaovacancia_data_final_and_more"),
    ]

    operations = []
