# Carga Choice
CARGA_REPASSE_REALIZADO = 'REPASSE_REALIZADO'
CARGA_PERIODO_INICIAL = 'CARGA_PERIODO_INICIAL'
CARGA_REPASSE_PREVISTO = 'REPASSE_PREVISTO'
CARGA_ASSOCIACOES = 'CARGA_ASSOCIACOES'
CARGA_USUARIOS = 'CARGA_USUARIOS'
CARGA_CENSO = 'CARGA_CENSO'
CARGA_REPASSE_PREVISTO_SME = 'CARGA_REPASSE_PREVISTO_SME'

CARGA_NOMES = {
    CARGA_REPASSE_REALIZADO: 'Repasses realizados',
    CARGA_PERIODO_INICIAL: 'Carga período inicial',
    CARGA_REPASSE_PREVISTO: 'Repasses previstos',
    CARGA_ASSOCIACOES: 'Carga de Associações',
    CARGA_USUARIOS: 'Carga de usuários',
    CARGA_CENSO: 'Carga de censo',
    CARGA_REPASSE_PREVISTO_SME: 'Repasses previstos sme',
}

CARGA_CHOICES = (
    (CARGA_REPASSE_REALIZADO, CARGA_NOMES[CARGA_REPASSE_REALIZADO]),
    (CARGA_PERIODO_INICIAL, CARGA_NOMES[CARGA_PERIODO_INICIAL]),
    (CARGA_REPASSE_PREVISTO, CARGA_NOMES[CARGA_REPASSE_PREVISTO]),
    (CARGA_ASSOCIACOES, CARGA_NOMES[CARGA_ASSOCIACOES]),
    (CARGA_USUARIOS, CARGA_NOMES[CARGA_USUARIOS]),
    (CARGA_CENSO, CARGA_NOMES[CARGA_CENSO]),
    (CARGA_REPASSE_PREVISTO_SME, CARGA_NOMES[CARGA_REPASSE_PREVISTO_SME]),
)
