# Carga Choice
CARGA_REPASSE_REALIZADO = 'REPASSE_REALIZADO'
CARGA_PERIODO_INICIAL = 'CARGA_PERIODO_INICIAL'
CARGA_REPASSE_PREVISTO = 'REPASSE_PREVISTO'
CARGA_ASSOCIACOES = 'CARGA_ASSOCIACOES'
CARGA_CONTAS_ASSOCIACOES = 'CARGA_CONTAS_ASSOCIACOES'
CARGA_ACOES_ASSOCIACOES = 'CARGA_ACOES_ASSOCIACOES'
CARGA_USUARIOS = 'CARGA_USUARIOS'
CARGA_CENSO = 'CARGA_CENSO'
CARGA_REPASSE_PREVISTO_SME = 'CARGA_REPASSE_PREVISTO_SME'
CARGA_DEVOLUCAO_TESOURO = 'CARGA_DEVOLUCAO_TESOURO'
CARGA_MATERIAIS_SERVICOS = 'CARGA_MATERIAIS_SERVICOS'

CARGA_NOMES = {
    CARGA_REPASSE_REALIZADO: 'Repasses realizados',
    CARGA_PERIODO_INICIAL: 'Carga período inicial',
    CARGA_REPASSE_PREVISTO: 'Repasses previstos',
    CARGA_ASSOCIACOES: 'Carga de Associações',
    CARGA_CONTAS_ASSOCIACOES: 'Carga de Contas de Associações',
    CARGA_ACOES_ASSOCIACOES: 'Carga acões de Associações',
    CARGA_USUARIOS: 'Carga de usuários',
    CARGA_CENSO: 'Carga de censo',
    CARGA_REPASSE_PREVISTO_SME: 'Repasses previstos sme',
    CARGA_DEVOLUCAO_TESOURO: 'Devoluções ao Tesouro',
    CARGA_MATERIAIS_SERVICOS: 'Especificações de Materiais e Serviços'
}

CARGA_CHOICES = (
    (CARGA_REPASSE_REALIZADO, CARGA_NOMES[CARGA_REPASSE_REALIZADO]),
    (CARGA_PERIODO_INICIAL, CARGA_NOMES[CARGA_PERIODO_INICIAL]),
    (CARGA_REPASSE_PREVISTO, CARGA_NOMES[CARGA_REPASSE_PREVISTO]),
    (CARGA_ASSOCIACOES, CARGA_NOMES[CARGA_ASSOCIACOES]),
    (CARGA_CONTAS_ASSOCIACOES, CARGA_NOMES[CARGA_CONTAS_ASSOCIACOES]),
    (CARGA_ACOES_ASSOCIACOES, CARGA_NOMES[CARGA_ACOES_ASSOCIACOES]),
    (CARGA_USUARIOS, CARGA_NOMES[CARGA_USUARIOS]),
    (CARGA_CENSO, CARGA_NOMES[CARGA_CENSO]),
    (CARGA_REPASSE_PREVISTO_SME, CARGA_NOMES[CARGA_REPASSE_PREVISTO_SME]),
    (CARGA_DEVOLUCAO_TESOURO, CARGA_NOMES[CARGA_DEVOLUCAO_TESOURO]),
    (CARGA_MATERIAIS_SERVICOS, CARGA_NOMES[CARGA_MATERIAIS_SERVICOS])
)

CARGA_REQUER_PERIODO = {
    CARGA_REPASSE_REALIZADO: False,
    CARGA_PERIODO_INICIAL: False,
    CARGA_REPASSE_PREVISTO: True,
    CARGA_ASSOCIACOES: False,
    CARGA_ACOES_ASSOCIACOES: False,
    CARGA_USUARIOS: False,
    CARGA_CENSO: False,
    CARGA_REPASSE_PREVISTO_SME: False,
    CARGA_DEVOLUCAO_TESOURO: False,
    CARGA_MATERIAIS_SERVICOS: False
}

CARGA_REQUER_TIPO_CONTA = {
    CARGA_REPASSE_REALIZADO: False,
    CARGA_PERIODO_INICIAL: False,
    CARGA_REPASSE_PREVISTO: True,
    CARGA_ASSOCIACOES: False,
    CARGA_ACOES_ASSOCIACOES: False,
    CARGA_USUARIOS: False,
    CARGA_CENSO: False,
    CARGA_REPASSE_PREVISTO_SME: False,
    CARGA_DEVOLUCAO_TESOURO: False,
    CARGA_MATERIAIS_SERVICOS: False
}
