# Generated by Django 2.2.10 on 2020-03-18 20:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200318_1504'),
        ('despesas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alterado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('numero_documento', models.CharField(blank=True, default='', max_length=100, verbose_name='Nº do documento')),
                ('data_documento', models.DateField(blank=True, null=True, verbose_name='Data do documento')),
                ('cpf_cnpj_fornecedor', models.CharField(blank=True, default='', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Digite o CPF ou CNPJ no formato XX.XXX.XXX/XXXX-XX ou XXX.XXX.XXX-XX.', regex='(^\\d{3}\\.\\d{3}\\.\\d{3}\\-\\d{2}$)|(^\\d{2}\\.\\d{3}\\.\\d{3}\\/\\d{4}\\-\\d{2}$)')], verbose_name='CPF / CNPJ')),
                ('nome_fornecedor', models.CharField(max_length=100, verbose_name='Nome do fornecedor')),
                ('data_transacao', models.DateField(blank=True, null=True, verbose_name='Data da transacao')),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Valor Total')),
                ('valor_recursos_proprios', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Valor pago com recursos próprios')),
                ('associacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='despesas', to='core.Associacao')),
                ('tipo_documento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='despesas.TipoDocumento')),
                ('tipo_transacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='despesas.TipoTransacao')),
            ],
            options={
                'verbose_name': 'Despesa',
                'verbose_name_plural': 'Despesas',
            },
        ),
    ]
