# Generated by Django 2.2.10 on 2020-03-18 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0002_despesa'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesa',
            name='status',
            field=models.CharField(choices=[('COMPLETO', 'Completo'), ('INCOMPLETO', 'Incompleto')], default='INCOMPLETO', max_length=15, verbose_name='status'),
        ),
    ]
