# Generated by Django 2.2.10 on 2020-03-19 11:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0003_despesa_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoAplicacaoRecurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=160, verbose_name='Nome')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alterado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo de aplicação de recurso',
                'verbose_name_plural': 'Tipos de aplicação de recursos',
            },
        ),
    ]
