# Generated by Django 2.2.10 on 2020-03-19 12:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0004_tipoaplicacaorecurso'),
    ]

    operations = [
        migrations.CreateModel(
            name='EspecificacaoMaterialServico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alterado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
                ('tipo_aplicacao_recurso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='despesas.TipoAplicacaoRecurso')),
                ('tipo_custeio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='despesas.TipoCusteio')),
            ],
            options={
                'verbose_name': 'Especificação de material ou serviço',
                'verbose_name_plural': 'Especificações de materiais ou serviços',
            },
        ),
    ]
