# Generated by Django 2.2.10 on 2020-03-24 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0007_rateiodespesa_acao_associacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rateiodespesa',
            name='acao',
        ),
    ]
