# Generated by Django 2.2.10 on 2020-03-24 17:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('despesas', '0008_remove_rateiodespesa_acao'),
    ]

    operations = [
        migrations.AddField(
            model_name='rateiodespesa',
            name='status',
            field=models.CharField(choices=[('COMPLETO', 'Completo'), ('INCOMPLETO', 'Incompleto')],
                                   default='INCOMPLETO', max_length=15, verbose_name='status'),
        ),
    ]
