# Generated by Django 2.2.10 on 2020-03-24 19:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('despesas', '0010_rateiodespesa_aplicacao_recurso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rateiodespesa',
            name='tipo_aplicacao_recurso',
        ),
    ]
