# Generated by Django 2.2.10 on 2020-03-24 19:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('despesas', '0011_remove_rateiodespesa_tipo_aplicacao_recurso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rateiodespesa',
            name='aplicacao_recurso',
            field=models.CharField(choices=[('CAPITAL', 'Capital'), ('CUSTEIO', 'Custeio')], default='CUSTEIO',
                                   max_length=15, verbose_name='Tipo de aplicação do recurso'),
        ),
    ]
