# Generated by Django 2.2.10 on 2020-03-24 20:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('despesas', '0012_auto_20200324_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='especificacaomaterialservico',
            name='aplicacao_recurso',
            field=models.CharField(choices=[('CAPITAL', 'Capital'), ('CUSTEIO', 'Custeio')], default='CUSTEIO',
                                   max_length=15, verbose_name='Tipo de aplicação do recurso'),
        ),
    ]
