# Generated by Django 2.2.10 on 2020-03-24 20:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('despesas', '0013_especificacaomaterialservico_aplicacao_recurso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='especificacaomaterialservico',
            name='tipo_aplicacao_recurso',
        ),
    ]
