# Generated by Django 2.2.10 on 2020-03-24 20:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('despesas', '0014_remove_especificacaomaterialservico_tipo_aplicacao_recurso'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TipoAplicacaoRecurso',
        ),
    ]
