# Generated by Django 2.2.10 on 2020-04-03 17:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('despesas', '0015_delete_tipoaplicacaorecurso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='nome_fornecedor',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Nome do fornecedor'),
        ),
    ]
