# Generated by Django 2.2.10 on 2020-04-03 18:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('despesas', '0016_auto_20200403_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rateiodespesa',
            name='aplicacao_recurso',
            field=models.CharField(choices=[('CAPITAL', 'Capital'), ('CUSTEIO', 'Custeio')], default='CUSTEIO',
                                   max_length=15, null=True, verbose_name='Tipo de aplicação do recurso'),
        ),
    ]
