# Generated by Django 2.2.10 on 2020-05-29 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0019_rateiodespesa_conferido'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipotransacao',
            name='tem_documento',
            field=models.BooleanField(default=False, verbose_name='Tem documento?'),
        ),
    ]
