# Generated by Django 2.2.10 on 2020-05-29 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0020_tipotransacao_tem_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesa',
            name='documento_transacao',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Nº doc transação'),
        ),
    ]
