# Generated by Django 2.2.10 on 2020-06-24 15:31

from django.contrib.postgres.operations import UnaccentExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0022_rateiodespesa_prestacao_conta'),
    ]

    operations = [
        UnaccentExtension()
    ]
