# Generated by Django 2.2.10 on 2020-07-17 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0024_tipodocumento_apenas_digitos'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipodocumento',
            name='numero_documento_digitado',
            field=models.BooleanField(default=False, verbose_name='Número documento será digitado?'),
        ),
    ]
