# Generated by Django 2.2.10 on 2020-08-03 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0027_auto_20200729_0841'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesa',
            name='valor_original',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Valor original'),
        ),
    ]
