# Generated by Django 2.2.10 on 2020-08-03 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0028_despesa_valor_original'),
    ]

    operations = [
        migrations.AddField(
            model_name='rateiodespesa',
            name='valor_original',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Valor original'),
        ),
    ]
