# Generated by Django 2.2.10 on 2020-08-31 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0030_rateiodespesa_periodo_conciliacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rateiodespesa',
            name='prestacao_conta',
        ),
    ]
