# Generated by Django 2.2.10 on 2021-05-17 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0033_auto_20210212_0743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='status',
            field=models.CharField(choices=[('COMPLETO', 'Completo'), ('INCOMPLETO', 'Rascunho')], default='INCOMPLETO', max_length=15, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='rateiodespesa',
            name='status',
            field=models.CharField(choices=[('COMPLETO', 'Completo'), ('INCOMPLETO', 'Rascunho')], default='INCOMPLETO', max_length=15, verbose_name='status'),
        ),
    ]
