# Generated by Django 2.2.10 on 2021-06-24 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0034_auto_20210517_1001'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipocusteio',
            options={'verbose_name': 'Tipo de despesa de custeio', 'verbose_name_plural': 'Tipos de despesa de custeio'},
        ),
    ]
