# Generated by Django 2.2.10 on 2021-07-14 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0035_auto_20210624_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='rateiodespesa',
            name='saida_de_recurso_externo',
            field=models.BooleanField(default=False, verbose_name='É saída de recurso externo?'),
        ),
    ]
