# Generated by Django 2.2.10 on 2021-07-28 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0036_rateiodespesa_saida_de_recurso_externo'),
    ]

    operations = [
        migrations.AddField(
            model_name='rateiodespesa',
            name='eh_despesa_sem_comprovacao_fiscal',
            field=models.BooleanField(default=False, verbose_name='É despesa sem comprovação fiscal?'),
        ),
    ]
