# Generated by Django 2.2.10 on 2021-08-05 10:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0037_rateiodespesa_eh_despesa_sem_comprovacao_fiscal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedor',
            name='cpf_cnpj',
            field=models.CharField(blank=True, default='', max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Digite o CPF ou CNPJ no formato XX.XXX.XXX/XXXX-XX ou XXX.XXX.XXX-XX.', regex='(^\\d{3}\\.\\d{3}\\.\\d{3}\\-\\d{2}$)|(^\\d{2}\\.\\d{3}\\.\\d{3}\\/\\d{4}\\-\\d{2}$)')], verbose_name='CPF / CNPJ'),
        ),
    ]
