# Generated by Django 2.2.10 on 2021-09-13 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0038_auto_20210805_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='especificacaomaterialservico',
            name='ativa',
            field=models.BooleanField(default=True, verbose_name='Está ativa?'),
        ),
    ]
