# Generated by Django 2.2.10 on 2022-03-05 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0039_especificacaomaterialservico_ativa'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesa',
            name='eh_despesa_reconhecida_pela_associacao',
            field=models.BooleanField(default=True, verbose_name='É despesa reconhecida pela Associação?'),
        ),
        migrations.AddField(
            model_name='despesa',
            name='eh_despesa_sem_comprovacao_fiscal',
            field=models.BooleanField(default=False, verbose_name='É despesa sem comprovação fiscal?'),
        ),
        migrations.AddField(
            model_name='despesa',
            name='numero_boletim_de_ocorrencia',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Nº boletim de ocorrência'),
        ),
    ]
