# Generated by Django 2.2.10 on 2022-03-07 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0042_auto_20220307_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipocusteio',
            name='eh_tributos_e_tarifas',
            field=models.BooleanField(default=False, verbose_name='É Tributos e Tarifas?'),
        ),
    ]
