# Generated by Django 2.2.10 on 2022-03-10 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0043_tipocusteio_eh_tributos_e_tarifas'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesa',
            name='despesa_imposto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='despesa_geradora_do_imposto', to='despesas.Despesa', to_field='uuid'),
        ),
    ]
