# Generated by Django 2.2.10 on 2022-03-14 14:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0044_despesa_despesa_imposto'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotivoPagamentoAntecipado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alterado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('motivo', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Motivo de pagamento antecipado',
                'verbose_name_plural': 'Motivos de pagamento antecipado',
            },
        ),
    ]
