# Generated by Django 2.2.10 on 2022-03-14 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0045_motivopagamentoantecipado'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesa',
            name='motivos_pagamento_antecipado',
            field=models.ManyToManyField(blank=True, to='despesas.MotivoPagamentoAntecipado'),
        ),
        migrations.AddField(
            model_name='despesa',
            name='outros_motivos_pagamento_antecipado',
            field=models.TextField(blank=True, default='', verbose_name='Outros motivos para pagamento antecipado'),
        ),
    ]
