# Generated by Django 2.2.10 on 2022-03-25 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0046_auto_20220314_1417'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='despesa',
            options={'verbose_name': 'Documento comprobatório da despesa', 'verbose_name_plural': 'Documentos comprobatórios das despesas'},
        ),
    ]
