# Generated by Django 2.2.10 on 2022-04-05 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0047_auto_20220325_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipodocumento',
            name='documento_comprobatorio_de_despesa',
            field=models.BooleanField(default=True, verbose_name='Documento comprobatório de despesa'),
        ),
        migrations.AlterField(
            model_name='tipodocumento',
            name='eh_documento_de_retencao_de_imposto',
            field=models.BooleanField(default=False, verbose_name='Documento relativo ao imposto recolhido'),
        ),
        migrations.AlterField(
            model_name='tipodocumento',
            name='pode_reter_imposto',
            field=models.BooleanField(default=False, verbose_name='Habilita o preenchimento do imposto'),
        ),
    ]
