# Generated by Django 2.2.10 on 2022-04-06 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0048_despesa_despesas_impostos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='despesa',
            name='despesa_imposto',
        ),
    ]
