# Generated by Django 2.2.10 on 2022-04-07 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0049_remove_despesa_despesa_imposto'),
        ('despesas', '0048_auto_20220405_1035'),
    ]

    operations = [
    ]
