# Generated by Django 2.2.10 on 2022-05-16 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0050_merge_20220407_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipocusteio',
            name='eh_tributos_e_tarifas',
            field=models.BooleanField(default=False, verbose_name='Impostos de serviço'),
        ),
    ]
