# Generated by Django 2.2.10 on 2022-09-06 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0051_auto_20220516_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesa',
            name='data_e_hora_de_inativacao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Inativado em'),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='status',
            field=models.CharField(choices=[('COMPLETO', 'Completo'), ('INCOMPLETO', 'Rascunho'), ('INATIVO', 'Inativo')], default='INCOMPLETO', max_length=15, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='rateiodespesa',
            name='status',
            field=models.CharField(choices=[('COMPLETO', 'Completo'), ('INCOMPLETO', 'Rascunho'), ('INATIVO', 'Inativo')], default='INCOMPLETO', max_length=15, verbose_name='status'),
        ),
    ]
