# Generated by Django 4.2.11 on 2025-02-27 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("despesas", "0054_despesa_despesa_anterior_ao_uso_do_sistema_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="tipodocumento",
            unique_together={("nome",)},
        ),
    ]
