# Generated by Django 4.2.20 on 2025-10-10 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0416_alter_funcdreassociacoesdadre_options"),
        ("despesas", "0055_alter_tipodocumento_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="tipocusteio",
            name="unidades",
            field=models.ManyToManyField(blank=True, to="core.unidade"),
        ),
    ]
