# Generated by Django 4.2.20 on 2026-02-26 09:21

from django.db import migrations, models
import django.db.models.deletion


def atualiza_recurso_despesas(apps, schema_editor):
    Recurso = apps.get_model('core', 'Recurso')
    Despesa = apps.get_model('despesas', 'Despesa')

    recurso_legado = Recurso.objects.get(legado=True)

    Despesa.objects.filter(recurso__isnull=True).update(recurso=recurso_legado)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0429_alter_associacao_periodo_inicial"),
        ("despesas", "0056_tipocusteio_unidades"),
    ]

    operations = [
        migrations.AddField(
            model_name="despesa",
            name="recurso",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.recurso",
                verbose_name="Recurso",
            ),
        ),
        migrations.RunPython(atualiza_recurso_despesas, reverse_code=migrations.RunPython.noop),
    ]
