# Generated by Django 4.2.20 on 2026-06-12 16:06

from django.db import migrations, models
import sme_ptrf_apps.despesas.models.validators


class Migration(migrations.Migration):

    dependencies = [
        ("despesas", "0057_despesa_recurso"),
    ]

    operations = [
        migrations.AlterField(
            model_name="despesa",
            name="cpf_cnpj_fornecedor",
            field=models.CharField(
                blank=True,
                default="",
                max_length=20,
                null=True,
                validators=[
                    sme_ptrf_apps.despesas.models.validators.cpf_cnpj_validation
                ],
                verbose_name="CPF / CNPJ",
            ),
        ),
        migrations.AlterField(
            model_name="fornecedor",
            name="cpf_cnpj",
            field=models.CharField(
                blank=True,
                default="",
                max_length=20,
                null=True,
                unique=True,
                validators=[
                    sme_ptrf_apps.despesas.models.validators.cpf_cnpj_validation
                ],
                verbose_name="CPF / CNPJ",
            ),
        ),
    ]
