# Generated by Django 4.2.20 on 2026-09-16 08:19

from django.db import migrations
from django.db.models import Q


def limpar_campos_capital_de_rateios_custeio(apps, schema_editor):
    RateioDespesa = apps.get_model("despesas", "RateioDespesa")

    rateios = RateioDespesa.objects.filter(
        aplicacao_recurso="CUSTEIO",
    ).filter(
        Q(quantidade_itens_capital__gt=0)
        | Q(valor_item_capital__gt=0)
        | Q(nao_exibir_em_rel_bens=True)
        | (
            Q(numero_processo_incorporacao_capital__isnull=False)
            & ~Q(numero_processo_incorporacao_capital="")
        )
    )

    rateios.update(
        quantidade_itens_capital=0,
        valor_item_capital=0,
        nao_exibir_em_rel_bens=False,
        numero_processo_incorporacao_capital="",
    )


class Migration(migrations.Migration):

    dependencies = [
        ("despesas", "0058_alter_despesa_cpf_cnpj_fornecedor_and_more"),
    ]

    operations = [
        migrations.RunPython(
            limpar_campos_capital_de_rateios_custeio,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
