from .tecnicos_dre_viewset import TecnicosDreViewSet
from .faq_categorias_viewset import FaqCategoriasViewSet
from .faq_viewset import FaqsViewSet
from .atribuicao_viewset import AtribuicaoViewset
from .relatorios_consolidados_dre_viewset import RelatoriosConsolidadosDREViewSet
