# Generated by Django 2.2.10 on 2020-08-11 13:40

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoVerificacaoRegularidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alterado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo do grupo')),
            ],
            options={
                'verbose_name': 'Grupo de verificação de regularidade',
                'verbose_name_plural': 'Grupos de verificação de regularidade',
            },
        ),
        migrations.CreateModel(
            name='ListaVerificacaoRegularidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alterado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('titulo', models.CharField(max_length=100, verbose_name='Nome do Grupo')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listas_de_verificacao', to='dre.GrupoVerificacaoRegularidade')),
            ],
            options={
                'verbose_name': 'Lista de Verificação de Regularidade',
                'verbose_name_plural': 'Listas de Verificação de Regularidade',
            },
        ),
        migrations.CreateModel(
            name='ItemVerificacaoRegularidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alterado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('lista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_de_verificacao', to='dre.ListaVerificacaoRegularidade')),
            ],
            options={
                'verbose_name': 'Item de verificação de regularidade',
                'verbose_name_plural': 'Itens de verificação de regularidade',
            },
        ),
    ]
