# Generated by Django 2.2.10 on 2020-08-11 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dre', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listaverificacaoregularidade',
            name='titulo',
            field=models.CharField(max_length=100, verbose_name='Título da lista'),
        ),
    ]
