# Generated by Django 2.2.10 on 2020-08-11 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dre', '0002_auto_20200811_1451'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listaverificacaoregularidade',
            options={'verbose_name': 'Lista de verificação de regularidade', 'verbose_name_plural': 'Listas de verificação de regularidade'},
        ),
    ]
