# Generated by Django 2.2.10 on 2020-08-14 13:30

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_unidade_dre_designacao_ano'),
        ('dre', '0004_verificacaoregularidadeassociacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='TecnicoDre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alterado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nome', models.CharField(max_length=160, verbose_name='Nome')),
                ('rf', models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='RF')),
                ('dre', models.ForeignKey(blank=True, limit_choices_to={'tipo_unidade': 'DRE'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tecnicos_da_dre', to='core.Unidade')),
            ],
            options={
                'verbose_name': 'Técnico de DRE',
                'verbose_name_plural': 'Técnicos de DREs',
            },
        ),
    ]
