# Generated by Django 2.2.10 on 2020-08-19 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dre', '0005_tecnicodre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tecnicodre',
            name='rf',
            field=models.CharField(blank=True, default='', max_length=10, null=True, unique=True, verbose_name='RF'),
        ),
    ]
