# Generated by Django 2.2.10 on 2020-08-18 09:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_unidade_dre_designacao_ano'),
        ('dre', '0005_tecnicodre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atribuicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alterado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('periodo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='atribuicoes', to='core.Periodo')),
                ('tecnico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='atribuicoes', to='dre.TecnicoDre')),
                ('unidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='atribuicoes', to='core.Unidade')),
            ],
            options={
                'verbose_name': 'Atribuição',
                'verbose_name_plural': 'Atribuições',
            },
        ),
    ]
