# Generated by Django 2.2.10 on 2020-08-24 14:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dre', '0007_faqcategoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alterado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('pergunta', models.CharField(max_length=200)),
                ('resposta', models.TextField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='perguntas', to='dre.FaqCategoria')),
            ],
            options={
                'verbose_name': 'Faq - Pergunta e Resposta',
                'verbose_name_plural': 'Faqs - Perguntas e Respostas',
            },
        ),
    ]
