# Generated by Django 2.2.10 on 2020-08-25 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dre', '0008_faq'),
        ('dre', '0006_atribuicao'),
    ]

    operations = [
    ]
