# Generated by Django 2.2.10 on 2020-09-10 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dre', '0009_merge_20200825_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atribuicao',
            name='tecnico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='atribuicoes', to='dre.TecnicoDre'),
        ),
    ]
