# Generated by Django 2.2.10 on 2020-10-22 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dre', '0010_auto_20200910_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='tecnicodre',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='E-mail'),
        ),
    ]
