# Generated by Django 2.2.10 on 2020-10-22 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dre', '0011_tecnicodre_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='tecnicodre',
            name='telefone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Telefone'),
        ),
    ]
