# Generated by Django 2.2.10 on 2020-10-27 13:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0106_parametros_fique_de_olho_relatorio_dre'),
        ('dre', '0012_tecnicodre_telefone'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatorioConsolidadoDRE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alterado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='')),
                ('status', models.CharField(choices=[('NAO_GERADO', 'Não gerado'), ('GERADO_PARCIAL', 'Gerado Parcial'), ('GERADO_TOTAL', 'Gerado Total')], default='NAO_GERADO', max_length=20, verbose_name='status')),
                ('dre', models.ForeignKey(blank=True, limit_choices_to={'tipo_unidade': 'DRE'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='relatorios_consolidados_da_dre', to='core.Unidade')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relatorios_consolidados_dre_do_periodo', to='core.Periodo')),
                ('tipo_conta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.TipoConta')),
            ],
            options={
                'verbose_name': 'Relatório consolidado DRE',
                'verbose_name_plural': 'Relatórios consolidados DREs',
            },
        ),
    ]
