# Generated by Django 2.2.10 on 2020-10-28 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dre', '0013_relatorioconsolidadodre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatorioconsolidadodre',
            name='status',
            field=models.CharField(choices=[('NAO_GERADO', 'Relatório não gerado'), ('GERADO_PARCIAL', 'Relatório parcial gerado'), ('GERADO_TOTAL', 'Relatório final gerado')], default='NAO_GERADO', max_length=20, verbose_name='status'),
        ),
    ]
