# Generated by Django 2.2.10 on 2020-11-04 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0109_auto_20201030_1436'),
        ('dre', '0015_justificativarelatorioconsolidadodre'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='justificativarelatorioconsolidadodre',
            unique_together={('dre', 'tipo_conta', 'periodo')},
        ),
    ]
