# Generated by Django 2.2.10 on 2020-11-13 14:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0028_auto_20200929_2004'),
        ('core', '0114_auto_20201113_1327'),
        ('dre', '0016_auto_20201104_0956'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObsDevolucaoRelatorioConsolidadoDRE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alterado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('tipo_devolucao', models.CharField(choices=[('TESOURO', 'Devolução ao tesouro'), ('CONTA', 'Devolução à conta do PTRF')], default='CONTA', max_length=15, null=True, verbose_name='Categoria da receita')),
                ('observacao', models.TextField(blank=True, max_length=600, null=True, verbose_name='Observação')),
                ('dre', models.ForeignKey(blank=True, limit_choices_to={'tipo_unidade': 'DRE'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='observacoes_devolucoes_relatorios_consolidados_da_dre', to='core.Unidade')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='observacoes_devolucoes_relatorios_consolidados_dre_do_periodo', to='core.Periodo')),
                ('tipo_conta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.TipoConta')),
                ('tipo_devolucao_a_conta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='observacoes_dre_sobre_devolucoes_a_conta', to='receitas.DetalheTipoReceita')),
                ('tipo_devolucao_ao_tesouro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='observacoes_dre_sobre_devolucoes_ao_tesouro', to='core.TipoDevolucaoAoTesouro')),
            ],
            options={
                'verbose_name': 'Observação sobre devoluções de relatório consolidado DRE',
                'verbose_name_plural': 'Observações sobre devoluções em relatórios consolidados DREs',
                'unique_together': {('dre', 'tipo_conta', 'periodo', 'tipo_devolucao')},
            },
        ),
    ]
