# Generated by Django 2.2.10 on 2020-11-23 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dre', '0017_obsdevolucaorelatorioconsolidadodre'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='obsdevolucaorelatorioconsolidadodre',
            unique_together=set(),
        ),
    ]
