# Generated by Django 2.2.10 on 2021-04-28 14:05

from django.contrib.postgres.operations import UnaccentExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dre', '0021_motivoaprovacaoressalva'),
    ]

    operations = [
        UnaccentExtension()
    ]
