# Generated by Django 2.2.10 on 2021-07-27 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dre', '0022_ativa_unaccent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatorioconsolidadodre',
            name='status',
            field=models.CharField(choices=[('NAO_GERADO', 'Relatório não gerado'), ('GERADO_PARCIAL', 'Relatório parcial gerado'), ('GERADO_TOTAL', 'Relatório final gerado'), ('EM_PROCESSAMENTO', 'Em processamento')], default='NAO_GERADO', max_length=20, verbose_name='status'),
        ),
    ]
