# Generated by Django 2.2.10 on 2021-08-23 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dre', '0024_auto_20210727_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatorioconsolidadodre',
            name='versao',
            field=models.CharField(choices=[('FINAL', 'final'), ('PREVIA', 'prévio')], default='FINAL', max_length=20, verbose_name='versão'),
        ),
    ]
