# Generated by Django 2.2.10 on 2021-10-25 11:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dre', '0025_relatorioconsolidadodre_versao'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotivoReprovacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alterado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('motivo', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Motivo de reprovação',
                'verbose_name_plural': 'Motivos de reprovação',
            },
        ),
    ]
