# Generated by Django 2.2.10 on 2021-12-06 09:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dre', '0028_membrocomissao'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnoAnaliseRegularidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alterado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('ano', models.PositiveSmallIntegerField(default=2020, unique=True, validators=[django.core.validators.MaxValueValidator(2099), django.core.validators.MinValueValidator(2000)], verbose_name='Ano de análise de regularidade')),
            ],
            options={
                'verbose_name': 'Ano de análise de regularidade',
                'verbose_name_plural': 'Anos de análise de regularidade',
            },
        ),
    ]
