# Generated by Django 2.2.10 on 2021-12-07 09:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0233_analisevalorreprogramadoprestacaoconta'),
        ('dre', '0029_anoanaliseregularidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnaliseRegularidadeAssociacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alterado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status_regularidade', models.CharField(choices=[('PENDENTE', 'Pendente'), ('REGULAR', 'Regular')], default='PENDENTE', max_length=15, verbose_name='Status de Regularidade')),
                ('ano_analise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='analises_regularidade_no_ano', to='dre.AnoAnaliseRegularidade')),
                ('associacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='analises_regularidade_da_associacao', to='core.Associacao')),
            ],
            options={
                'verbose_name': 'Análise de regularidade de associação',
                'verbose_name_plural': 'Análises de regularidade de associações',
            },
        ),
    ]
