# Generated by Django 2.2.10 on 2021-12-07 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dre', '0030_analiseregularidadeassociacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificacaoregularidadeassociacao',
            name='analise_regularidade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verificacoes_da_analise', to='dre.AnaliseRegularidadeAssociacao'),
        ),
    ]
