# Generated by Django 2.2.10 on 2021-12-07 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dre', '0031_verificacaoregularidadeassociacao_analise_regularidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verificacaoregularidadeassociacao',
            name='associacao',
        ),
        migrations.RemoveField(
            model_name='verificacaoregularidadeassociacao',
            name='grupo_verificacao',
        ),
        migrations.RemoveField(
            model_name='verificacaoregularidadeassociacao',
            name='lista_verificacao',
        ),
    ]
