# Generated by Django 2.2.10 on 2021-12-08 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dre', '0032_auto_20211207_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='analiseregularidadeassociacao',
            name='motivo_nao_regularidade',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Motivo da não regularização da associação'),
        ),
    ]
