# Generated by Django 2.2.10 on 2022-01-26 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dre', '0034_auto_20220121_0741'),
    ]

    operations = [
        migrations.AddField(
            model_name='ataparecertecnico',
            name='data_portaria',
            field=models.DateField(blank=True, null=True, verbose_name='Data da portaria'),
        ),
        migrations.AddField(
            model_name='ataparecertecnico',
            name='numero_portaria',
            field=models.IntegerField(blank=True, null=True, verbose_name='Numero da portaria'),
        ),
        migrations.AlterField(
            model_name='ataparecertecnico',
            name='data_reuniao',
            field=models.DateField(blank=True, null=True, verbose_name='Data da reunião'),
        ),
        migrations.AlterField(
            model_name='ataparecertecnico',
            name='local_reuniao',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Local da reunião'),
        ),
    ]
