# Generated by Django 2.2.10 on 2022-03-07 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dre', '0035_auto_20220126_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='anoanaliseregularidade',
            name='atualizacao_em_massa',
            field=models.BooleanField(default=False, verbose_name='Atualização em massa?'),
        ),
        migrations.AddField(
            model_name='anoanaliseregularidade',
            name='status_atualizacao',
            field=models.CharField(choices=[('NENHUMA_REQUERIDA', 'Nenhuma atualização requerida'), ('AGUARDANDO_INICIO', 'Aguardando inicio de processo de atualização'), ('EM_PROCESAMENTO', 'Atualização de regularidade em processamento'), ('CONCLUIDA', 'Atualização de regularidade concluída')], default='NENHUMA_REQUERIDA', max_length=50, verbose_name='Status do processo de atualização'),
        ),
    ]
