# Generated by Django 2.2.10 on 2022-03-07 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dre', '0036_auto_20220307_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anoanaliseregularidade',
            name='atualizacao_em_massa',
            field=models.BooleanField(default=False, verbose_name='Atualização em massa do status de regularidade?'),
        ),
    ]
