# Generated by Django 2.2.10 on 2022-06-03 14:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0257_auto_20220518_1659'),
        ('dre', '0037_auto_20220307_0921'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsolidadoDRE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alterado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('NAO_GERADOS', 'Documentos não gerados'), ('GERADOS_PARCIAIS', 'Documentos parciais gerados'), ('GERADOS_TOTAIS', 'Documentos finais gerados'), ('EM_PROCESSAMENTO', 'Documentos em processamento')], default='NAO_GERADOS', max_length=20, verbose_name='status')),
                ('dre', models.ForeignKey(blank=True, limit_choices_to={'tipo_unidade': 'DRE'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consolidados_dre_da_dre', to='core.Unidade')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consolidados_dre_do_periodo', to='core.Periodo')),
            ],
            options={
                'verbose_name': 'Consolidado DRE',
                'verbose_name_plural': 'Consolidados DREs',
            },
        ),
    ]
