# Generated by Django 2.2.10 on 2022-06-09 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0258_associacao_status_valores_reprogramados'),
        ('dre', '0037_auto_20220307_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametrosdre',
            name='tipo_conta_dois',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipo_conta_dois', to='core.TipoConta'),
        ),
        migrations.AddField(
            model_name='parametrosdre',
            name='tipo_conta_um',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipo_conta_um', to='core.TipoConta'),
        ),
    ]
