# Generated by Django 2.2.10 on 2022-06-06 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dre', '0039_auto_20220603_1445'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='relatorioconsolidadodre',
            options={'verbose_name': 'Relatório físico-financeiro DRE', 'verbose_name_plural': 'Relatórios físico-financeiros DREs'},
        ),
        migrations.AddField(
            model_name='relatorioconsolidadodre',
            name='consolidado_dre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='relatorios_consolidados_dre_do_consolidado_dre', to='dre.ConsolidadoDRE'),
        ),
    ]
