# Generated by Django 2.2.10 on 2022-06-13 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dre', '0038_auto_20220609_1208'),
        ('dre', '0040_auto_20220606_0949'),
    ]

    operations = [
    ]
