# Generated by Django 2.2.10 on 2022-06-23 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dre', '0041_merge_20220613_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='ataparecertecnico',
            name='consolidado_dre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='atas_de_parecer_tecnico_do_consolidado_dre', to='dre.ConsolidadoDRE'),
        ),
    ]
