# Generated by Django 2.2.10 on 2022-06-27 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0262_merge_20220623_1056'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dre', '0042_ataparecertecnico_consolidado_dre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lauda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alterado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('arquivo_lauda_txt', models.FileField(blank=True, null=True, upload_to='', verbose_name='Arquivo Lauda TXT')),
                ('status', models.CharField(choices=[('NAO_GERADA', 'Lauda não gerada'), ('GERADA_PARCIAL', 'Lauda parcial gerada'), ('GERADA_TOTAL', 'Lauda final gerada'), ('EM_PROCESSAMENTO', 'Lauda em processamento')], default='NAO_GERADA', max_length=20, verbose_name='status')),
                ('consolidado_dre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='laudas_do_consolidado_dre', to='dre.ConsolidadoDRE')),
                ('dre', models.ForeignKey(blank=True, limit_choices_to={'tipo_unidade': 'DRE'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='laudas_da_dre', to='core.Unidade')),
                ('periodo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='laudas_do_periodo', to='core.Periodo')),
                ('tipo_conta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='laudas_do_tipo_conta', to='core.TipoConta')),
                ('usuario', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='laudas_do_usuario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lauda',
                'verbose_name_plural': 'Laudas',
            },
        ),
    ]
