# Generated by Django 2.2.10 on 2022-07-04 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dre', '0043_lauda'),
    ]

    operations = [
        migrations.AddField(
            model_name='consolidadodre',
            name='versao',
            field=models.CharField(choices=[('FINAL', 'final'), ('PREVIA', 'prévia')], default='FINAL', max_length=20, verbose_name='versão'),
        ),
    ]
