# Generated by Django 2.2.10 on 2022-07-07 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0262_merge_20220623_1056'),
        ('dre', '0044_consolidadodre_versao'),
    ]

    operations = [
        migrations.AddField(
            model_name='consolidadodre',
            name='eh_parcial',
            field=models.BooleanField(default=True, verbose_name='É parcial?'),
        ),
        migrations.AddField(
            model_name='consolidadodre',
            name='sequencia_de_publicacao',
            field=models.IntegerField(blank=True, null=True, verbose_name='Sequência de publicação'),
        ),
        migrations.AlterUniqueTogether(
            name='consolidadodre',
            unique_together={('periodo', 'dre', 'sequencia_de_publicacao')},
        ),
    ]
