# Generated by Django 2.2.10 on 2022-07-12 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dre', '0045_auto_20220707_0659'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consolidadodre',
            options={'ordering': ['-sequencia_de_publicacao'], 'verbose_name': 'Consolidado DRE', 'verbose_name_plural': 'Consolidados DREs'},
        ),
        migrations.AddField(
            model_name='ataparecertecnico',
            name='sequencia_de_publicacao',
            field=models.IntegerField(blank=True, null=True, verbose_name='Sequência de publicação'),
        ),
    ]
