# Generated by Django 2.2.10 on 2022-08-08 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dre', '0046_auto_20220712_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ataparecertecnico',
            name='consolidado_dre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='atas_de_parecer_tecnico_do_consolidado_dre', to='dre.ConsolidadoDRE'),
        ),
    ]
