# Generated by Django 2.2.10 on 2022-08-08 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dre', '0048_auto_20220808_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lauda',
            name='consolidado_dre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='laudas_do_consolidado_dre', to='dre.ConsolidadoDRE'),
        ),
    ]
