# Generated by Django 2.2.10 on 2022-08-09 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dre', '0049_auto_20220808_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatorioconsolidadodre',
            name='versao',
            field=models.CharField(choices=[('FINAL', 'final'), ('PREVIA', 'prévio'), ('CONSOLIDADA', 'consolidado')], default='FINAL', max_length=20, verbose_name='versão'),
        ),
    ]
