# Generated by Django 2.2.10 on 2022-09-12 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dre', '0050_auto_20220809_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='justificativarelatorioconsolidadodre',
            name='consolidado_dre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='justificativas_relatorios_consolidados_dre_do_consolidado_dre', to='dre.ConsolidadoDRE'),
        ),
        migrations.AlterUniqueTogether(
            name='justificativarelatorioconsolidadodre',
            unique_together=set(),
        ),
    ]
