# Generated by Django 2.2.10 on 2022-09-13 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dre', '0051_auto_20220912_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='justificativarelatorioconsolidadodre',
            name='consolidado_dre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='justificativas_relatorios_consolidados_dre_do_consolidado_dre', to='dre.ConsolidadoDRE'),
        ),
    ]
