# Generated by Django 2.2.10 on 2022-09-26 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dre', '0052_auto_20220913_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='consolidadodre',
            name='data_publicacao',
            field=models.DateField(blank=True, null=True, verbose_name='Publicado em'),
        ),
        migrations.AddField(
            model_name='consolidadodre',
            name='pagina_publicacao',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Página publicacao'),
        ),
        migrations.AddField(
            model_name='consolidadodre',
            name='status_sme',
            field=models.CharField(choices=[('NAO_PUBLICADO', 'Não publicado'), ('PUBLICADO', 'Publicado'), ('EM_ANALISE', 'Em análise'), ('DEVOLVIDO', 'Devolvido'), ('ANALISADO', 'Analisado')], default='NAO_PUBLICADO', max_length=30, verbose_name='status SME'),
        ),
    ]
