# Generated by Django 2.2.10 on 2022-10-10 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dre', '0053_auto_20220926_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='consolidadodre',
            name='data_de_inicio_da_analise',
            field=models.DateField(blank=True, null=True, verbose_name='Data de início da análise (data de recebimento)'),
        ),
    ]
