# Generated by Django 2.2.10 on 2022-10-13 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dre', '0054_documentoadicional'),
        ('dre', '0054_consolidadodre_data_de_inicio_da_analise'),
    ]

    operations = [
    ]
