# Generated by Django 2.2.10 on 2022-10-19 09:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dre', '0055_merge_20221013_0951'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComentarioAnaliseConsolidadoDRE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alterado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('ordem', models.PositiveSmallIntegerField(verbose_name='ordem')),
                ('comentario', models.TextField(blank=True, max_length=600, null=True, verbose_name='Comentário')),
                ('notificado', models.BooleanField(default=False, verbose_name='Foi notificado?')),
                ('notificado_em', models.DateField(blank=True, null=True, verbose_name='Notificado em')),
                ('consolidado_dre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_de_analise_do_consolidado_dre', to='dre.ConsolidadoDRE')),
            ],
            options={
                'verbose_name': 'Comentário de análise do consolidado DRE',
                'verbose_name_plural': 'Comentários de análises dos consolidados DRE',
            },
        ),
    ]
