# Generated by Django 2.2.10 on 2022-10-21 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dre', '0055_merge_20221013_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='consolidadodre',
            name='responsavel_pela_analise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consolidado_dre_usuario_responsavel', to=settings.AUTH_USER_MODEL, verbose_name='Responsável'),
        ),
    ]
