# Generated by Django 2.2.10 on 2022-10-25 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dre', '0056_consolidadodre_responsavel_pela_analise'),
        ('dre', '0056_comentarioanaliseconsolidadodre'),
    ]

    operations = [
    ]
