# Generated by Django 2.2.10 on 2022-10-25 10:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dre', '0057_merge_20221025_0944'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnaliseConsolidadoDre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alterado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('consolidado_dre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analises_do_consolidado_dre', to='dre.ConsolidadoDRE')),
            ],
            options={
                'verbose_name': 'Análise consolidado DRE',
                'verbose_name_plural': 'Análises consolidados DRE',
            },
        ),
    ]
