# Generated by Django 2.2.10 on 2022-10-25 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dre', '0058_analiseconsolidadodre'),
    ]

    operations = [
        migrations.AddField(
            model_name='consolidadodre',
            name='analise_atual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consolidado_dre_da_analise_atual', to='dre.AnaliseConsolidadoDre'),
        ),
    ]
