# Generated by Django 2.2.10 on 2022-10-31 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dre', '0057_merge_20221024_1005'),
        ('dre', '0059_consolidadodre_analise_atual'),
    ]

    operations = [
    ]
