# Generated by Django 2.2.10 on 2022-10-27 11:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dre', '0059_consolidadodre_analise_atual'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnaliseDocumentoConsolidadoDre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alterado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('detalhamento', models.TextField(blank=True, default='', max_length=600, verbose_name='Motivo')),
                ('resultado', models.CharField(choices=[('CORRETO', 'Documento Correto'), ('AJUSTE', 'Ajuste necessário')], default='CORRETO', max_length=20, verbose_name='status')),
                ('analise_consolidado_dre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analises_de_documentos_da_analise_do_consolidado', to='dre.AnaliseConsolidadoDre')),
                ('ata_parecer_tecnico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analises_de_documentos_da_ata_parecer_tecnico', to='dre.AtaParecerTecnico')),
                ('documento_adicional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analises_de_documentos_do_documento_adicional', to='dre.DocumentoAdicional')),
                ('relatorio_consolidao_dre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analises_de_documentos_do_relatorio_consolidao_dre', to='dre.RelatorioConsolidadoDRE')),
            ],
            options={
                'verbose_name': 'Análise de documento do consolidado DRE',
                'verbose_name_plural': 'Análises de documentos dos consolidados DRE',
            },
        ),
    ]
