# Generated by Django 2.2.10 on 2022-11-03 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dre', '0060_analisedocumentoconsolidadodre'),
        ('dre', '0060_merge_20221031_1515'),
    ]

    operations = [
    ]
