# Generated by Django 2.2.10 on 2022-11-10 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dre', '0061_merge_20221103_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='analiseconsolidadodre',
            name='data_devolucao',
            field=models.DateField(blank=True, null=True, verbose_name='data da devolução pela SME'),
        ),
        migrations.AddField(
            model_name='analiseconsolidadodre',
            name='data_limite',
            field=models.DateField(blank=True, null=True, verbose_name='data para reenvio para SME após acertos'),
        ),
        migrations.AddField(
            model_name='analiseconsolidadodre',
            name='data_retorno_analise',
            field=models.DateField(blank=True, null=True, verbose_name='data para retorno da análise para SME'),
        ),
    ]
