# Generated by Django 2.2.10 on 2022-11-11 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dre', '0062_auto_20221110_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='analiseconsolidadodre',
            name='relatorio_acertos_gerado_em',
            field=models.DateTimeField(null=True, verbose_name='Arquivo pdf de solicitação de acertos gerado em'),
        ),
        migrations.AddField(
            model_name='analiseconsolidadodre',
            name='relatorio_acertos_pdf',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Relatório em PDF de apresentação após acertos'),
        ),
        migrations.AddField(
            model_name='analiseconsolidadodre',
            name='relatorio_acertos_status',
            field=models.CharField(choices=[('NAO_GERADO', 'Não gerado'), ('EM_PROCESSAMENTO', 'Em processamento'), ('CONCLUIDO', 'Geração concluída')], default='NAO_GERADO', max_length=20, verbose_name='Status da geração do documento de apresentação após acertos'),
        ),
        migrations.AddField(
            model_name='analiseconsolidadodre',
            name='relatorio_acertos_versao',
            field=models.CharField(choices=[('-', '-'), ('FINAL', 'final'), ('RASCUNHO', 'rascunho')], default='-', max_length=20, verbose_name='Versão do documento de apresentação após acertos'),
        ),
    ]
