# Generated by Django 2.2.10 on 2022-12-09 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dre', '0065_analisedocumentoconsolidadodre_documento_devolvido'),
    ]

    operations = [
        migrations.AddField(
            model_name='consolidadodre',
            name='consolidado_retificado',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='retificacao', to='dre.ConsolidadoDRE'),
        ),
    ]
