# Generated by Django 2.2.10 on 2022-12-06 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dre', '0065_analisedocumentoconsolidadodre_documento_devolvido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analiseconsolidadodre',
            name='copiado',
        ),
        migrations.RemoveField(
            model_name='analisedocumentoconsolidadodre',
            name='documento_devolvido',
        ),
        migrations.AddField(
            model_name='analisedocumentoconsolidadodre',
            name='copiado',
            field=models.BooleanField(default=False, verbose_name='é uma copiá?'),
        ),
    ]
