# Generated by Django 2.2.10 on 2022-12-09 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dre', '0066_consolidadodre_consolidado_retificado'),
    ]

    operations = [
        migrations.AddField(
            model_name='consolidadodre',
            name='sequencia_de_retificacao',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Sequência de retificação'),
        ),
    ]
