# Generated by Django 2.2.10 on 2022-12-09 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dre', '0067_consolidadodre_sequencia_de_retificacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consolidadodre',
            name='consolidado_retificado',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='retificacoes', to='dre.ConsolidadoDRE'),
        ),
    ]
