# Generated by Django 2.2.10 on 2022-12-12 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dre', '0068_auto_20221209_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='consolidadodre',
            name='motivo_retificacao',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo de retificação'),
        ),
    ]
