# Generated by Django 2.2.10 on 2022-12-21 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0302_auto_20221129_1118'),
        ('dre', '0069_consolidadodre_motivo_retificacao'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='consolidadodre',
            unique_together={('periodo', 'dre', 'sequencia_de_publicacao', 'sequencia_de_retificacao')},
        ),
    ]
