# Generated by Django 2.2.10 on 2022-12-21 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dre', '0066_auto_20221206_1142'),
        ('dre', '0070_auto_20221221_0729'),
    ]

    operations = [
    ]
