# Generated by Django 2.2.10 on 2023-01-31 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dre', '0072_consolidadodre_gerou_uma_retificacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='ataparecertecnico',
            name='sequencia_de_retificacao',
            field=models.IntegerField(blank=True, null=True, verbose_name='Sequência de retificação'),
        ),
    ]
