# Generated by Django 2.2.10 on 2023-02-09 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dre', '0073_ataparecertecnico_sequencia_de_retificacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='justificativarelatorioconsolidadodre',
            name='eh_retificacao',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='É uma justificativa de retificação ?'),
        ),
    ]
