# Generated by Django 2.2.10 on 2023-02-16 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0307_auto_20230215_1010'),
        ('dre', '0074_justificativarelatorioconsolidadodre_eh_retificacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='consolidadodre',
            name='pcs_do_consolidado',
            field=models.ManyToManyField(blank=True, null=True, related_name='consolidados_dre_da_prestacao_de_contas', to='core.PrestacaoConta'),
        ),
    ]
