# Generated by Django 2.2.10 on 2023-02-22 16:52

import logging

from django.db import migrations

logger = logging.getLogger(__name__)


def update_pcs_do_consolidado(apps, schema_editor):
    model_consolidado_dre = apps.get_model('dre', 'ConsolidadoDre')

    consolidados_originais = model_consolidado_dre.objects.filter(
        consolidado_retificado__isnull=True,
        versao='FINAL'
    ).all()
    logger.info(f'Atualizando pcs de {consolidados_originais.count()} consolidados originais')
    for consolidado in consolidados_originais:
        logger.info(f'Atualizando pcs do consolidado {consolidado.id}')
        consolidado.pcs_do_consolidado.set(consolidado.prestacoes_de_conta_do_consolidado_dre.all())

    consolidados_retificacao = model_consolidado_dre.objects.filter(consolidado_retificado__isnull=False).all()
    logger.info(f'Atualizando pcs de {consolidados_retificacao.count()} consolidados de retificação')
    for consolidado in consolidados_retificacao:
        logger.info(f'Atualizando pcs do consolidado {consolidado.id}')
        consolidado.pcs_do_consolidado.set(consolidado.prestacoes_de_conta_do_consolidado_dre.all())


class Migration(migrations.Migration):

    dependencies = [
        ('dre', '0076_auto_20230217_1620'),
    ]

    operations = [
        migrations.RunPython(update_pcs_do_consolidado, reverse_code=migrations.RunPython.noop)
    ]
