# Generated by Django 4.2.20 on 2026-04-09 11:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("dre", "0078_lauda_sem_movimentacao"),
    ]

    operations = [
        migrations.CreateModel(
            name="AtaParecerTecnicoSnapshot",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "alterado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Alterado em"),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("dados", models.JSONField(default=dict)),
                ("schema_version", models.PositiveSmallIntegerField(default=1)),
                (
                    "origem",
                    models.CharField(
                        choices=[
                            ("PUBLICACAO", "Publicacao"),
                            ("MANUAL", "Manual"),
                            ("TELA", "Tela"),
                            ("MIGRACAO", "Migracao"),
                        ],
                        default="PUBLICACAO",
                        max_length=20,
                    ),
                ),
                ("hash_dados", models.CharField(max_length=64)),
                ("congelado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "ata",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshot",
                        to="dre.ataparecertecnico",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ata de Parecer Tecnico - Snapshot",
                "verbose_name_plural": "Atas de Parecer Tecnico - Snapshots",
            },
        ),
    ]
