# Generated by Django 4.2.20 on 2026-05-11 16:50

from django.db import migrations, models
import django.db.models.deletion

def atualiza_recurso_motivo_aprovacao_ressalva(apps, schema_editor):
    Recurso = apps.get_model('core', 'Recurso')
    MotivoAprovacaoRessalva = apps.get_model('dre', 'MotivoAprovacaoRessalva')

    recurso_legado = Recurso.objects.get(legado=True)

    MotivoAprovacaoRessalva.objects.filter(recurso__isnull=True).update(recurso=recurso_legado)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0440_recurso_habilita_aprovacao_com_ressalvas"),
        ("dre", "0079_ataparecertecnicosnapshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="motivoaprovacaoressalva",
            name="recurso",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="motivo_aprovacao_ressalva_recurso",
                to="core.recurso",
                verbose_name="Recurso",
            ),
        ),
        migrations.RunPython(atualiza_recurso_motivo_aprovacao_ressalva, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name="motivoaprovacaoressalva",
            name="recurso",
            field=models.ForeignKey(
                blank=False,
                null=False,
                on_delete=models.deletion.PROTECT,
                related_name="motivo_aprovacao_ressalva_recurso",
                to="core.recurso",
                verbose_name="Recurso",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="motivoaprovacaoressalva",
            unique_together={("motivo", "recurso")},
        ),
    ]
