# Generated by Django 4.2.20 on 2026-05-12 12:14

from django.db import migrations, models
import django.db.models.deletion

def atualiza_motivoreprovacao_recurso_para_legado(apps, schema_editor):
    MotivoReprovacao = apps.get_model('dre', 'MotivoReprovacao')
    Recurso = apps.get_model('core', 'Recurso')

    recurso = Recurso.objects.filter(legado=True).first()
    if recurso:
        MotivoReprovacao.objects.all().update(recurso=recurso)

class Migration(migrations.Migration):

    dependencies = [
        ("core", "0440_recurso_habilita_aprovacao_com_ressalvas"),
        ("dre", "0079_ataparecertecnicosnapshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="motivoreprovacao",
            name="recurso",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="motivos_reprovacao",
                to="core.recurso",
                verbose_name="recurso",
            ),
        ),
        migrations.RunPython(atualiza_motivoreprovacao_recurso_para_legado, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name="motivoreprovacao",
            name="recurso",
            field=models.ForeignKey(
                blank=False,
                null=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="motivos_reprovacao",
                to="core.recurso",
                verbose_name="recurso",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="motivoreprovacao",
            unique_together={("motivo", "recurso")},
        ),
    ]
