# Generated by Django 4.2.20 on 2026-05-14 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dre", "0080_motivoaprovacaoressalva_recurso_and_more"),
        ("dre", "0080_motivoreprovacao_recurso_and_more"),
    ]

    operations = []
