# Generated by Django 4.2.20 on 2026-06-02 11:53

from django.db import migrations, models

def atualiza_comissao_responsavel_analise_pc(apps, schema_editor):
    Comissao = apps.get_model('dre', 'Comissao')
    ParametrosDre = apps.get_model('dre', 'ParametrosDre')

    comissoes_resposaveis_prestacao_contas = ParametrosDre.objects.filter(comissao_exame_contas__isnull=False).first()
    if comissoes_resposaveis_prestacao_contas:
        Comissao.objects.filter(pk__in=[comissoes_resposaveis_prestacao_contas.comissao_exame_contas_id]).update(responsavel_analise_pc=True)

def atualiza_comissao_recurso_para_legado(apps, schema_editor):
    Comissao = apps.get_model('dre', 'Comissao')
    Recurso = apps.get_model('core', 'Recurso')

    recurso = Recurso.objects.filter(legado=True).first()
    if recurso:
        comissoes = Comissao.objects.filter(recursos__isnull=True)
        for comissao in comissoes:
            comissao.recursos.add(recurso)

class Migration(migrations.Migration):

    dependencies = [
        ("core", "0442_alter_recurso_exibe_valores_reprogramados"),
        ("dre", "0082_lauda_arquivo_pdf"),
    ]

    operations = [
        migrations.AddField(
            model_name="comissao",
            name="recursos",
            field=models.ManyToManyField(
                blank=False, related_name="comissoes", to="core.recurso"
            ),
        ),
        migrations.AddField(
            model_name="comissao",
            name="responsavel_analise_pc",
            field=models.BooleanField(
                default=False,
                help_text="Indica se esta comissão é responsável pela análise de prestação de contas do recurso",
                verbose_name="Responsável pela análise de prestação de contas?",
            ),
        ),
        migrations.RunPython(atualiza_comissao_responsavel_analise_pc, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(atualiza_comissao_recurso_para_legado, reverse_code=migrations.RunPython.noop),
    ]
