# Status Choice
STATUS_COMPLETO = 'COMPLETO'
STATUS_INCOMPLETO = 'INCOMPLETO'

STATUS_NOMES = {
    STATUS_COMPLETO: 'Completo',
    STATUS_INCOMPLETO: 'Rascunho',
}

STATUS_CHOICES = (
    (STATUS_COMPLETO, STATUS_NOMES[STATUS_COMPLETO]),
    (STATUS_INCOMPLETO, STATUS_NOMES[STATUS_INCOMPLETO]),
)
