# Generated by Django 4.2.20 on 2025-05-14 04:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("despesas", "0055_alter_tipodocumento_unique_together"),
        ("core", "0406_merge_20250408_0913"),
    ]

    operations = [
        migrations.CreateModel(
            name="BemProduzido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "alterado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Alterado em"),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "num_processo_incorporacao",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        null=True,
                        verbose_name="Nº do processo de incorporação",
                    ),
                ),
                (
                    "quantidade",
                    models.IntegerField(
                        blank=True, default=0, null=True, verbose_name="Quantidade"
                    ),
                ),
                (
                    "valor_individual",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        null=True,
                        verbose_name="Valor individual",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("COMPLETO", "Completo"), ("INCOMPLETO", "Rascunho")],
                        default="INCOMPLETO",
                        max_length=15,
                        verbose_name="status",
                    ),
                ),
                (
                    "associacao",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bens_produzidos_associacao",
                        to="core.associacao",
                    ),
                ),
                (
                    "especificacao_do_bem",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="despesas.especificacaomaterialservico",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bem produzido",
                "verbose_name_plural": "Bens produzidos",
            },
        ),
        migrations.CreateModel(
            name="BemProduzidoDespesa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "alterado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Alterado em"),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "bem_produzido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="despesas",
                        to="situacao_patrimonial.bemproduzido",
                    ),
                ),
                (
                    "despesa",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="despesa_bem_produzido",
                        to="despesas.despesa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Despesa de bem produzido",
                "verbose_name_plural": "Despesas de bens produzidos",
            },
        ),
    ]
