# Generated by Django 4.2.20 on 2025-05-26 18:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("despesas", "0055_alter_tipodocumento_unique_together"),
        ("situacao_patrimonial", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BemProduzidoRateio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "alterado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Alterado em"),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "valor_disponivel",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=8,
                        verbose_name="Valor disponível",
                    ),
                ),
                (
                    "bem_produzido_despesa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rateios",
                        to="situacao_patrimonial.bemproduzidodespesa",
                    ),
                ),
                (
                    "rateio",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rateio_bem_produzido",
                        to="despesas.rateiodespesa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rateio de despesa de bem produzido",
                "verbose_name_plural": "Rateios de despesa de bem produzido",
            },
        ),
    ]
