# Generated by Django 4.2.20 on 2025-05-27 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("situacao_patrimonial", "0002_bemproduzidorateio"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bemproduzidorateio",
            name="valor_disponivel",
        ),
        migrations.AddField(
            model_name="bemproduzidorateio",
            name="valor_utilizado",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=8,
                verbose_name="Valor utilizado",
            ),
        ),
    ]
