# Generated by Django 4.2.20 on 2025-06-05 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "situacao_patrimonial",
            "0003_remove_bemproduzidorateio_valor_disponivel_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bemproduzido",
            name="especificacao_do_bem",
        ),
        migrations.RemoveField(
            model_name="bemproduzido",
            name="num_processo_incorporacao",
        ),
        migrations.RemoveField(
            model_name="bemproduzido",
            name="quantidade",
        ),
        migrations.RemoveField(
            model_name="bemproduzido",
            name="valor_individual",
        ),
        migrations.AddField(
            model_name="bemproduzidodespesa",
            name="valor_recurso_proprio_utilizado",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=8,
                verbose_name="Valor recurso próprio utilizado",
            ),
        ),
    ]
