# Generated by Django 4.2.20 on 2025-06-06 07:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("despesas", "0055_alter_tipodocumento_unique_together"),
        (
            "situacao_patrimonial",
            "0004_remove_bemproduzido_especificacao_do_bem_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="BemProduzidoItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "alterado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Alterado em"),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "num_processo_incorporacao",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        null=True,
                        verbose_name="Nº do processo de incorporação",
                    ),
                ),
                (
                    "quantidade",
                    models.IntegerField(
                        blank=True, default=0, null=True, verbose_name="Quantidade"
                    ),
                ),
                (
                    "valor_individual",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        null=True,
                        verbose_name="Valor individual",
                    ),
                ),
                (
                    "bem_produzido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="situacao_patrimonial.bemproduzido",
                    ),
                ),
                (
                    "especificacao_do_bem",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="despesas.especificacaomaterialservico",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item de bem produzido",
                "verbose_name_plural": "Itens de bens produzidos",
            },
        ),
    ]
