# Generated by Django 4.2.20 on 2026-07-03 09:10

from django.db import migrations, models
import django.db.models.deletion
import sme_ptrf_apps.situacao_patrimonial.models.bem_produzido


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0445_alter_recurso_habilita_exibicao_de_lauda"),
        ("situacao_patrimonial", "0005_bemproduzidoitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="bemproduzido",
            name="recurso",
            field=models.ForeignKey(
                default=sme_ptrf_apps.situacao_patrimonial.models.bem_produzido.BemProduzido.get_recurso_padrao,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.recurso",
                verbose_name="Recurso",
            ),
        ),
    ]
