# Generated by Django 4.2.20 on 2025-04-16 12:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PeriodoPaa",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "alterado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Alterado em"),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "referencia",
                    models.CharField(
                        max_length=150, verbose_name="Referência do período"
                    ),
                ),
                (
                    "data_inicial",
                    models.DateField(verbose_name="Data de início do período"),
                ),
                (
                    "data_final",
                    models.DateField(verbose_name="Data de término do período"),
                ),
            ],
            options={
                "verbose_name": "Período PAA",
                "verbose_name_plural": "Períodos PAA",
            },
        ),
    ]
