# Generated by Django 4.2.20 on 2025-05-05 10:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("paa", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ParametroPaa",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "alterado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Alterado em"),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "mes_elaboracao_paa",
                    models.IntegerField(
                        choices=[
                            (1, "Janeiro"),
                            (2, "Fevereiro"),
                            (3, "Março"),
                            (4, "Abril"),
                            (5, "Maio"),
                            (6, "Junho"),
                            (7, "Julho"),
                            (8, "Agosto"),
                            (9, "Setembro"),
                            (10, "Outubro"),
                            (11, "Novembro"),
                            (12, "Dezembro"),
                        ],
                        help_text="indica o mês que pode ser iniciada a elaboração do PAA",
                        null=True,
                        verbose_name="Mês de elaboração do PAA",
                    ),
                ),
            ],
            options={
                "verbose_name": "Parâmetro do PAA",
                "verbose_name_plural": "Parâmetros do PAA",
            },
        ),
    ]
