# Generated by Django 4.2.20 on 2025-05-05 10:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0406_merge_20250408_0913"),
        ("paa", "0002_parametropaa"),
    ]

    operations = [
        migrations.CreateModel(
            name="Paa",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "alterado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Alterado em"),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "associacao",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.associacao",
                        verbose_name="Associação",
                    ),
                ),
                (
                    "periodo_paa",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="paa.periodopaa",
                        verbose_name="Período PAA",
                    ),
                ),
            ],
            options={
                "verbose_name": "PAA",
                "verbose_name_plural": "PAA`s",
                "unique_together": {("periodo_paa", "associacao")},
            },
        ),
    ]
