# Generated by Django 4.2.20 on 2025-05-21 10:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("paa", "0004_fonterecursopaa_recursopropriopaa_receitaprevistapaa_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReceitaPrevistaPdde",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "alterado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Alterado em"),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "previsao_valor_custeio",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        verbose_name="Previsão Valor Custeio",
                    ),
                ),
                (
                    "previsao_valor_capital",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        verbose_name="Previsão Valor Capital",
                    ),
                ),
                (
                    "previsao_valor_livre",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        verbose_name="Previsão Valor Livre Aplicação",
                    ),
                ),
                (
                    "saldo_custeio",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        verbose_name="Saldo Custeio",
                    ),
                ),
                (
                    "saldo_capital",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        verbose_name="Saldo Capital",
                    ),
                ),
                (
                    "saldo_livre",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        verbose_name="Saldo Livre Aplicação",
                    ),
                ),
                (
                    "acao_pdde",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="paa.acaopdde",
                        verbose_name="Ação PDDE",
                    ),
                ),
                (
                    "paa",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="paa.paa",
                        verbose_name="PAA",
                    ),
                ),
            ],
            options={
                "verbose_name": "Receita Prevista PDDE",
                "verbose_name_plural": "Receitas Previstas PDDE",
            },
        ),
    ]
