# Generated by Django 4.2.11 on 2025-06-06 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paa", "0005_receitaprevistapdde"),
    ]

    operations = [
        migrations.AddField(
            model_name="paa",
            name="saldo_congelado_em",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Saldo congelado em"
            ),
        ),
        migrations.AddField(
            model_name="receitaprevistapaa",
            name="saldo_congelado_capital",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=20,
                null=True,
                verbose_name="Saldo congelado Capital",
            ),
        ),
        migrations.AddField(
            model_name="receitaprevistapaa",
            name="saldo_congelado_custeio",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=20,
                null=True,
                verbose_name="Saldo congelado Custeio",
            ),
        ),
        migrations.AddField(
            model_name="receitaprevistapaa",
            name="saldo_congelado_livre",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=20,
                null=True,
                verbose_name="Saldo congelado Livre Aplicação",
            ),
        ),
    ]
