# Generated by Django 4.2.20 on 2025-06-16 10:22

from django.db import migrations


def carregar_dados(apps, schema_editor):
    fonte_recurso_model = apps.get_model('paa', 'FonteRecursoPaa')
    fontes  = [
        "Campanhas com Arrecadação",
        "Campanhas sem Arrecadação",
        "Convênios e Parcerias",
        "Doações",
        "Festas com Arrecadação",
        "Festas sem Arrecadação",
        "Juros",
        "Outras Fontes",
        "Reuniões Ordinárias"
        
    ]
    registros = [fonte_recurso_model(nome=fonte) for fonte in fontes]
    fonte_recurso_model.objects.bulk_create(registros)


class Migration(migrations.Migration):

    dependencies = [
        ("paa", "0006_paa_saldo_congelado_em_and_more"),
    ]

    operations = [
        migrations.RunPython(carregar_dados)
    ]
