# Generated by Django 4.2.20 on 2025-06-18 08:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0408_alter_categoriapdde_unique_together_and_more"),
        ("despesas", "0055_alter_tipodocumento_unique_together"),
        ("paa", "0007_insere_dados_fonte_recurso_paa"),
    ]

    operations = [
        migrations.CreateModel(
            name="PrioridadePaa",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "alterado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Alterado em"),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "prioridade",
                    models.BooleanField(
                        choices=[(1, "Sim"), (0, "Não")],
                        default=0,
                        verbose_name="Prioridade",
                    ),
                ),
                (
                    "recurso",
                    models.CharField(
                        choices=[
                            ("PTRF", "PTRF"),
                            ("PDDE", "PDDE"),
                            ("RECURSO_PROPRIO", "Recursos Próprios"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "tipo_aplicacao",
                    models.CharField(
                        blank=True,
                        choices=[("CUSTEIO", "Custeio"), ("CAPITAL", "Capital")],
                        default="CUSTEIO",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "valor_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(
                                0, message="Valor total não pode ser negativo."
                            )
                        ],
                    ),
                ),
                (
                    "acao_associacao",
                    models.ForeignKey(
                        blank=True,
                        help_text="Exibido quando o recurso é do tipo PTRF",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.acaoassociacao",
                    ),
                ),
                (
                    "acao_pdde",
                    models.ForeignKey(
                        blank=True,
                        help_text="Exibido quando o recurso é do tipo PDDE",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="paa.acaopdde",
                    ),
                ),
                (
                    "especificacao_material",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="despesas.especificacaomaterialservico",
                    ),
                ),
                (
                    "paa",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="paa.paa",
                        verbose_name="PAA",
                    ),
                ),
                (
                    "programa_pdde",
                    models.ForeignKey(
                        blank=True,
                        help_text="Exibido quando o recurso é do tipo PDDE",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="paa.programapdde",
                        verbose_name="Programa PDDE",
                    ),
                ),
                (
                    "tipo_despesa_custeio",
                    models.ForeignKey(
                        blank=True,
                        help_text="Exibido quando o tipo de aplicação é CUSTEIO",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="despesas.tipocusteio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prioridade do PAA",
                "verbose_name_plural": "Prioridades do PAA",
            },
        ),
    ]
