# Generated by Django 4.2.20 on 2025-08-06 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paa", "0008_prioridadepaa"),
    ]

    operations = [
        migrations.AddField(
            model_name="acaopdde",
            name="status",
            field=models.CharField(
                choices=[("ATIVA", "Ativa"), ("INATIVA", "Inativa")],
                default="ATIVA",
                max_length=15,
                verbose_name="status",
            ),
        ),
    ]
