# Generated by Django 4.2.20 on 2025-08-05 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("paa", "0008_prioridadepaa"),
    ]

    operations = [
        migrations.AddField(
            model_name="prioridadepaa",
            name="copia_de",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="paa.prioridadepaa",
            ),
        ),
    ]
