# Generated by Django 4.2.20 on 2025-08-05 17:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paa", "0009_prioridadepaa_copia_de"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prioridadepaa",
            name="valor_total",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=12,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        0, message="Valor total não pode ser negativo."
                    )
                ],
            ),
        ),
    ]
