# Generated by Django 4.2.20 on 2025-08-06 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paa", "0009_acaopdde_status"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="acaopdde",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="acaopdde",
            name="status",
            field=models.CharField(
                choices=[("ATIVA", "Ativa"), ("INATIVA", "Inativa")],
                default="ATIVA",
                max_length=7,
                verbose_name="status",
            ),
        ),
    ]
