# Generated by Django 4.2.20 on 2025-08-08 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("paa", "0010_alter_acaopdde_unique_together_alter_acaopdde_status"),
        ("paa", "0010_alter_prioridadepaa_valor_total"),
    ]

    operations = []
