# Generated by Django 4.2.20 on 2025-09-12 06:37

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("paa", "0011_merge_20250808_1138"),
    ]

    operations = [
        migrations.AddField(
            model_name="parametropaa",
            name="conclusao_do_paa_ue_1",
            field=ckeditor.fields.RichTextField(
                null=True, verbose_name="Conclusão do PAA 1"
            ),
        ),
        migrations.AddField(
            model_name="parametropaa",
            name="conclusao_do_paa_ue_2",
            field=ckeditor.fields.RichTextField(
                null=True, verbose_name="Conclusão do PAA 2"
            ),
        ),
        migrations.AddField(
            model_name="parametropaa",
            name="introducao_do_paa_ue_1",
            field=ckeditor.fields.RichTextField(
                null=True, verbose_name="Introdução do PAA 1"
            ),
        ),
        migrations.AddField(
            model_name="parametropaa",
            name="introducao_do_paa_ue_2",
            field=ckeditor.fields.RichTextField(
                null=True, verbose_name="Introdução do PAA 2"
            ),
        ),
        migrations.AddField(
            model_name="parametropaa",
            name="texto_pagina_paa_ue",
            field=ckeditor.fields.RichTextField(
                null=True, verbose_name="Texto da página de PAA (UE)"
            ),
        ),
    ]
