# Generated by Django 4.2.20 on 2025-09-19 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("paa", "0012_parametropaa_conclusao_do_paa_ue_1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="prioridadepaa",
            name="paa_importado",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="paa_importado",
                to="paa.paa",
                verbose_name="PAA Importado",
            ),
        ),
    ]
