# Generated by Django 4.2.20 on 2025-09-22 11:31

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("paa", "0012_parametropaa_conclusao_do_paa_ue_1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="paa",
            name="texto_introducao",
            field=ckeditor.fields.RichTextField(
                null=True, verbose_name="Texto introdução"
            ),
        ),
    ]
