# Generated by Django 4.2.20 on 2025-09-24 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("paa", "0013_paa_texto_introducao"),
        ("paa", "0013_prioridadepaa_paa_importado"),
    ]

    operations = []
