# Generated by Django 4.2.20 on 2025-10-02 15:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("paa", "0014_merge_20250924_1647"),
    ]

    operations = [
        migrations.CreateModel(
            name="ObjetivoPaa",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "alterado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Alterado em"),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "nome",
                    models.CharField(
                        max_length=160, unique=True, verbose_name="Objetivo"
                    ),
                ),
                (
                    "status",
                    models.BooleanField(choices=[(1, "Ativo"), (0, "Inativo")], default=1),
                ),
                (
                    "paa",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="paa.paa",
                        verbose_name="PAA",
                    ),
                ),
            ],
            options={
                "verbose_name": "Objetivo do PAA",
                "verbose_name_plural": "Objetivos do PAA",
            },
        ),
    ]
