# Generated by Django 4.2.20 on 2025-10-08 14:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("paa", "0015_objetivopaa"),
    ]

    operations = [
        migrations.CreateModel(
            name="AtividadeEstatutaria",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "alterado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Alterado em"),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "nome",
                    models.CharField(
                        max_length=160, verbose_name="Atividade Estatutária"
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ORDINARIA", "Reuniões Ordinárias"),
                            ("EXTRAORDINARIA", "Reuniões Extraordinárias"),
                        ],
                        default="ORDINARIA",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "mes",
                    models.IntegerField(
                        choices=[
                            (1, "Janeiro"),
                            (2, "Fevereiro"),
                            (3, "Março"),
                            (4, "Abril"),
                            (5, "Maio"),
                            (6, "Junho"),
                            (7, "Julho"),
                            (8, "Agosto"),
                            (9, "Setembro"),
                            (10, "Outubro"),
                            (11, "Novembro"),
                            (12, "Dezembro"),
                        ],
                        null=True,
                        verbose_name="Mês",
                    ),
                ),
                (
                    "status",
                    models.BooleanField(
                        choices=[(1, "Ativo"), (0, "Inativo")], default=1
                    ),
                ),
            ],
            options={
                "verbose_name": "Atividade Estatutária",
                "verbose_name_plural": "Atividades Estatutárias",
                "unique_together": {("nome", "mes", "tipo")},
            },
        ),
    ]
