# Generated by Django 4.2.20 on 2025-10-21 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paa", "0016_atividadeestatutaria"),
    ]

    operations = [
        migrations.AddField(
            model_name="paa",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NAO_INICIADO", "Não iniciado"),
                    ("EM_ELABORACAO", "Em elaboração"),
                    ("GERADO", "Gerado"),
                    ("EM_RETIFICACAO", "Em retificação"),
                ],
                default="EM_ELABORACAO",
                max_length=20,
                null=True,
            ),
        ),
    ]
