# Generated by Django 4.2.20 on 2025-10-28 13:13

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("paa", "0017_paa_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="paa",
            name="texto_conclusao",
            field=ckeditor.fields.RichTextField(
                null=True, verbose_name="Texto conclusão"
            ),
        ),
    ]
