# Generated by Django 4.2.20 on 2025-10-31 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paa", "0018_paa_texto_conclusao"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="receitaprevistapaa",
            constraint=models.UniqueConstraint(
                fields=("paa", "acao_associacao"),
                name="unique_receita_prevista_por_paa_acao",
            ),
        ),
    ]
