# Generated by Django 4.2.20 on 2025-11-10 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paa", "0019_receitaprevistapaa_unique_receita_prevista_por_paa_acao"),
    ]

    operations = [
        migrations.AddField(
            model_name="paa",
            name="objetivos",
            field=models.ManyToManyField(
                blank=True, related_name="paas", to="paa.objetivopaa"
            ),
        ),
    ]
