# Generated by Django 4.2.20 on 2025-11-13 06:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("mandatos", "0008_alter_cargocomposicao_substituido_and_more"),
        ("paa", "0020_paa_objetivos"),
    ]

    operations = [
        migrations.CreateModel(
            name="AtaPaa",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "alterado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Alterado em"),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "arquivo_pdf",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="",
                        verbose_name="Ata PAA em PDF",
                    ),
                ),
                (
                    "tipo_ata",
                    models.CharField(
                        choices=[("APRESENTACAO", "Apresentação")],
                        default="APRESENTACAO",
                        max_length=20,
                        verbose_name="tipo de ata",
                    ),
                ),
                (
                    "tipo_reuniao",
                    models.CharField(
                        choices=[
                            ("ORDINARIA", "Ordinária"),
                            ("EXTRAORDINARIA", "Extraordinária"),
                        ],
                        default="ORDINARIA",
                        max_length=20,
                        verbose_name="tipo de reunião",
                    ),
                ),
                (
                    "convocacao",
                    models.CharField(
                        choices=[
                            ("PRIMEIRA", "1ª convocação"),
                            ("SEGUNDA", "2ª convocação"),
                        ],
                        default="PRIMEIRA",
                        max_length=20,
                        verbose_name="convocação",
                    ),
                ),
                (
                    "status_geracao_pdf",
                    models.CharField(
                        choices=[
                            ("NAO_GERADO", "Não gerado"),
                            ("EM_PROCESSAMENTO", "Em processamento"),
                            ("CONCLUIDO", "Geração concluída"),
                        ],
                        default="NAO_GERADO",
                        max_length=20,
                        verbose_name="status Pdf",
                    ),
                ),
                (
                    "data_reuniao",
                    models.DateField(
                        blank=True, null=True, verbose_name="data da reunião"
                    ),
                ),
                (
                    "local_reuniao",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="local da reunião",
                    ),
                ),
                (
                    "comentarios",
                    models.TextField(
                        blank=True,
                        default="",
                        verbose_name="Manifestações, comentários e justificativas",
                    ),
                ),
                (
                    "parecer_conselho",
                    models.CharField(
                        choices=[("APROVADA", "Aprovada"), ("REJEITADA", "Rejeitada")],
                        default="APROVADA",
                        max_length=20,
                        verbose_name="parecer do conselho",
                    ),
                ),
                (
                    "preenchida_em",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Preenchida em"
                    ),
                ),
                (
                    "hora_reuniao",
                    models.TimeField(default="00:00", verbose_name="Hora da reunião"),
                ),
                (
                    "previa",
                    models.BooleanField(default=False, verbose_name="É prévia?"),
                ),
                (
                    "justificativa_repasses_pendentes",
                    models.TextField(
                        blank=True,
                        default="",
                        verbose_name="Justificativa repasses pendentes",
                    ),
                ),
                (
                    "pdf_gerado_previamente",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        help_text="O PDF já foi gerado e precisa ser regerado quando a ata é editada/apagada",
                        verbose_name="PDF gerado previamente",
                    ),
                ),
                (
                    "composicao",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="atas_paa_da_composicao",
                        to="mandatos.composicao",
                        verbose_name="Composição utilizada",
                    ),
                ),
                (
                    "paa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="atas_da_paa",
                        to="paa.paa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ata PAA",
                "verbose_name_plural": "Atas PAA",
            },
        ),
        migrations.CreateModel(
            name="ParticipanteAtaPaa",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "alterado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Alterado em"),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "identificacao",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=20,
                        verbose_name="Identificacão do presente (RF,CPF ou EOL)",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="Nome"
                    ),
                ),
                (
                    "cargo",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="Cargo"
                    ),
                ),
                ("membro", models.BooleanField(default=False, verbose_name="Membro ?")),
                (
                    "conselho_fiscal",
                    models.BooleanField(
                        default=False, verbose_name="Pertence ao conselho fiscal ?"
                    ),
                ),
                (
                    "presente",
                    models.BooleanField(default=True, verbose_name="Presente ?"),
                ),
                (
                    "ata_paa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="presentes_na_ata_paa",
                        to="paa.atapaa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Participantes ata PAA",
                "verbose_name_plural": "Participantes ata PAA",
            },
        ),
        migrations.AddField(
            model_name="atapaa",
            name="presidente_da_reuniao",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="presidente_participante_ata_paa",
                to="paa.participanteatapaa",
            ),
        ),
        migrations.AddField(
            model_name="atapaa",
            name="secretario_da_reuniao",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="secretario_participante_ata_paa",
                to="paa.participanteatapaa",
            ),
        ),
    ]
