# Generated by Django 4.2.20 on 2025-11-11 19:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("paa", "0021_atapaa_participanteatapaa_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="atividadeestatutaria",
            name="paa",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="paa.paa",
                verbose_name="PAA",
            ),
        ),
        migrations.CreateModel(
            name="AtividadeEstatutariaPaa",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "alterado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Alterado em"),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("data", models.DateField(verbose_name="Data da atividade")),
                (
                    "atividade_estatutaria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="paa.atividadeestatutaria",
                    ),
                ),
                (
                    "paa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="paa.paa",
                        verbose_name="PAA",
                    ),
                ),
            ],
            options={
                "verbose_name": "Atividade Estatutária PAA",
                "verbose_name_plural": "Atividades Estatutárias PAA",
            },
        ),
        migrations.AddField(
            model_name="paa",
            name="atividades_estatutarias",
            field=models.ManyToManyField(
                blank=True, related_name="paas",
                through="paa.AtividadeEstatutariaPaa",
                to="paa.atividadeestatutaria",
            ),
        ),
    ]
