# Generated by Django 4.2.20 on 2025-11-13 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paa", "0022_atividadeestatutaria_paa_atividadeestatutariapaa_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="participanteatapaa",
            name="professor_gremio",
            field=models.BooleanField(
                default=False, verbose_name="Professor do grêmio ?"
            ),
        ),
    ]
