# Generated by Django 4.2.20 on 2025-11-13 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("paa", "0021_atividadeestatutaria_paa_atividadeestatutariapaa_and_more"),
        ("paa", "0022_participanteatapaa_professor_gremio"),
    ]

    operations = []
