# Generated by Django 4.2.20 on 2025-11-14 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("paa", "0023_participanteatapaa_professor_gremio"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="atividadeestatutariapaa",
            unique_together={("atividade_estatutaria", "paa", "data")},
        ),
    ]
