# Generated by Django 4.2.20 on 2025-11-14 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paa", "0024_alter_atividadeestatutariapaa_unique_together"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="atapaa",
            name="justificativa_repasses_pendentes",
        ),
        migrations.AddField(
            model_name="atapaa",
            name="justificativa",
            field=models.TextField(
                blank=True, default="", verbose_name="Justificativa de rejeição"
            ),
        ),
    ]
