# Generated by Django 4.2.20 on 2025-11-18 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paa", "0025_remove_atapaa_justificativa_repasses_pendentes_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="atapaa",
            name="parecer_conselho",
            field=models.CharField(
                choices=[("APROVADA", "Aprovado"), ("REJEITADA", "Rejeitado")],
                default="APROVADA",
                max_length=20,
                verbose_name="parecer do conselho",
            ),
        ),
    ]
