# Generated by Django 4.2.20 on 2025-11-26 16:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("paa", "0026_alter_atapaa_parecer_conselho"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentoPaa",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "alterado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Alterado em"),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "arquivo_pdf",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="",
                        verbose_name="Documento em PDF",
                    ),
                ),
                (
                    "status_geracao",
                    models.CharField(
                        choices=[
                            ("NAO_GERADO", "Não gerado"),
                            ("EM_PROCESSAMENTO", "Em processamento"),
                            ("CONCLUIDO", "Geração concluída"),
                        ],
                        default="NAO_GERADO",
                        max_length=20,
                        verbose_name="Status geração",
                    ),
                ),
                (
                    "versao",
                    models.CharField(
                        choices=[("FINAL", "final"), ("PREVIA", "prévia")],
                        default="FINAL",
                        max_length=20,
                        verbose_name="Versão",
                    ),
                ),
                (
                    "paa",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="paa.paa",
                        verbose_name="PAA",
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento PAA",
                "verbose_name_plural": "Documento PAA",
            },
        ),
    ]
