# Generated by Django 4.2.20 on 2025-11-18 11:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("paa", "0026_alter_atapaa_parecer_conselho"),
    ]

    operations = [
        migrations.CreateModel(
            name="OutroRecurso",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=160, verbose_name="Nome")),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "alterado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Alterado em"),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "aceita_capital",
                    models.BooleanField(default=False, verbose_name="Aceita capital?"),
                ),
                (
                    "aceita_custeio",
                    models.BooleanField(default=False, verbose_name="Aceita custeio?"),
                ),
                (
                    "aceita_livre_aplicacao",
                    models.BooleanField(
                        default=False, verbose_name="Aceita livre aplicação?"
                    ),
                ),
            ],
            options={
                "verbose_name": "Outro Recurso",
                "verbose_name_plural": "Outros Recursos",
                "unique_together": {("nome",)},
            },
        ),
    ]
