# Generated by Django 4.2.20 on 2025-11-28 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("paa", "0027_documentopaa"),
        ("paa", "0027_outrorecurso"),
    ]

    operations = []
