# Generated by Django 4.2.20 on 2025-12-02 12:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0419_merge_20251031_1017"),
        ("paa", "0028_merge_0027_documentopaa_0027_outrorecurso"),
    ]

    operations = [
        migrations.CreateModel(
            name="OutroRescursoPeriodoPaa",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "alterado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Alterado em"),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("ativo", models.BooleanField(default=True)),
                (
                    "outro_recurso",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="paa.outrorecurso",
                        verbose_name="Outro Recurso",
                    ),
                ),
                (
                    "periodo_paa",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="paa.periodopaa",
                        verbose_name="Período PAA",
                    ),
                ),
                ("unidades", models.ManyToManyField(blank=True, to="core.unidade")),
            ],
            options={
                "verbose_name": "Outro Recurso PAA",
                "verbose_name_plural": "Outros Recursos PAA",
                "unique_together": {("outro_recurso", "periodo_paa")},
            },
        ),
    ]
