# Generated by Django 4.2.20 on 2025-12-02 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0419_merge_20251031_1017"),
        ("paa", "0029_outrorescursoperiodopaa"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="OutroRescursoPeriodoPaa",
            new_name="OutroRecursoPeriodoPaa",
        ),
    ]
