# Generated by Django 4.2.20 on 2025-12-22 12:22

from django.db import migrations, models
import sme_ptrf_apps.paa.models.outros_recursos


class Migration(migrations.Migration):

    dependencies = [
        ("paa", "0030_rename_outrorescursoperiodopaa_outrorecursoperiodopaa"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="periodopaa",
            options={
                "ordering": ("-data_inicial",),
                "verbose_name": "Período PAA",
                "verbose_name_plural": "Períodos PAA",
            },
        ),
        migrations.AddField(
            model_name="outrorecurso",
            name="cor",
            field=models.CharField(
                blank=True,
                default=sme_ptrf_apps.paa.models.outros_recursos.gerar_cor,
                max_length=10,
                null=True,
            ),
        ),
    ]
