# Generated by Django 4.2.20 on 2025-12-22 15:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("paa", "0031_alter_periodopaa_options_outrorecurso_cor"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReceitaPrevistaOutroRecursoPeriodo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "alterado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Alterado em"),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "saldo_congelado_custeio",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=20,
                        null=True,
                        verbose_name="Saldo congelado Custeio",
                    ),
                ),
                (
                    "saldo_congelado_capital",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=20,
                        null=True,
                        verbose_name="Saldo congelado Capital",
                    ),
                ),
                (
                    "saldo_congelado_livre",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=20,
                        null=True,
                        verbose_name="Saldo congelado Livre Aplicação",
                    ),
                ),
                (
                    "previsao_valor_custeio",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        verbose_name="Previsão Valor Custeio",
                    ),
                ),
                (
                    "previsao_valor_capital",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        verbose_name="Previsão Valor Capital",
                    ),
                ),
                (
                    "previsao_valor_livre",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        verbose_name="Previsão Valor Livre Aplicação",
                    ),
                ),
                (
                    "outro_recurso_periodo",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="paa.outrorecursoperiodopaa",
                        verbose_name="Outro Recurso Período",
                    ),
                ),
                (
                    "paa",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="paa.paa",
                        verbose_name="PAA",
                    ),
                ),
            ],
            options={
                "verbose_name": "Receita Prevista Outro Recurso Período",
                "verbose_name_plural": "Receitas Previstas Outros Recursos Períodos",
            },
        ),
        migrations.AddConstraint(
            model_name="receitaprevistaoutrorecursoperiodo",
            constraint=models.UniqueConstraint(
                fields=("paa", "outro_recurso_periodo"),
                name="unique_receita_prevista_por_outro_recurso_periodo",
            ),
        ),
    ]
