# Generated by Django 4.2.20 on 2025-12-22 15:46 0033_remove_receitaprevistaoutrorecursoperiodo_saldo_congelado_capital_and_more

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paa", "0032_receitaprevistaoutrorecursoperiodo_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="receitaprevistaoutrorecursoperiodo",
            name="saldo_congelado_capital",
        ),
        migrations.RemoveField(
            model_name="receitaprevistaoutrorecursoperiodo",
            name="saldo_congelado_custeio",
        ),
        migrations.RemoveField(
            model_name="receitaprevistaoutrorecursoperiodo",
            name="saldo_congelado_livre",
        ),
        migrations.AddField(
            model_name="receitaprevistaoutrorecursoperiodo",
            name="saldo_capital",
            field=models.DecimalField(
                decimal_places=2, max_digits=20, null=True, verbose_name="Saldo Capital"
            ),
        ),
        migrations.AddField(
            model_name="receitaprevistaoutrorecursoperiodo",
            name="saldo_custeio",
            field=models.DecimalField(
                decimal_places=2, max_digits=20, null=True, verbose_name="Saldo Custeio"
            ),
        ),
        migrations.AddField(
            model_name="receitaprevistaoutrorecursoperiodo",
            name="saldo_livre",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=20,
                null=True,
                verbose_name="Saldo Livre Aplicação",
            ),
        ),
    ]
