# Generated by Django 4.2.20 on 2026-01-07 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "paa",
            "0033_remove_receitaprevistaoutrorecursoperiodo_saldo_congelado_capital_and_more",
        ),
    ]

    operations = [      
        migrations.AlterModelOptions(
            name="receitaprevistaoutrorecursoperiodo",
            options={
                "ordering": ("outro_recurso_periodo__outro_recurso__nome",),
                "verbose_name": "Receita Prevista Outro Recurso Período",
                "verbose_name_plural": "Receitas Previstas Outros Recursos Períodos",
            },
        ),
        migrations.AddField(
            model_name="atividadeestatutaria",
            name="ordem",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
