# Generated by Django 4.2.20 on 2026-01-12 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("paa", "0034_alter_atividadeestatutaria_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="prioridadepaa",
            name="outro_recurso",
            field=models.ForeignKey(
                blank=True,
                help_text="Exibido quando o recurso é do tipo Outros Recursos",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="paa.outrorecurso",
            ),
        ),
        migrations.AlterField(
            model_name="prioridadepaa",
            name="recurso",
            field=models.CharField(
                choices=[
                    ("PTRF", "PTRF"),
                    ("PDDE", "PDDE"),
                    ("RECURSO_PROPRIO", "Recursos Próprios"),
                    ("OUTRO_RECURSO", "Outros Recursos"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
