# Generated by Django 4.2.20 on 2026-01-29 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("paa", "0035_prioridadepaa_outro_recurso_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prioridadepaa",
            name="acao_associacao",
            field=models.ForeignKey(
                blank=True,
                help_text="Exibido quando o recurso é do tipo PTRF",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="prioridade_paa_da_associacao",
                to="core.acaoassociacao",
            ),
        ),
        migrations.AlterField(
            model_name="receitaprevistapaa",
            name="acao_associacao",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="receita_prevista_paa_da_associacao",
                to="core.acaoassociacao",
                verbose_name="Ação de Associação",
            ),
        ),
    ]
