# Generated by Django 4.2.20 on 2026-01-30 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0421_parametros_tipos_unidades_professor_gremio"),
        ("paa", "0036_alter_prioridadepaa_acao_associacao_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="paa",
            name="acoes_conclusao",
            field=models.ManyToManyField(
                blank=True,
                help_text="Ações do tipo PTRF (core_acao) com exibir_paa=True disponíveis na conclusão do PAA",
                related_name="paas_conclusao",
                to="core.acao",
                verbose_name="Ações disponíveis na conclusão",
            ),
        ),
        migrations.AddField(
            model_name="paa",
            name="acoes_pdde_conclusao",
            field=models.ManyToManyField(
                blank=True,
                help_text="Ações PDDE (paa_acaopdde) com status ATIVA disponíveis na conclusão do PAA",
                related_name="paas_conclusao",
                to="paa.acaopdde",
                verbose_name="Ações PDDE disponíveis na conclusão",
            ),
        ),
        migrations.AddField(
            model_name="paa",
            name="outros_recursos_periodo_conclusao",
            field=models.ManyToManyField(
                blank=True,
                help_text="Outros Recursos (paa_outrorecurso) vinculados à unidade e período disponíveis na conclusão do PAA",
                related_name="paas_conclusao",
                to="paa.outrorecursoperiodopaa",
                verbose_name="Outros Recursos disponíveis na conclusão",
            ),
        ),
    ]
