# Generated by Django 4.2.20 on 2026-02-06 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paa", "0038_alter_paa_acoes_conclusao_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="atapaa",
            name="cargo_presidente_reuniao",
            field=models.CharField(
                blank=True,
                default="",
                max_length=200,
                verbose_name="cargo do presidente da reunião",
            ),
        ),
        migrations.AddField(
            model_name="atapaa",
            name="cargo_secretaria_reuniao",
            field=models.CharField(
                blank=True,
                default="",
                max_length=200,
                verbose_name="cargo da secretária da reunião",
            ),
        ),
        migrations.AddField(
            model_name="atapaa",
            name="presidente_reuniao",
            field=models.CharField(
                blank=True,
                default="",
                max_length=200,
                verbose_name="presidente da reunião",
            ),
        ),
        migrations.AddField(
            model_name="atapaa",
            name="secretario_reuniao",
            field=models.CharField(
                blank=True,
                default="",
                max_length=200,
                verbose_name="secretario da reunião",
            ),
        ),
    ]
