# Generated by Django 4.2.20 on 2026-02-10 09:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("paa", "0039_atapaa_cargo_presidente_reuniao_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModeloCarga",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "alterado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Alterado em"),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "tipo_carga",
                    models.CharField(
                        choices=[("MODELO_PLANO_ANUAL", "Modelo Plano Anual")],
                        default="MODELO_PLANO_ANUAL",
                        max_length=35,
                        unique=True,
                        verbose_name="tipo de carga",
                    ),
                ),
                ("arquivo", models.FileField(blank=True, null=True, upload_to="")),
            ],
            options={
                "verbose_name": "modelo de carga",
                "verbose_name_plural": "Modelos de carga",
            },
        ),
    ]
