# Generated by Django 4.2.20 on 2026-02-10 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("paa", "0040_modelocarga"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ModeloCarga",
            new_name="ModeloCargaPaa",
        ),
    ]
