# Generated by Django 4.2.20 on 2026-03-16 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paa", "0041_rename_modelocarga_modelocargapaa"),
    ]

    operations = [
        migrations.AlterField(
            model_name="objetivopaa",
            name="nome",
            field=models.CharField(max_length=160, verbose_name="Objetivo"),
        ),
    ]
