# Generated by Django 4.2.20 on 2026-03-18 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paa", "0042_alter_objetivopaa_nome"),
    ]

    operations = [
        migrations.AddField(
            model_name="atividadeestatutaria",
            name="ano",
            field=models.CharField(
                choices=[("VIGENTE", "Vigente"), ("POSTERIOR", "Posterior")],
                null=True,
                verbose_name="Ano",
            ),
        ),
    ]
