# Generated by Django 4.2.20 on 2026-03-19 15:29

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("paa", "0043_atividadeestatutaria_ano"),
    ]

    operations = [
        migrations.AddField(
            model_name="parametropaa",
            name="texto_atividades_previstas",
            field=ckeditor.fields.RichTextField(
                null=True, verbose_name="Texto das atividades previstas"
            ),
        ),
    ]
