# Generated by Django 4.2.20 on 2026-03-24 09:35

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("paa", "0044_parametropaa_texto_atividades_previstas"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parametropaa",
            name="conclusao_do_paa_ue_1",
            field=ckeditor.fields.RichTextField(
                blank=True, null=True, verbose_name="Conclusão do PAA 1"
            ),
        ),
        migrations.AlterField(
            model_name="parametropaa",
            name="conclusao_do_paa_ue_2",
            field=ckeditor.fields.RichTextField(
                blank=True, null=True, verbose_name="Conclusão do PAA 2"
            ),
        ),
        migrations.AlterField(
            model_name="parametropaa",
            name="introducao_do_paa_ue_1",
            field=ckeditor.fields.RichTextField(
                blank=True, null=True, verbose_name="Introdução do PAA 1"
            ),
        ),
        migrations.AlterField(
            model_name="parametropaa",
            name="introducao_do_paa_ue_2",
            field=ckeditor.fields.RichTextField(
                blank=True, null=True, verbose_name="Introdução do PAA 2"
            ),
        ),
        migrations.AlterField(
            model_name="parametropaa",
            name="texto_atividades_previstas",
            field=ckeditor.fields.RichTextField(
                blank=True, null=True, verbose_name="Texto das atividades previstas"
            ),
        ),
        migrations.AlterField(
            model_name="parametropaa",
            name="texto_pagina_paa_ue",
            field=ckeditor.fields.RichTextField(
                blank=True, null=True, verbose_name="Texto da página de PAA (UE)"
            ),
        ),
    ]
