# Generated by Django 4.2.20 on 2026-03-24 17:18

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("paa", "0045_alter_parametropaa_conclusao_do_paa_ue_1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="parametropaa",
            name="texto_levantamento_prioridades",
            field=ckeditor.fields.RichTextField(
                blank=True,
                null=True,
                verbose_name="Texto do levantamento de prioridades",
            ),
        ),
    ]
