# Generated by Django 4.2.20 on 2026-04-02 10:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("paa", "0046_parametropaa_texto_levantamento_prioridades"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentopaa",
            name="retificacao",
            field=models.BooleanField(
                default=False,
                help_text="Identifica se o documento é gerado por uma retificação",
                verbose_name="Retificação",
            ),
        ),
        migrations.AddField(
            model_name="documentopaa",
            name="versao_documento",
            field=models.IntegerField(default=1, verbose_name="Versão do documento"),
        ),
        migrations.AlterField(
            model_name="atapaa",
            name="tipo_ata",
            field=models.CharField(
                choices=[
                    ("APRESENTACAO", "Apresentação"),
                    ("RETIFICACAO", "Retificação"),
                ],
                default="APRESENTACAO",
                max_length=20,
                verbose_name="tipo de ata",
            ),
        ),
        migrations.CreateModel(
            name="ReplicaPaa",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "alterado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Alterado em"),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "historico",
                    models.JSONField(
                        help_text="Snapshot serializado do PAA no momento da retificação. Estrutura: {texto_introducao, texto_conclusao, objetivos, receitas_ptrf, receitas_pdde, receitas_outros_recursos, prioridades}",
                        verbose_name="Histórico do PAA",
                    ),
                ),
                (
                    "paa",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replica",
                        to="paa.paa",
                        verbose_name="PAA",
                    ),
                ),
            ],
            options={
                "verbose_name": "Réplica PAA",
                "verbose_name_plural": "Réplicas PAA",
            },
        ),
    ]
