# Generated by Django 4.2.20 on 2026-05-07 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "paa",
            "0047_add_versao_documento_retificacao_documento_paa_ata_retificacao_replica_paa",
        ),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="atividadeestatutaria",
            unique_together=set(),
        ),
    ]
