# Generated by Django 4.2.20 on 2026-05-22 10:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("paa", "0048_alter_atividadeestatutaria_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="LogReplicaPaa",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "alterado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Alterado em"),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "origem",
                    models.CharField(
                        choices=[
                            ("CANCELAMENTO", "Ao Cancelar Retificação"),
                            ("CONCLUSAO", "Ao Concluir Retificação"),
                        ],
                        default="CANCELAMENTO",
                        max_length=30,
                        verbose_name="origem",
                    ),
                ),
                (
                    "numero_versao_documento",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Número da versão do documento gerado",
                    ),
                ),
                (
                    "replica",
                    models.JSONField(
                        help_text="Snapshot serializado do PAA",
                        verbose_name="Log Réplica do PAA",
                    ),
                ),
                (
                    "paa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs_replica",
                        to="paa.paa",
                        verbose_name="PAA",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log da Réplica PAA",
                "verbose_name_plural": "Logs das Réplicas PAA",
            },
        ),
    ]
