# Generated by Django 4.2.20 on 2026-06-10 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paa", "0049_logreplicapaa"),
    ]

    operations = [
        migrations.AddField(
            model_name="atapaa",
            name="justificativa_retificacao",
            field=models.TextField(
                blank=True, default="", verbose_name="Justificativa de retificação"
            ),
        ),
    ]
