# Generated by Django 4.2.20 on 2026-06-30 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paa", "0050_atapaa_justificativa_retificacao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="atapaa",
            name="pdf_gerado_previamente",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="O PDF já foi gerado e precisa ser regerado quando a ata é editada/apagada",
                verbose_name="Documento gerado",
            ),
        ),
    ]
