# Generated by Django 4.2.20 on 2026-07-22 11:31

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("paa", "0051_alter_atapaa_pdf_gerado_previamente"),
    ]

    operations = [
        migrations.AddField(
            model_name="parametropaa",
            name="informe_bloqueio_prioridades",
            field=ckeditor.fields.RichTextField(
                blank=True,
                null=True,
                verbose_name="Informe de bloqueio de prioridades",
            ),
        ),
    ]
