# Generated by Django 4.2.20 on 2026-09-04 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paa", "0052_parametropaa_informe_bloqueio_prioridades"),
    ]

    operations = [
        migrations.AddField(
            model_name="atapaa",
            name="gerado_em",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Gerado em"),
        ),
        migrations.AddField(
            model_name="documentopaa",
            name="gerado_em",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Gerado em"),
        ),
    ]
