# Generated by Django 4.2.20 on 2026-09-10 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paa", "0053_atapaa_gerado_em_documentopaa_gerado_em"),
    ]

    operations = [
        migrations.AddField(
            model_name="prioridadepaa",
            name="descricao",
            field=models.TextField(blank=True, null=True, verbose_name="Descrição"),
        ),
    ]
