# Generated by Django 4.2.20 on 2026-09-28 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paa", "0054_prioridadepaa_descricao"),
    ]

    operations = [
        migrations.AddField(
            model_name="participanteatapaa",
            name="data_inicio_no_cargo",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data de início no cargo"
            ),
        ),
        migrations.AddField(
            model_name="participanteatapaa",
            name="vago",
            field=models.BooleanField(default=False, verbose_name="Vago ?"),
        ),
    ]
