# Generated by Django 2.2.10 on 2020-03-18 18:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_contaassociacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contaassociacao',
            options={'verbose_name': 'Conta de Associação', 'verbose_name_plural': 'Contas de Associações'},
        ),
        migrations.CreateModel(
            name='AcaoAssociacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alterado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('ATIVA', 'Ativa'), ('INATIVA', 'Inativa')], default='ATIVA', max_length=15, verbose_name='status')),
                ('acao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Acao')),
                ('associacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acoes', to='core.Associacao')),
            ],
            options={
                'verbose_name': 'Ação de Associação',
                'verbose_name_plural': 'Ações de Associações',
            },
        ),
    ]
