# Generated by Django 2.2.10 on 2020-04-08 12:37

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0005_auto_20200318_1504'),
    ]

    operations = [
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alterado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('data_inicio_realizacao_despesas', models.DateField(verbose_name='Inicio realização de despesas')),
                ('data_fim_realizacao_despesas', models.DateField(verbose_name='Fim realização de despesas')),
                ('data_prevista_repasse',
                 models.DateField(blank=True, null=True, verbose_name='Data prevista do repasse')),
                ('data_inicio_prestacao_contas',
                 models.DateField(blank=True, null=True, verbose_name='Início prestação de contas')),
                ('data_fim_prestacao_contas',
                 models.DateField(blank=True, null=True, verbose_name='Fim prestação de contas')),
            ],
            options={
                'verbose_name': 'Período',
                'verbose_name_plural': 'Períodos',
            },
        ),
    ]
