# Generated by Django 2.2.10 on 2020-04-13 16:27

from django.db import migrations, models
import django.db.models.deletion
import sme_ptrf_apps.core.models.validators


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_unidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='associacao',
            name='cnpj',
            field=models.CharField(blank=True, default='', max_length=20, unique=True, validators=[sme_ptrf_apps.core.models.validators.cnpj_validation], verbose_name='CNPJ'),
        ),
        migrations.AddField(
            model_name='associacao',
            name='presidente_associacao_nome',
            field=models.CharField(blank=True, default='', max_length=70, verbose_name='nome do presidente da associação'),
        ),
        migrations.AddField(
            model_name='associacao',
            name='presidente_associacao_rf',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='RF do presidente associação'),
        ),
        migrations.AddField(
            model_name='associacao',
            name='presidente_conselho_fiscal_nome',
            field=models.CharField(blank=True, default='', max_length=70, verbose_name='nome do presidente da associação'),
        ),
        migrations.AddField(
            model_name='associacao',
            name='presidente_conselho_fiscal_rf',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='RF do presidente associação'),
        ),
        migrations.AddField(
            model_name='associacao',
            name='unidade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='associacoes', to='core.Unidade'),
        ),
    ]
