# Generated by Django 2.2.10 on 2020-04-14 18:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200413_1327'),
    ]

    operations = [
        migrations.CreateModel(
            name='FechamentoPeriodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alterado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('total_receitas_capital', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Receitas (capital)')),
                ('total_repasses_capital', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Repasses (capital)')),
                ('total_despesas_capital', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Despesas (capital)')),
                ('saldo_reprogramado_capital', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Saldo Reprogramado (capital)')),
                ('total_receitas_custeio', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Receitas (custeio)')),
                ('total_repasses_custeio', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Repasses (custeio)')),
                ('total_despesas_custeio', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Despesas (custeio)')),
                ('saldo_reprogramado_custeio', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Saldo Reprogramado (custeio)')),
                ('status', models.CharField(choices=[('ABERTO', 'Completo'), ('FECHADO', 'Fechado')], default='ABERTO', max_length=15, verbose_name='status')),
                ('acao_associacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fechamentos_da_acao', to='core.AcaoAssociacao')),
                ('associacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fechamentos_associacao', to='core.Associacao')),
                ('conta_associacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fechamentos_da_conta', to='core.ContaAssociacao')),
                ('fechamento_anterior', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proximo_fechamento', to='core.FechamentoPeriodo')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fechamentos', to='core.Periodo')),
            ],
            options={
                'verbose_name': 'Fechamento de período',
                'verbose_name_plural': 'Fechamentos de períodos',
            },
        ),
    ]
