# Generated by Django 2.2.10 on 2020-04-14 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_fechamentoperiodo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fechamentoperiodo',
            name='fechamento_anterior',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proximo_fechamento', to='core.FechamentoPeriodo'),
        ),
    ]
