# Generated by Django 2.2.10 on 2020-04-18 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_periodo_periodo_anterior'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodo',
            name='data_fim_realizacao_despesas',
            field=models.DateField(blank=True, null=True, verbose_name='Fim realização de despesas'),
        ),
    ]
