# Generated by Django 2.2.10 on 2020-04-18 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200418_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodo',
            name='referencia',
            field=models.CharField(blank=True, default='', max_length=7, verbose_name='Referência'),
        ),
    ]
