# Generated by Django 2.2.10 on 2020-04-29 22:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_associacao_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associacao',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='associacoes', to=settings.AUTH_USER_MODEL),
        ),
    ]
