# Generated by Django 2.2.10 on 2020-05-04 12:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20200429_1939'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrestacaoConta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alterado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('ABERTO', 'Completo'), ('FECHADO', 'Fechado')], default='ABERTO', max_length=15, verbose_name='status')),
                ('conciliado', models.BooleanField(default=False, verbose_name='Período Conciliado?')),
                ('observacoes', models.TextField(blank=True, default='', verbose_name='observacoes')),
                ('associacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prestacoes_de_conta_da_associacao', to='core.Associacao')),
                ('conta_associacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prestacoes_de_conta_da_conta', to='core.ContaAssociacao')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestacoes_de_conta', to='core.Periodo')),
                ('prestacao_de_conta_anterior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proxima_prestacao_de_conta', to='core.PrestacaoConta')),
            ],
            options={
                'verbose_name': 'Prestação de conta',
                'verbose_name_plural': 'Prestações de conta',
            },
        ),
    ]
