# Generated by Django 2.2.10 on 2020-05-04 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20200504_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='fechamentoperiodo',
            name='prestacao_conta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fechamentos_da_prestacao', to='core.PrestacaoConta'),
        ),
    ]
