# Generated by Django 2.2.10 on 2020-05-05 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_fechamentoperiodo_prestacao_conta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prestacaoconta',
            options={'verbose_name': 'Prestação de conta', 'verbose_name_plural': 'Prestações de contas'},
        ),
        migrations.AddField(
            model_name='prestacaoconta',
            name='conciliado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última conciliação feita em'),
        ),
        migrations.AddField(
            model_name='prestacaoconta',
            name='motivo_reabertura',
            field=models.TextField(blank=True, default='', verbose_name='Motivo de reabrir a conciliação'),
        ),
    ]
