# Generated by Django 2.2.10 on 2020-05-09 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20200505_1400'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='prestacaoconta',
            unique_together={('conta_associacao', 'periodo')},
        ),
    ]
