# Generated by Django 2.2.10 on 2020-05-28 00:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20200509_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemonstrativoFinanceiro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alterado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
            options={
                'verbose_name': 'Demonstrativo Financeiro',
                'verbose_name_plural': 'Demonstrativos Financeiros',
            },
        ),
    ]
