# Generated by Django 2.2.10 on 2020-05-28 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_demonstrativofinanceiro'),
    ]

    operations = [
        migrations.AddField(
            model_name='demonstrativofinanceiro',
            name='acao_associacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='demonstrativo_financeiro', to='core.AcaoAssociacao'),
        ),
    ]
