# Generated by Django 2.2.10 on 2020-06-01 16:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_demonstrativofinanceiro_acao_associacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelacaoBens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alterado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('conta_associacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='relacoes_de_bens', to='core.ContaAssociacao')),
            ],
            options={
                'verbose_name': 'Relação de bens',
                'verbose_name_plural': 'Relações de bens',
            },
        ),
    ]
