# Generated by Django 2.2.10 on 2020-06-02 20:30

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_parametros'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alterado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('tipo_ata', models.CharField(choices=[('APRESENTACAO', 'Apresentação'), ('RETIFICACAO', 'Retificação')], default='APRESENTACAO', max_length=20, verbose_name='tipo de ata')),
                ('tipo_reuniao', models.CharField(choices=[('ORDINARIA', 'Ordinária'), ('EXTRAORDINARIA', 'Extraordinária')], default='ORDINARIA', max_length=20, verbose_name='tipo de reunião')),
                ('convocacao', models.CharField(choices=[('PRIMEIRA', '1ª convocação'), ('SEGUNDA', '2ª convocação')], default='PRIMEIRA', max_length=20, verbose_name='convocação')),
                ('local_reuniao', models.CharField(blank=True, default='', max_length=200, verbose_name='local da reunião')),
                ('presidente_reuniao', models.CharField(blank=True, default='', max_length=200, verbose_name='presidente da reunião')),
                ('cargo_presidente_reuniao', models.CharField(blank=True, default='', max_length=200, verbose_name='cargo do presidente da reunião')),
                ('secretario_reuniao', models.CharField(blank=True, default='', max_length=200, verbose_name='secretario da reunião')),
                ('comentarios', models.TextField(blank=True, default='', verbose_name='Manifestações, comentários e justificativas')),
                ('parecer_concelho', models.CharField(choices=[('APROVADA', 'Aprovada'), ('REJEITADA', 'Rejeitada'), ('RESSALVAS', 'Aprovada com ressalvas')], default='APROVADA', max_length=20, verbose_name='parecer do concelho')),
                ('associacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atas_da_associacao', to='core.Associacao')),
                ('conta_associacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atas_da_conta', to='core.ContaAssociacao')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.Periodo')),
                ('prestacao_conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atas_da_prestacao', to='core.PrestacaoConta')),
            ],
            options={
                'verbose_name': 'Fechamento de período',
                'verbose_name_plural': 'Fechamentos de períodos',
            },
        ),
    ]
