# Generated by Django 2.2.10 on 2020-06-02 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_parametros'),
        ('core', '0024_relacaobens'),
    ]

    operations = [
    ]
