# Generated by Django 2.2.10 on 2020-06-02 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_ata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ata',
            options={'verbose_name': 'Ata', 'verbose_name_plural': 'Atas'},
        ),
    ]
