# Generated by Django 2.2.10 on 2020-06-02 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_merge_20200602_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='relacaobens',
            name='prestacao_conta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relacoes_de_bens_da_prestacao', to='core.PrestacaoConta'),
        ),
    ]
