# Generated by Django 2.2.10 on 2020-06-02 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_relacaobens_prestacao_conta'),
    ]

    operations = [
        migrations.AddField(
            model_name='relacaobens',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
