# Generated by Django 2.2.10 on 2020-06-02 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20200602_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='ata',
            name='data_reuniao',
            field=models.DateField(blank=True, null=True, verbose_name='data da reunião'),
        ),
    ]
