# Generated by Django 2.2.10 on 2020-06-05 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_relacaobens_arquivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='associacao',
            name='usuario',
        ),
    ]
