# Generated by Django 2.2.10 on 2020-06-03 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_ata_data_reuniao'),
    ]

    operations = [
        migrations.AddField(
            model_name='ata',
            name='cargo_secretaria_reuniao',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='cargo da secretária da reunião'),
        ),
    ]
