# Generated by Django 2.2.10 on 2020-06-03 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_ata_cargo_secretaria_reuniao'),
    ]

    operations = [
        migrations.AddField(
            model_name='contaassociacao',
            name='agencia',
            field=models.CharField(blank=True, default='', max_length=15, verbose_name='Nº agência'),
        ),
        migrations.AddField(
            model_name='contaassociacao',
            name='banco_nome',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Nome do banco'),
        ),
        migrations.AddField(
            model_name='contaassociacao',
            name='numero_conta',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Nº conta'),
        ),
    ]
