# Generated by Django 2.2.10 on 2020-06-03 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20200603_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='contaassociacao',
            name='numero_cartao',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='Nº do cartão'),
        ),
    ]
