# Generated by Django 2.2.10 on 2020-06-04 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_contaassociacao_numero_cartao'),
    ]

    operations = [
        migrations.AddField(
            model_name='fechamentoperiodo',
            name='total_despesas_nao_conciliadas_capital',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Despesas não conciliadas (capital)'),
        ),
        migrations.AddField(
            model_name='fechamentoperiodo',
            name='total_despesas_nao_conciliadas_custeio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Despesas não conciliadas (custeio)'),
        ),
        migrations.AddField(
            model_name='fechamentoperiodo',
            name='total_receitas_nao_conciliadas_capital',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Receitas não conciliadas (capital)'),
        ),
        migrations.AddField(
            model_name='fechamentoperiodo',
            name='total_receitas_nao_conciliadas_custeio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Receitas não conciliadas (custeio)'),
        ),
    ]
