# Generated by Django 2.2.10 on 2020-06-05 16:48

import django.contrib.postgres.fields
from django.db import migrations, models

import sme_ptrf_apps.core.models.fechamento_periodo


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_fechamentoperiodo_especificacoes_despesas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fechamentoperiodo',
            name='especificacoes_despesas',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=sme_ptrf_apps.core.models.fechamento_periodo.get_especificacoes_despesas_default, size=None, verbose_name='especificações das despesas'),
        ),
    ]
