# Generated by Django 2.2.10 on 2020-06-05 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_remove_associacao_usuario'),
        ('core', '0034_auto_20200605_1348'),
    ]

    operations = [
    ]
