# Generated by Django 2.2.10 on 2020-06-08 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20200605_1221'),
        ('core', '0035_merge_20200605_1715'),
    ]

    operations = [
    ]
