# Generated by Django 2.2.10 on 2020-06-12 18:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_acao_posicao_nas_pesquisas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arquivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alterado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('identificador', models.SlugField(unique=True)),
                ('conteudo', models.FileField(blank=True, null=True, upload_to='')),
                ('tipo_carga', models.CharField(choices=[('REPASSE_REALIZADO', 'Repasse realizado')], default='REPASSE_REALIZADO', max_length=30, verbose_name='status')),
            ],
            options={
                'verbose_name': 'arquivo',
                'verbose_name_plural': 'arquivos',
            },
        ),
    ]
