# Generated by Django 2.2.10 on 2020-06-22 20:10

from django.db import migrations, models
import django.db.models.deletion
import sme_ptrf_apps.core.choices.membro_associacao
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_auto_20200612_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembroAssociacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alterado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nome', models.CharField(max_length=160, verbose_name='Nome')),
                ('cargo_associacao', models.CharField(blank=True, choices=[('Presidente da diretoria executiva', 'PRESIDENTE_DIRETORIA_EXECUTIVA'), ('Vice-Presidente da diretoria executiva', 'VICE_PRESIDENTE_DIRETORIA_EXECUTIVA'), ('Secretario', 'SECRETARIO'), ('Tesoureiro', 'TESOUREIRO'), ('Vogal 1', 'VOGAL_1'), ('Vogal 2', 'VOGAL_2'), ('Vogal 3', 'VOGAL_3'), ('Vogal 4', 'VOGAL_4'), ('Vogal 5', 'VOGAL_5'), ('Presidente do conselho fiscal', 'PRESIDENTE_CONSELHO_FISCAL'), ('Conselheiro 1', 'CONSELHEIRO_1'), ('Conselheiro 2', 'CONSELHEIRO_2'), ('Conselheiro 3', 'CONSELHEIRO_3'), ('Conselheiro 4', 'CONSELHEIRO_4')], default=sme_ptrf_apps.core.choices.membro_associacao.MembroEnum('Presidente da diretoria executiva'), max_length=45, null=True, verbose_name='Cargo Associação')),
                ('cargo_educacao', models.CharField(blank=True, default='', max_length=45, null=True, verbose_name='Cargo Educação')),
                ('representacao', models.CharField(choices=[('Servidor', 'SERVIDOR'), ('Pai_ou_responsável', 'PAI_RESPONSAVEL'), ('Estudante', 'ESTUDANTE')], default=sme_ptrf_apps.core.choices.membro_associacao.RepresentacaoCargo('Servidor'), max_length=25, verbose_name='Representação')),
                ('codigo_identificacao', models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='Código EOL ou RF')),
                ('associacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cargos', to='core.Associacao')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
