# Generated by Django 2.2.10 on 2020-06-19 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_auto_20200612_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='associacao',
            name='periodo_inicial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='associacoes_iniciadas_no_periodo', to='core.Periodo', verbose_name='período inicial'),
        ),
    ]
