# Generated by Django 2.2.10 on 2020-06-22 20:19

from django.db import migrations, models
import sme_ptrf_apps.core.choices.membro_associacao


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_membroassociacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membroassociacao',
            name='cargo_associacao',
            field=models.CharField(blank=True, choices=[('Presidente da diretoria executiva', 'PRESIDENTE_DIRETORIA_EXECUTIVA'), ('Vice-Presidente da diretoria executiva', 'VICE_PRESIDENTE_DIRETORIA_EXECUTIVA'), ('Secretario', 'SECRETARIO'), ('Tesoureiro', 'TESOUREIRO'), ('Vogal 1', 'VOGAL_1'), ('Vogal 2', 'VOGAL_2'), ('Vogal 3', 'VOGAL_3'), ('Vogal 4', 'VOGAL_4'), ('Vogal 5', 'VOGAL_5'), ('Presidente do conselho fiscal', 'PRESIDENTE_CONSELHO_FISCAL'), ('Conselheiro 1', 'CONSELHEIRO_1'), ('Conselheiro 2', 'CONSELHEIRO_2'), ('Conselheiro 3', 'CONSELHEIRO_3'), ('Conselheiro 4', 'CONSELHEIRO_4')], default=sme_ptrf_apps.core.choices.membro_associacao.MembroEnum('Presidente da diretoria executiva'), max_length=65, null=True, verbose_name='Cargo Associação'),
        ),
    ]
