# Generated by Django 2.2.10 on 2020-06-23 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_auto_20200622_2021'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membroassociacao',
            options={'verbose_name': 'Membro da Associação', 'verbose_name_plural': 'Membros das Associações'},
        ),
    ]
