# Generated by Django 2.2.10 on 2020-06-24 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_auto_20200623_1117'),
        ('core', '0041_associacao_periodo_inicial'),
    ]

    operations = [
    ]
