# Generated by Django 2.2.10 on 2020-07-08 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_remove_prestacaoconta_observacoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='ata',
            name='preenchida_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Preenchida em'),
        ),
    ]
