# Generated by Django 2.2.10 on 2020-07-08 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_remove_prestacaoconta_observacoes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arquivo',
            name='tipo_carga',
            field=models.CharField(choices=[('REPASSE_REALIZADO', 'Repasse realizado'), ('CARGA_PERIODO_INICIAL', 'Carga período inicial')], default='REPASSE_REALIZADO', max_length=35, verbose_name='status'),
        ),
    ]
