# Generated by Django 2.2.10 on 2020-07-09 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_ata_preenchida_em'),
        ('core', '0049_auto_20200708_1835'),
    ]

    operations = [
    ]
