# Generated by Django 2.2.10 on 2020-07-13 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_merge_20200709_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='fechamentoperiodo',
            name='saldo_reprogramado_livre',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Saldo Reprogramado (livre)'),
        ),
        migrations.AddField(
            model_name='fechamentoperiodo',
            name='total_receitas_livre',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Receitas (livre)'),
        ),
        migrations.AddField(
            model_name='fechamentoperiodo',
            name='total_receitas_nao_conciliadas_livre',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Receitas não conciliadas (livre)'),
        ),
        migrations.AddField(
            model_name='fechamentoperiodo',
            name='total_repasses_livre',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Repasses (livre)'),
        ),
    ]
