# Generated by Django 2.2.10 on 2020-07-17 16:21

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_auto_20200713_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametros',
            name='fique_de_olho',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
