# Generated by Django 2.2.10 on 2020-07-17 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_auto_20200713_1035'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arquivo',
            options={'verbose_name': 'arquivo de carga', 'verbose_name_plural': 'arquivos de carga'},
        ),
        migrations.AlterField(
            model_name='arquivo',
            name='tipo_carga',
            field=models.CharField(choices=[('REPASSE_REALIZADO', 'Repasses realizados'), ('CARGA_PERIODO_INICIAL', 'Carga período inicial'), ('REPASSE_PREVISTO', 'Repasses previstos')], default='REPASSE_REALIZADO', max_length=35, verbose_name='tipo de carga'),
        ),
    ]
