# Generated by Django 2.2.10 on 2020-07-20 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_auto_20200717_1556'),
        ('core', '0052_parametros_fique_de_olho'),
    ]

    operations = [
    ]
