# Generated by Django 2.2.10 on 2020-07-20 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_merge_20200720_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arquivo',
            name='tipo_carga',
            field=models.CharField(choices=[('REPASSE_REALIZADO', 'Repasses realizados'), ('CARGA_PERIODO_INICIAL', 'Carga período inicial'), ('REPASSE_PREVISTO', 'Repasses previstos'), ('CARGA_ASSOCIACOES', 'Carga de Associações')], default='REPASSE_REALIZADO', max_length=35, verbose_name='tipo de carga'),
        ),
    ]
