# Generated by Django 2.2.10 on 2020-07-23 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_auto_20200720_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='associacao',
            name='ccm',
            field=models.CharField(blank=True, default='', max_length=15, null=True, verbose_name='CCM'),
        ),
    ]
