# Generated by Django 2.2.10 on 2020-07-23 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_associacao_ccm'),
    ]

    operations = [
        migrations.AddField(
            model_name='associacao',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, null=True, verbose_name='E-mail'),
        ),
    ]
