# Generated by Django 2.2.10 on 2020-07-27 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='fechamentoperiodo',
            name='total_receitas_devolucao_capital',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Receitas Devolução (capital)'),
        ),
        migrations.AddField(
            model_name='fechamentoperiodo',
            name='total_receitas_devolucao_custeio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Receitas Devolução (custeio)'),
        ),
        migrations.AddField(
            model_name='fechamentoperiodo',
            name='total_receitas_devolucao_livre',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Receitas Devolução (livre)'),
        ),
    ]
