# Generated by Django 2.2.10 on 2020-07-29 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_auto_20200727_0219'),
    ]

    operations = [
        migrations.AddField(
            model_name='associacao',
            name='status_regularidade',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('REGULAR', 'Regular')], default='PENDENTE', max_length=15, verbose_name='Status de Regularidade'),
        ),
    ]
