# Generated by Django 2.2.10 on 2020-07-30 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_auto_20200730_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidade',
            name='cep',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='unidade',
            name='telefone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Telefone'),
        ),
    ]
