# Generated by Django 2.2.10 on 2020-07-30 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_auto_20200730_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='associacao',
            name='presidente_associacao_nome',
        ),
        migrations.RemoveField(
            model_name='associacao',
            name='presidente_associacao_rf',
        ),
        migrations.RemoveField(
            model_name='associacao',
            name='presidente_conselho_fiscal_nome',
        ),
        migrations.RemoveField(
            model_name='associacao',
            name='presidente_conselho_fiscal_rf',
        ),
    ]
