# Generated by Django 2.2.10 on 2020-07-30 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_auto_20200730_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidade',
            name='diretor_nome',
            field=models.CharField(blank=True, default='', max_length=160, verbose_name='Nome do diretor da unidade'),
        ),
    ]
