# Generated by Django 2.2.10 on 2020-08-06 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_parametros_tempo_notificar_nao_demonstrados'),
    ]

    operations = [
        migrations.AddField(
            model_name='associacao',
            name='processo_regularidade',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Nº processo regularidade'),
        ),
    ]
