# Generated by Django 2.2.10 on 2020-08-06 11:42

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_associacao_processo_regularidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessoAssociacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alterado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('numero_processo', models.CharField(blank=True, default='', max_length=100, verbose_name='Nº processo prestação de conta')),
                ('ano', models.CharField(blank=True, default='', max_length=4, verbose_name='Ano')),
                ('associacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='processos', to='core.Associacao')),
            ],
            options={
                'verbose_name': 'Processo de prestação de contas',
                'verbose_name_plural': 'Processos de prestação de contas',
            },
        ),
    ]
