# Generated by Django 2.2.10 on 2020-08-07 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_processoassociacao'),
        ('core', '0067_auto_20200805_1922'),
    ]

    operations = [
    ]
