# Generated by Django 2.2.10 on 2020-08-08 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_unidade_dre_cnpj'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidade',
            name='dre_diretor_regional_rf',
            field=models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='RF do diretor regional '),
        ),
    ]
