# Generated by Django 2.2.10 on 2020-08-08 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_unidade_dre_diretor_regional_rf'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidade',
            name='dre_diretor_regional_nome',
            field=models.CharField(blank=True, default='', max_length=160, verbose_name='Nome do diretor regional'),
        ),
    ]
