# Generated by Django 2.2.10 on 2020-08-08 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_unidade_dre_designacao_portaria'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidade',
            name='dre_designacao_ano',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Designação ano'),
        ),
    ]
