# Generated by Django 2.2.10 on 2020-08-31 09:04

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_unidade_dre_designacao_ano'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObservacaoConciliacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alterado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('texto', models.TextField(blank=True, max_length=600, null=True, verbose_name='Texto')),
                ('acao_associacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='observacoes_conciliacao_da_acao', to='core.AcaoAssociacao')),
                ('associacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='observacoes_conciliacao_da_associacao', to='core.Associacao')),
                ('conta_associacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='observacoes_conciliacao_da_conta', to='core.ContaAssociacao')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='observacoes_conciliacao_do_periodo', to='core.Periodo')),
            ],
            options={
                'verbose_name': 'observação de conciliação',
                'verbose_name_plural': 'observações de conciliação',
            },
        ),
    ]
