# Generated by Django 2.2.10 on 2020-09-01 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_observacaoconciliacao'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Observacao',
        ),
    ]
