# Generated by Django 2.2.10 on 2020-09-02 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0079_auto_20200902_1017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestacaoconta',
            name='prestacao_de_conta_anterior',
        ),
    ]
