# Generated by Django 2.2.10 on 2020-09-02 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0080_remove_prestacaoconta_prestacao_de_conta_anterior'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='prestacaoconta',
            unique_together={('associacao', 'periodo')},
        ),
    ]
