# Generated by Django 2.2.10 on 2020-09-04 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0085_notificacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacao',
            name='ativo',
            field=models.BooleanField(default=False, verbose_name='Foi Lido?'),
        ),
    ]
