# Generated by Django 2.2.10 on 2020-09-04 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0086_notificacao_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacao',
            name='descricao',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Descrição'),
        ),
    ]
