# Generated by Django 2.2.10 on 2020-09-08 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0087_notificacao_descricao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificacao',
            old_name='ativo',
            new_name='lido',
        ),
    ]
