# Generated by Django 2.2.10 on 2020-09-09 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0082_auto_20200908_1152'),
        ('core', '0088_auto_20200908_1214'),
    ]

    operations = [
    ]
