# Generated by Django 2.2.10 on 2020-09-17 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0090_notificacao_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ata',
            name='conta_associacao',
        ),
    ]
