# Generated by Django 2.2.10 on 2020-09-21 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0092_auto_20200918_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestacaoconta',
            name='data_recebimento',
            field=models.DateField(blank=True, null=True, verbose_name='data de recebimento pela DRE'),
        ),
        migrations.AddField(
            model_name='prestacaoconta',
            name='data_ultima_analise',
            field=models.DateField(blank=True, null=True, verbose_name='data da última análise pela DRE'),
        ),
        migrations.AddField(
            model_name='prestacaoconta',
            name='devolucao_tesouro',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='há devolução ao tesouro'),
        ),
    ]
