# Generated by Django 2.2.10 on 2020-09-24 11:13

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0094_auto_20200922_1356'),
    ]

    operations = [
        migrations.CreateModel(
            name='CobrancaPrestacaoConta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alterado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('data', models.DateField(verbose_name='data da cobrança')),
                ('tipo', models.CharField(choices=[('RECEBIMENTO', 'Cobrança de recebimento'), ('DEVOLUCAO', 'Cobrança de devolução')], default='RECEBIMENTO', max_length=15, verbose_name='tipo de cobrança')),
                ('prestacao_conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cobrancas_da_prestacao', to='core.PrestacaoConta')),
            ],
            options={
                'verbose_name': 'Cobrança de prestação de contas',
                'verbose_name_plural': 'Cobranças de prestações de contas',
            },
        ),
    ]
