# Generated by Django 2.2.10 on 2020-09-29 11:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0095_cobrancaprestacaoconta'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevolucaoPrestacaoConta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alterado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('data', models.DateField(verbose_name='data da devolução')),
                ('data_limite_ue', models.DateField(verbose_name='data limite para a ue')),
                ('prestacao_conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devolucoes_da_prestacao', to='core.PrestacaoConta')),
            ],
            options={
                'verbose_name': 'Devolução de prestação de contas',
                'verbose_name_plural': 'Devoluções de prestações de contas',
            },
        ),
    ]
