# Generated by Django 2.2.10 on 2020-09-29 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0095_cobrancaprestacaoconta'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoconta',
            name='agencia',
            field=models.CharField(blank=True, default='', max_length=15, verbose_name='Nº agência'),
        ),
        migrations.AddField(
            model_name='tipoconta',
            name='banco_nome',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Nome do banco'),
        ),
        migrations.AddField(
            model_name='tipoconta',
            name='numero_cartao',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='Nº do cartão'),
        ),
        migrations.AddField(
            model_name='tipoconta',
            name='numero_conta',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Nº conta'),
        ),
    ]
