# Generated by Django 2.2.10 on 2020-09-29 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0096_devolucaoprestacaoconta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acao',
            options={'verbose_name': 'Ação', 'verbose_name_plural': '03.0) Ações'},
        ),
        migrations.AlterModelOptions(
            name='acaoassociacao',
            options={'verbose_name': 'Ação de Associação', 'verbose_name_plural': '07.2) Ações de Associações'},
        ),
        migrations.AlterModelOptions(
            name='arquivo',
            options={'verbose_name': 'arquivo de carga', 'verbose_name_plural': '02.0) Arquivos de carga'},
        ),
        migrations.AlterModelOptions(
            name='associacao',
            options={'verbose_name': 'Associação', 'verbose_name_plural': '07.0) Associações'},
        ),
        migrations.AlterModelOptions(
            name='ata',
            options={'verbose_name': 'Ata', 'verbose_name_plural': '09.4) Atas'},
        ),
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name': 'Categoria', 'verbose_name_plural': '05.3) Categorias de notificação'},
        ),
        migrations.AlterModelOptions(
            name='cobrancaprestacaoconta',
            options={'verbose_name': 'Cobrança de prestação de contas', 'verbose_name_plural': '09.6) Cobranças de prestações de contas'},
        ),
        migrations.AlterModelOptions(
            name='contaassociacao',
            options={'verbose_name': 'Conta de Associação', 'verbose_name_plural': '07.1) Contas de Associações'},
        ),
        migrations.AlterModelOptions(
            name='demonstrativofinanceiro',
            options={'verbose_name': 'Demonstrativo Financeiro', 'verbose_name_plural': '09.2) Demonstrativos Financeiros'},
        ),
        migrations.AlterModelOptions(
            name='devolucaoprestacaoconta',
            options={'verbose_name': 'Devolução de prestação de contas', 'verbose_name_plural': '09.7) Devoluções de prestações de contas'},
        ),
        migrations.AlterModelOptions(
            name='fechamentoperiodo',
            options={'verbose_name': 'Fechamento de período', 'verbose_name_plural': '09.1) Fechamentos de períodos'},
        ),
        migrations.AlterModelOptions(
            name='membroassociacao',
            options={'verbose_name': 'Membro da Associação', 'verbose_name_plural': '07.3) Membros das Associações'},
        ),
        migrations.AlterModelOptions(
            name='notificacao',
            options={'verbose_name': 'Notificação', 'verbose_name_plural': '05.0) Notificações'},
        ),
        migrations.AlterModelOptions(
            name='observacaoconciliacao',
            options={'verbose_name': 'observação de conciliação', 'verbose_name_plural': '09.5) Observações de conciliação'},
        ),
        migrations.AlterModelOptions(
            name='parametros',
            options={'verbose_name': 'Parâmetro', 'verbose_name_plural': '01.0) Parâmetros'},
        ),
        migrations.AlterModelOptions(
            name='periodo',
            options={'verbose_name': 'Período', 'verbose_name_plural': '08.0) Períodos'},
        ),
        migrations.AlterModelOptions(
            name='prestacaoconta',
            options={'verbose_name': 'Prestação de conta', 'verbose_name_plural': '09.0) Prestações de contas'},
        ),
        migrations.AlterModelOptions(
            name='processoassociacao',
            options={'verbose_name': 'Processo de prestação de contas', 'verbose_name_plural': '07.1) Processos de prestação de contas'},
        ),
        migrations.AlterModelOptions(
            name='relacaobens',
            options={'verbose_name': 'Relação de bens', 'verbose_name_plural': '09.3) Relações de bens'},
        ),
        migrations.AlterModelOptions(
            name='remetente',
            options={'verbose_name': 'Remetente', 'verbose_name_plural': '05.2) Remetentes de notificações'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Tag', 'verbose_name_plural': '10.0) Tags'},
        ),
        migrations.AlterModelOptions(
            name='tipoconta',
            options={'verbose_name': 'Tipo de conta', 'verbose_name_plural': '04.0) Tipos de conta'},
        ),
        migrations.AlterModelOptions(
            name='tiponotificacao',
            options={'verbose_name': 'Tipo de notificação', 'verbose_name_plural': '05.1) Tipos de notificação'},
        ),
        migrations.AlterModelOptions(
            name='unidade',
            options={'verbose_name': 'Unidade', 'verbose_name_plural': '06.0) Unidades'},
        ),
        migrations.AddField(
            model_name='cobrancaprestacaoconta',
            name='devolucao_prestacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cobrancas_da_devolucao', to='core.DevolucaoPrestacaoConta'),
        ),
    ]
