# Generated by Django 2.2.10 on 2020-09-30 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0096_auto_20200929_2004'),
        ('core', '0097_auto_20200929_1419'),
    ]

    operations = [
    ]
