# Generated by Django 2.2.10 on 2020-10-14 07:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0032_rateiodespesa_update_conferido'),
        ('core', '0102_tipodevolucaoaotesouro'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevolucaoAoTesouro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alterado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('data', models.DateField(verbose_name='data da devolução ao tesouro')),
                ('devolucao_total', models.BooleanField(default=True, verbose_name='Devolução total?')),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Valor')),
                ('motivo', models.TextField(blank=True, max_length=600, null=True, verbose_name='Motivo')),
                ('despesa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='devolucoes_ao_tesouro_da_despesa', to='despesas.Despesa')),
                ('prestacao_conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devolucoes_ao_tesouro_da_prestacao', to='core.PrestacaoConta')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devolucoes_ao_tesouro_do_tipo', to='core.TipoDevolucaoAoTesouro')),
            ],
            options={
                'verbose_name': 'Devolução ao tesouro prestação de contas',
                'verbose_name_plural': '09.9) Devoluções ao tesouro prestações de contas',
            },
        ),
    ]
