# Generated by Django 2.2.10 on 2020-10-15 15:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0103_devolucaoaotesouro'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComentarioAnalisePrestacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alterado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('ordem', models.PositiveSmallIntegerField(verbose_name='ordem')),
                ('comentario', models.TextField(blank=True, max_length=600, null=True, verbose_name='Comentário')),
                ('prestacao_conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_de_analise_da_prestacao', to='core.PrestacaoConta')),
            ],
            options={
                'verbose_name': 'Observação de análise de prestação de contas',
                'verbose_name_plural': '09.9) Observações de análise de prestações de contas',
            },
        ),
    ]
