# Generated by Django 2.2.10 on 2020-10-21 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0104_comentarioanaliseprestacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='ata',
            name='retificacoes',
            field=models.TextField(blank=True, default='', verbose_name='Retificações'),
        ),
    ]
