# Generated by Django 2.2.10 on 2020-10-26 13:23

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0105_ata_retificacoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametros',
            name='fique_de_olho_relatorio_dre',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Fique de olho (Relatório DRE)'),
        ),
    ]
