# Generated by Django 2.2.10 on 2020-10-29 09:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0106_parametros_fique_de_olho_relatorio_dre'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrevisaoRepasseSme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alterado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor')),
                ('associacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='previsoes_de_repasse_sme_para_a_associacao', to='core.Associacao')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='previsoes_repasse_sme', to='core.Periodo')),
            ],
            options={
                'verbose_name': 'Previsão repasse SME',
                'verbose_name_plural': '12.0) Previsões de repasse',
                'unique_together': {('associacao', 'periodo')},
            },
        ),
    ]
