# Generated by Django 2.2.10 on 2020-10-28 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0106_parametros_fique_de_olho_relatorio_dre'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoconta',
            name='apenas_leitura',
            field=models.BooleanField(default=False, verbose_name='Apenas Leitura?'),
        ),
    ]
