# Generated by Django 2.2.10 on 2020-10-30 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0107_previsaorepassesme'),
        ('core', '0107_tipoconta_apenas_leitura'),
    ]

    operations = [
    ]
