# Generated by Django 2.2.10 on 2020-11-05 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0109_auto_20201030_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='arquivo',
            name='tipo_delimitador',
            field=models.CharField(choices=[('DELIMITADOR_PONTO_VIRGULA', 'Delimitador ponto e vírgula'), ('DELIMITADOR_VIRGULA', 'Delimitador vírgula')], default='DELIMITADOR_VIRGULA', max_length=35, verbose_name='tipo delimitador'),
        ),
    ]
