# Generated by Django 2.2.10 on 2020-11-06 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0110_arquivo_tipo_delimitador'),
    ]

    operations = [
        migrations.AddField(
            model_name='arquivo',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('SUCESSO', 'Sucesso'), ('ERRO', 'Erro'), ('PROCESSADO_COM_ERRO', 'Processado com erro')], default='PENDENTE', max_length=35, verbose_name='status'),
        ),
    ]
