# Generated by Django 2.2.10 on 2020-11-06 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0111_arquivo_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='arquivo',
            name='log',
            field=models.TextField(blank=True, null=True),
        ),
    ]
