# Generated by Django 2.2.10 on 2020-11-06 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0112_arquivo_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='arquivo',
            name='ultima_execucao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ultima execução'),
        ),
    ]
