# Generated by Django 2.2.10 on 2020-11-18 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0114_auto_20201113_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='devolucaoaotesouro',
            name='visao_criacao',
            field=models.CharField(choices=[('DRE', 'Diretoria Regional'), ('UE', 'Unidade Escolar')], default='DRE', max_length=20, verbose_name='Criado pela'),
        ),
    ]
