# Generated by Django 2.2.10 on 2020-11-25 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0116_auto_20201124_1017'),
        ('core', '0117_auto_20201125_0110'),
    ]

    operations = [
    ]
