# Generated by Django 2.2.10 on 2020-11-25 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0118_merge_20201125_1108'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='censo',
            options={'verbose_name': 'Censo', 'verbose_name_plural': '13.0) Censos'},
        ),
    ]
