# Generated by Django 2.2.10 on 2020-11-27 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0121_membroassociacao_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membroassociacao',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='membro', to=settings.AUTH_USER_MODEL),
        ),
    ]
