# Generated by Django 2.2.10 on 2020-11-30 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0122_auto_20201127_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='membroassociacao',
            name='cpf',
            field=models.CharField(blank=True, default='', max_length=14, null=True, verbose_name='CPF Responsável'),
        ),
    ]
