# Generated by Django 2.2.10 on 2020-12-10 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0124_auto_20201202_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='acao',
            name='e_recursos_proprios',
            field=models.BooleanField(default=False, verbose_name='Aceita recursos próprios?'),
        ),
    ]
