# Generated by Django 2.2.10 on 2020-12-29 07:45

import ckeditor.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0125_acao_e_recursos_proprios'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametroFiqueDeOlhoPc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alterado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('fique_de_olho', ckeditor.fields.RichTextField(null=True, verbose_name='Texto do fique de olho')),
            ],
            options={
                'verbose_name': 'Fique de olho (Prestação de Contas)',
                'verbose_name_plural': 'Fique de olho (Prestação de Contas)',
            },
        ),
    ]
