# Generated by Django 2.2.10 on 2020-12-29 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0126_parametrofiquedeolhopc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parametrofiquedeolhopc',
            options={'verbose_name': 'Fique de olho (Prestação de Contas)', 'verbose_name_plural': '01.1) Fique de olho (Prestação de Contas)'},
        ),
    ]
