# Generated by Django 2.2.10 on 2020-12-29 11:05

from django.db import migrations


def migrate_data(apps, schema_editor):
    model_parametros = apps.get_model('core', 'Parametros')
    model_parametro_fique_de_olho_pc = apps.get_model('core', 'ParametroFiqueDeOlhoPc')
    fique_de_olho_texto = model_parametros.objects.get().fique_de_olho
    model_parametro_fique_de_olho_pc.objects.create(fique_de_olho=fique_de_olho_texto)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0127_auto_20201229_1017'),
    ]

    operations = [
        # migrations.RunPython(migrate_data, reverse_code=migrations.RunPython.noop)
    ]
