# Generated by Django 2.2.10 on 2021-01-05 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0128_migra_texto_fique_de_olho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devolucaoaotesouro',
            name='data',
            field=models.DateField(blank=True, null=True, verbose_name='data da devolução ao tesouro'),
        ),
    ]
