# Generated by Django 2.2.10 on 2021-01-05 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0129_auto_20210105_0258'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestacaoconta',
            name='motivos_reprovacao',
            field=models.TextField(blank=True, default='', verbose_name='Motivos para reprovação pela DRE'),
        ),
    ]
