# Generated by Django 2.2.10 on 2021-01-11 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0132_prestacaoconta_motivo_aprovacao_ressalva'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestacaoconta',
            name='ressalvas_aprovacao',
        ),
    ]
