# Generated by Django 2.2.10 on 2021-01-12 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0133_remove_prestacaoconta_ressalvas_aprovacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membroassociacao',
            name='usuario',
        ),
    ]
