# Generated by Django 2.2.10 on 2021-01-13 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0135_auto_20210113_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestacaoconta',
            name='motivos_aprovacao_ressalva',
            field=models.ManyToManyField(blank=True, to='dre.MotivoAprovacaoRessalva'),
        ),
    ]
