# Generated by Django 2.2.10 on 2021-01-14 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0135_associacao_motivo_nao_regularidade'),
        ('core', '0136_auto_20210113_1107'),
    ]

    operations = [
    ]
