# Generated by Django 2.2.10 on 2021-01-21 00:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0137_merge_20210114_0757'),
    ]

    operations = [
        migrations.AddField(
            model_name='arquivo',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='arquivos', to=settings.AUTH_USER_MODEL),
        ),
    ]
