# Generated by Django 2.2.10 on 2021-01-27 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0138_auto_20210126_0735'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='acao',
            unique_together={('nome',)},
        ),
    ]
