# Generated by Django 2.2.10 on 2021-02-03 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0139_auto_20210127_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='membroassociacao',
            name='bairro',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='membroassociacao',
            name='cep',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='membroassociacao',
            name='endereco',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='membroassociacao',
            name='telefone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Telefone'),
        ),
    ]
