# Generated by Django 2.2.10 on 2021-02-08 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0141_merge_20210204_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arquivo',
            name='usuario',
        ),
    ]
