# Generated by Django 2.2.10 on 2021-02-09 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0141_auto_20210204_0854'),
        ('core', '0142_remove_arquivo_usuario'),
    ]

    operations = [
    ]
