# Generated by Django 2.2.10 on 2021-02-09 13:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0143_merge_20210209_1140'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloCarga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alterado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('tipo_carga', models.CharField(choices=[('REPASSE_REALIZADO', 'Repasses realizados'), ('CARGA_PERIODO_INICIAL', 'Carga período inicial'), ('REPASSE_PREVISTO', 'Repasses previstos'), ('CARGA_ASSOCIACOES', 'Carga de Associações'), ('CARGA_USUARIOS', 'Carga de usuários'), ('CARGA_CENSO', 'Carga de censo'), ('CARGA_REPASSE_PREVISTO_SME', 'Repasses previstos sme')], default='CARGA_ASSOCIACOES', max_length=35, verbose_name='tipo de carga')),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='')),
            ],
            options={
                'verbose_name': 'modelo de carga',
                'verbose_name_plural': '02.1) Modelos de carga',
            },
        ),
    ]
