# Generated by Django 2.2.10 on 2021-02-12 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0145_auto_20210209_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arquivo',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('SUCESSO', 'Sucesso'), ('ERRO', 'Erro'), ('PROCESSADO_COM_ERRO', 'Processado com erro'), ('PROCESSANDO', 'Processando...')], default='PENDENTE', max_length=35, verbose_name='status'),
        ),
    ]
