# Generated by Django 2.2.10 on 2021-02-19 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0146_auto_20210212_0710'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='observacaoconciliacao',
            options={'verbose_name': 'informação de conciliação', 'verbose_name_plural': '09.5) Informações de conciliação'},
        ),
        migrations.RemoveField(
            model_name='observacaoconciliacao',
            name='acao_associacao',
        ),
        migrations.AddField(
            model_name='observacaoconciliacao',
            name='data_extrato',
            field=models.DateField(blank=True, null=True, verbose_name='data do extrato'),
        ),
        migrations.AddField(
            model_name='observacaoconciliacao',
            name='saldo_extrato',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='saldo do extrato'),
        ),
        migrations.AlterField(
            model_name='observacaoconciliacao',
            name='texto',
            field=models.TextField(blank=True, max_length=600, null=True, verbose_name='Observações da conciliação'),
        ),
    ]
