# Generated by Django 2.2.10 on 2021-03-11 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0147_auto_20210219_1110'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiPermissoesPerfis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '[API] Permissões Leitura e Gravação',
                'verbose_name_plural': '[API] Permissões Leitura e Gravação',
                'permissions': (('ue_leitura', '[API.UE] Pode ler da API com perfil de UE.'), ('ue_gravacao', '[API.UE] Pode gravar na API com perfil de UE.'), ('dre_leitura', '[API.DRE] Pode ler da API com perfil de DRE.'), ('dre_gravacao', '[API.DRE] Pode gravar na API com perfil de DRE.'), ('sme_leitura', '[API.SME] Pode ler da API com perfil de SME.'), ('sme_gravacao', '[API.SME] Pode gravar na API com perfil de SME.')),
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='FuncDreAcompanhamentoDePcs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '[DRE] Acompanhamento de PCs',
                'verbose_name_plural': '[DRE] Acompanhamento de PCs',
                'permissions': (('access_acompanhamento_pcs_dre', '[DRE] Pode acessar Acompanhamento de PCs.'),),
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='FuncDreAssociacoesDaDre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '[DRE] Associações da DRE',
                'verbose_name_plural': '[DRE] Associações da DRE',
                'permissions': (('access_associacao_dre', '[DRE] Pode acessar Associações da DRE.'), ('access_dados_unidade_dre', '[DRE] Pode acessar dados de uma unidade.'), ('access_regularidade_dre', '[DRE] Pode acessar regularidade de uma unidade.'), ('access_situacao_financeira_dre', '[DRE] Pode acessar a situação financeira de uma unidade.')),
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='FuncDreDadosDaDiretoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '[DRE] Dados da diretoria',
                'verbose_name_plural': '[DRE] Dados da diretoria',
                'permissions': (('access_dados_diretoria', '[DRE] Pode acessar Dados da Diretoria.'),),
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='FuncDreFaqDre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '[DRE] FAQ',
                'verbose_name_plural': '[DRE] FAQ',
                'permissions': (('access_faq_dre', '[DRE] Pode acessar FAQ.'),),
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='FuncDreRelatorioConsolidado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '[DRE] Relatório consolidado',
                'verbose_name_plural': '[DRE] Relatório consolidado',
                'permissions': (('access_relatorio_consolidado_dre', '[DRE] Pode acessar Relatório Consolidado.'), ('change_relatorio_consolidado_dre', '[DRE] Pode atualizar informações dos Relatórios Consolidados.'), ('gerar_relatorio_consolidado_dre', '[DRE] Pode gerar Relatório Consolidado.')),
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='FuncSmeAcompanhamentoDePc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '[SME] Acompanhamento de PC',
                'verbose_name_plural': '[SME] Acompanhamento de PC',
                'permissions': (('access_acompanhamento_pc_sme', '[SME] Pode acessar o Acompanhamento de PC.'),),
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='FuncSmePainelParametrizacoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '[SME] Painel de Parametrizacoes',
                'verbose_name_plural': '[SME] Painel de Parametrizacoes',
                'permissions': (('access_painel_parametrizacoes', '[SME] Pode acessar o Painel de parametrizações.'),),
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='FuncUeConciliacaoBancaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '[UE] Conciliação bancária',
                'verbose_name_plural': '[UE] Conciliação bancária',
                'permissions': (('access_conciliacao_bancaria', '[UE] Pode acessar Conciliação Bancária.'), ('change_conciliacao_bancaria', '[UE] Pode atualizar Conciliação Bancária.')),
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='FuncUeCreditosDaEscola',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '[UE] Créditos da Escola',
                'verbose_name_plural': '[UE] Créditos da Escola',
                'permissions': (('access_receita', '[UE] Pode acessar Créditos da Escola.'), ('add_valores_reprogramados', '[UE] Pode implantar valores reprogramados em Créditos da Escola.'), ('add_receita', '[UE] Pode incluir Créditos da Escola.'), ('change_receita', '[UE] Pode editar Créditos da Escola.'), ('delete_receita', '[UE] Pode excluir Créditos da Escola.')),
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='FuncUeDadosDaEscola',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '[UE] Dados da Associação',
                'verbose_name_plural': '[UE] Dados da Associação',
                'permissions': (('access_dados_associacao', '[UE] Pode acessar Dados da Associação.'), ('change_associacao', '[UE] Pode editar Dados da Associação.')),
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='FuncUeGastosDaEscola',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '[UE] Gastos da Escola',
                'verbose_name_plural': '[UE] Gastos da Escola',
                'permissions': (('access_despesa', '[UE] Pode acessar Gastos da Escola.'), ('add_despesa', '[UE] Pode incluir Gastos da Escola.'), ('change_despesa', '[UE] Pode editar Gastos da Escola.'), ('delete_despesa', '[UE] Pode excluir Gastos da Escola.')),
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='FuncUeGerais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '[Global]',
                'verbose_name_plural': '[Global]',
                'permissions': (('view_default', '[Global] Pode acessar as funcionalidades de livre acesso.'),),
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='FuncUePrestacaoDeContas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '[UE] Prestação de contas',
                'verbose_name_plural': '[UE] Prestação de contas',
                'permissions': (('access_prestacao_contas', '[UE] Pode acessar Prestação de Contas:Geração de documentos.'),),
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='FuncUeResumoDosRecursos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '[UE] Resumo dos recursos',
                'verbose_name_plural': '[UE] Resumo dos recursos',
                'permissions': (('access_painel_recursos_ue', '[UE] Pode ver resumo dos recursos.'),),
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
