# Generated by Django 2.2.10 on 2021-03-08 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0147_auto_20210219_1110'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuncDreAcompanhamentoDePcs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '[DRE] Acompanhamento de PCs',
                'verbose_name_plural': '[DRE] Acompanhamento de PCs',
                'permissions': (('view_dashboard_dre', '[DRE] Pode ver Acompanhamento de PCs.'),),
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='FuncDreAssociacoesDaDre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '[DRE] Associações da DRE',
                'verbose_name_plural': '[DRE] Associações da DRE',
                'permissions': (('view_associacao_dre', '[DRE] Pode ver associações da DRE.'),),
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='FuncDreDadosDaDiretoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '[DRE] Dados da diretoria',
                'verbose_name_plural': '[DRE] Dados da diretoria',
                'permissions': (('view_dadosdiretoria_dre', '[DRE] Pode ver dados da diretoria.'),),
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='FuncDreFaqDre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '[DRE] FAQ',
                'verbose_name_plural': '[DRE] FAQ',
                'permissions': (('view_faq_dre', '[DRE] Pode ver FAQ.'),),
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='FuncDreRelatorioConsolidado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '[DRE] Relatório consolidado',
                'verbose_name_plural': '[DRE] Relatório consolidado',
                'permissions': (('view_relatorio_consolidado_dre', '[DRE] Pode ver Relatório consolidado.'), ('change_relatorio_consolidado_dre', '[DRE] Pode atualizar Relatório consolidado.'), ('gerar_relatorio_consolidado_dre', '[DRE] Pode gerar Relatório consolidado.')),
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='FuncSmeAcompanhamentoDePc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '[SME] Acompanhamento de PC',
                'verbose_name_plural': '[SME] Acompanhamento de PC',
                'permissions': (('view_acompanhamento_pc_sme', '[SME] Pode ver Acompanhamento de PC.'),),
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='FuncSmePainelParametrizacoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '[SME] Painel de Parametrizacoes',
                'verbose_name_plural': '[SME] Painel de Parametrizacoes',
                'permissions': (('view_painel_parametrizacoes', '[SME] Pode ver Painel de parametrizações.'),),
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='FuncSmeParametrizacaoAcoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '[SME] Parametrização de Ações',
                'verbose_name_plural': '[SME] Parametrização de Ações',
                'permissions': (('view_parametrizacao_acoes', '[SME] Pode ver Parametrização de Ações.'),),
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='FuncSmeParametrizacaoAcoesAssociacoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '[SME] Parametrização de Ações de Associações',
                'verbose_name_plural': '[SME] Parametrização de Ações de Associações',
                'permissions': (('view_parametrizacao_acoes_associacoes', '[SME] Pode ver Parametrização de Ações de Associações.'),),
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='FuncSmeParametrizacaoAssociacoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '[SME] Parametrização de Associações',
                'verbose_name_plural': '[SME] Parametrização de Associações',
                'permissions': (('view_parametrizacao_associacoes', '[SME] Pode ver Parametrização de Associações.'),),
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='FuncSmeParametrizacaoPeriodos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '[SME] Parametrização de Períodos',
                'verbose_name_plural': '[SME] Parametrização de Períodos',
                'permissions': (('view_parametrizacao_periodos', '[SME] Pode ver Parametrização de Períodos.'),),
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='FuncSmeParametrizacaoTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '[SME] Parametrização de Tags',
                'verbose_name_plural': '[SME] Parametrização de Tags',
                'permissions': (('view_parametrizacao_tags', '[SME] Pode ver Parametrização de Tags.'),),
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='FuncSmeParametrizacaoTextosFiqueDeOlho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '[SME] Parametrização de Textos do Fique de Olho',
                'verbose_name_plural': '[SME] Parametrização de Textos do Fique de Olho',
                'permissions': (('view_parametrizacao_textos_fique_de_olho', '[SME] Pode ver Parametrização de Textos do Fique de Olho.'),),
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='FuncSmeParametrizacaoTiposDeCusteio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '[SME] Parametrização de Tipos de Custeio',
                'verbose_name_plural': '[SME] Parametrização de Tipos de Custeio',
                'permissions': (('view_parametrizacao_tipos_custeio', '[SME] Pode ver Parametrização de Tipos de Custeio.'),),
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='FuncUeConciliacaoBancaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '[UE] Conciliação bancária',
                'verbose_name_plural': '[UE] Conciliação bancária',
                'permissions': (('view_conciliacao_bancaria', '[UE] Pode ver conciliacao_bancaria.'), ('change_conciliacao_bancaria', '[UE] Pode atualizar conciliação bancária.')),
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='FuncUeCreditosDaEscola',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '[UE] Créditos da Escola',
                'verbose_name_plural': '[UE] Créditos da Escola',
                'permissions': (('view_receita', '[UE] Pode ver créditos da escola.'), ('add_receita', '[UE] Pode incluir créditos da escola.'), ('change_receita', '[UE] Pode editar créditos da escola.'), ('delete_receita', '[UE] Pode excluir créditos da escola.'), ('add_valores_reprogramados', '[UE] Pode implantar valores reprogramados.')),
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='FuncUeDadosDaEscola',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '[UE] Dados da Associação',
                'verbose_name_plural': '[UE] Dados da Associação',
                'permissions': (('view_associacao', '[UE] Pode ver dados da associação.'), ('change_associacao', '[UE] Pode editar dados da associacao.')),
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='FuncUeGastosDaEscola',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '[UE] Gastos da Escola',
                'verbose_name_plural': '[UE] Gastos da Escola',
                'permissions': (('view_despesa', '[UE] Pode ver gastos da escola.'), ('add_despesa', '[UE] Pode incluir gastos da escola.'), ('change_despesa', '[UE] Pode editar gastos da escola.'), ('delete_despesa', '[UE] Pode excluir gastos da escola.')),
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='FuncUePrestacoesDeConta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '[UE] Prestações de conta',
                'verbose_name_plural': '[UE] Prestações de conta',
                'permissions': (('view_prestacaoconta', '[UE] Pode ver prestações de conta.'),),
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='FuncUeResumoDosRecursos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '[UE] Resumo dos recursos',
                'verbose_name_plural': '[UE] Resumo dos recursos',
                'permissions': (('view_painel_recursos_ue', '[UE] Pode ver resumo dos recursos.'),),
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
