# Generated by Django 2.2.10 on 2021-03-11 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0148_apipermissoesperfis_funcdreacompanhamentodepcs_funcdreassociacoesdadre_funcdredadosdadiretoria_funcd'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuncDreGestaoPerfis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '[DRE] Gestão de perfis',
                'verbose_name_plural': '[DRE] Gestão de perfis',
                'permissions': (('access_gestao_perfis_dre', '[DRE] Pode acessar Gestão de Perfis da DRE.'),),
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='FuncSmeGestaoPerfis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '[SME] Gestão de perfis',
                'verbose_name_plural': '[SME] Gestão de perfis',
                'permissions': (('access_gestao_perfis_sme', '[SME] Pode acessar Gestão de Perfis da SME.'),),
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='FuncUeGestaoPerfis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '[UE] Gestão de perfis',
                'verbose_name_plural': '[UE] Gestão de perfis',
                'permissions': (('access_gestao_perfis_ue', '[UE] Pode acessar Gestão de Perfis da UE.'),),
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
