# Generated by Django 2.2.10 on 2021-03-09 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0148_ambiente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambiente',
            name='nome',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='ambiente',
            name='prefixo',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
