# Generated by Django 2.2.10 on 2021-03-11 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0149_funcdregestaoperfis_funcsmegestaoperfis_funcuegestaoperfis'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuncSmeArquivosCarga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '[SME] Arquivos de carga',
                'verbose_name_plural': '[SME] Arquivos de carga',
                'permissions': (('access_arquivos_carga', '[SME] Pode acessar Arquivos de Carga em parametrizações.'),),
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
