# Generated by Django 2.2.10 on 2021-03-11 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0150_funcsmearquivoscarga'),
        ('core', '0150_auto_20210309_1524'),
    ]

    operations = [
    ]
