# Generated by Django 2.2.10 on 2021-03-12 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0151_merge_20210311_1331'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='funcdreassociacoesdadre',
            options={'default_permissions': (), 'managed': False, 'permissions': (('access_associacao_dre', '[DRE] Pode acessar Associações da DRE.'), ('access_dados_unidade_dre', '[DRE] Pode acessar dados de uma unidade.'), ('access_regularidade_dre', '[DRE] Pode acessar regularidade de uma unidade.'), ('access_situacao_financeira_dre', '[DRE] Pode acessar a situação financeira de uma unidade.'), ('change_regularidade', '[DRE] Pode atualizar a regularidade de uma unidade.')), 'verbose_name': '[DRE] Associações da DRE', 'verbose_name_plural': '[DRE] Associações da DRE'},
        ),
    ]
