# Generated by Django 2.2.10 on 2021-03-15 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0151_merge_20210311_1331'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuncSmeConsultaSaldoBancario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '[SME] Consulta Saldo Bancário',
                'verbose_name_plural': '[SME] Consulta Saldos Bancários',
                'permissions': (('access_consulta_saldo_bancario', '[SME] Pode acessar a consulta de saldo bancário.'),),
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
