# Generated by Django 2.2.10 on 2021-03-13 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0152_auto_20210312_0901'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='funcueprestacaodecontas',
            options={'default_permissions': (), 'managed': False, 'permissions': (('access_prestacao_contas', '[UE] Pode acessar Prestação de Contas:Geração de documentos.'), ('concluir_periodo_prestacao_contas', '[UE] Pode concluir período em Prestação de Contas.'), ('gerar_previas_prestacao_contas', '[UE] Pode gerar prévias em Prestação de Contas.'), ('baixar_documentos_prestacao_contas', '[UE] Pode baixar documentos de Prestação de Contas.'), ('change_ata_prestacao_contas', '[UE] Pode atualizar atas de Prestação de Contas.')), 'verbose_name': '[UE] Prestação de contas', 'verbose_name_plural': '[UE] Prestação de contas'},
        ),
    ]
