# Generated by Django 2.2.10 on 2021-03-16 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0152_funcsmeconsultasaldobancario'),
        ('core', '0153_auto_20210313_0628'),
    ]

    operations = [
    ]
