# Generated by Django 2.2.10 on 2021-03-23 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0156_relacaobens_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='demonstrativofinanceiro',
            name='versao',
            field=models.CharField(choices=[('FINAL', 'Documento final'), ('PREVIA', 'Prévia')], default='FINAL', max_length=20, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='relacaobens',
            name='versao',
            field=models.CharField(choices=[('FINAL', 'Documento final'), ('PREVIA', 'Prévia')], default='FINAL', max_length=20, verbose_name='status'),
        ),
    ]
