# Generated by Django 2.2.10 on 2021-03-23 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0158_auto_20210323_1056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demonstrativofinanceiro',
            name='acao_associacao',
        ),
        migrations.AddField(
            model_name='demonstrativofinanceiro',
            name='periodo_previa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='demonstrativos_previos_do_periodo', to='core.Periodo', verbose_name='Período da prévia'),
        ),
        migrations.AddField(
            model_name='relacaobens',
            name='periodo_previa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='relacoes_de_bens_previos_do_periodo', to='core.Periodo', verbose_name='Período da prévia'),
        ),
    ]
