# Generated by Django 2.2.10 on 2021-03-25 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0161_auto_20210323_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='observacaoconciliacao',
            name='comprovante_extrato',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='observacaoconciliacao',
            name='data_atualizacao_comprovante_extrato',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
