# Generated by Django 2.2.10 on 2021-03-30 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0162_auto_20210325_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='demonstrativofinanceiro',
            name='arquivo_pdf',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Relatório em PDF'),
        ),
        migrations.AlterField(
            model_name='demonstrativofinanceiro',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Relatório em XLSX'),
        ),
    ]
