# Generated by Django 2.2.10 on 2021-04-22 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0164_auto_20210414_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='ata',
            name='arquivo_pdf',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Relatório em PDF'),
        ),
    ]
