# Generated by Django 2.2.10 on 2021-04-26 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0165_ata_arquivo_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='ata',
            name='status',
            field=models.CharField(choices=[('EM_PROCESSAMENTO', 'Em processamento'), ('CONCLUIDO', 'Geração concluída')], default='CONCLUIDO', max_length=20, verbose_name='status'),
        ),
    ]
