# Generated by Django 2.2.10 on 2021-04-27 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0166_ata_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ata',
            name='status',
        ),
        migrations.AddField(
            model_name='ata',
            name='status_geracao_pdf',
            field=models.CharField(choices=[('NAO_GERADO', 'Não gerado'), ('EM_PROCESSAMENTO', 'Em processamento'), ('CONCLUIDO', 'Geração concluída')], default='NAO_GERADO', max_length=20, verbose_name='status Pdf'),
        ),
    ]
