# Generated by Django 2.2.10 on 2021-04-28 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0165_ativa_unaccent'),
        ('core', '0167_auto_20210427_0813'),
    ]

    operations = [
    ]
