# Generated by Django 2.2.10 on 2021-05-10 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0168_merge_20210428_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidade',
            name='tipo_unidade',
            field=models.CharField(choices=[('ADM', 'ADM'), ('DRE', 'DRE'), ('IFSP', 'IFSP'), ('CMCT', 'CMCT'), ('CECI', 'CECI'), ('CEI', 'CEI'), ('CEMEI', 'CEMEI'), ('CIEJA', 'CIEJA'), ('EMEBS', 'EMEBS'), ('EMEF', 'EMEF'), ('EMEFM', 'EMEFM'), ('EMEI', 'EMEI'), ('CEU', 'CEU'), ('CEU CEI', 'CEU CEI'), ('CEI DIRET', 'CEI DIRET')], default='ADM', max_length=10),
        ),
    ]
