# Generated by Django 2.2.10 on 2021-05-28 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0172_funcdreatribuicaoporue'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuncDreProcessoSei',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '[DRE] Processo SEI',
                'verbose_name_plural': '[DRE] Processos SEI',
                'permissions': (('access_processo_sei', '[DRE] Pode acessar Processo SEI.'), ('change_processo_sei', '[DRE] Pode atualizar Processo SEI.')),
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
