# Generated by Django 2.2.10 on 2021-05-31 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0173_funcdreprocessosei'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuncDreTecnicosDaDiretoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '[DRE] Técnico da Diretoria',
                'verbose_name_plural': '[DRE] Técnicos da Diretoria',
                'permissions': (('access_tecnicos_da_diretoria', '[DRE] Pode acessar Técnicos da Diretoria.'), ('change_tecnicos_da_diretoria', '[DRE] Pode atualizar Técnicos da Diretoria.')),
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
