# Generated by Django 2.2.10 on 2021-06-14 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0174_funcdretecnicosdadiretoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacao',
            name='tipo',
            field=models.CharField(choices=[('ALERTA', 'Alerta'), ('INFORMACAO', 'Informação'), ('URGENTE', 'Urgente'), ('AVISO', 'Aviso')], default='INFORMACAO', max_length=15, verbose_name='Tipo'),
        ),
    ]
