# Generated by Django 2.2.10 on 2021-06-14 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0175_auto_20210614_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacao',
            name='categoria',
            field=models.CharField(choices=[('COMENTARIO_PC', 'Comentário na prestação de contas'), ('ELABORACAO_PC', 'Elaboração de PC')], default='COMENTARIO_PC', max_length=15, verbose_name='Categoria'),
        ),
    ]
