# Generated by Django 2.2.10 on 2021-06-14 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0177_auto_20210614_1754'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Remetente',
        ),
        migrations.DeleteModel(
            name='TipoNotificacao',
        ),
    ]
