# Generated by Django 2.2.10 on 2021-06-15 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0178_auto_20210614_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametros',
            name='dias_antes_inicio_periodo_pc_para_notificacao',
            field=models.PositiveSmallIntegerField(default=5, verbose_name='Quantos dias antes do inicio do período de PC, os usuários serão notificados?'),
        ),
    ]
