# Generated by Django 2.2.10 on 2021-06-15 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0179_parametros_dias_antes_inicio_periodo_pc_para_notificacao'),
        ('core', '0180_periodo_notificacao_inicio_periodo_pc_realizada'),
    ]

    operations = [
    ]
