# Generated by Django 2.2.10 on 2021-06-16 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0181_merge_20210615_1434'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='funcuerecebimentodenotificacoes',
            options={'default_permissions': (), 'managed': False, 'permissions': (('recebe_notificacao_inicio_periodo_prestacao_de_contas', '[UE] Pode receber Notificação Início Período Prestação De Contas.'), ('recebe_notificacao_pendencia_envio_prestacao_de_contas', '[UE] Pode receber Notificação pendência envio Prestação De Contas.')), 'verbose_name': '[UE] Recebimento de notificações', 'verbose_name_plural': '[UE] Recebimento de notificações'},
        ),
    ]
