# Generated by Django 2.2.10 on 2021-06-17 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0183_periodo_notificacao_pendencia_envio_pc_realizada'),
        ('core', '0183_periodo_notificacao_proximidade_inicio_pc_realizada'),
    ]

    operations = [
    ]
