# Generated by Django 2.2.10 on 2021-06-18 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0187_auto_20210618_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodo',
            name='notificacao_proximidade_fim_pc_realizada',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Notificação proximidade fim PC realizada'),
        ),
    ]
