# Generated by Django 2.2.10 on 2021-06-18 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0188_periodo_notificacao_proximidade_fim_pc_realizada'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametros',
            name='dias_antes_fim_periodo_pc_para_notificacao',
            field=models.PositiveSmallIntegerField(default=5, verbose_name='Quantos dias antes do fim do período de PC, os usuários serão notificados?'),
        ),
    ]
