# Generated by Django 2.2.10 on 2021-06-21 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0191_auto_20210621_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametros',
            name='dias_antes_fim_prazo_ajustes_pc_para_notificacao',
            field=models.PositiveSmallIntegerField(default=5, verbose_name='Quantos dias antes do fim do prazo para entrega de ajustes de PC, os usuários serão notificados?'),
        ),
    ]
