# Generated by Django 2.2.10 on 2021-08-06 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0192_parametros_dias_antes_fim_prazo_ajustes_pc_para_notificacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuncDreFornecedores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '[DRE] Cadastro de Fornecedor',
                'verbose_name_plural': '[DRE] Cadastro de Fornecedores',
                'permissions': (('access_fornecedores', '[DRE] Pode acessar cadastro de fornecedores.'), ('change_fornecedores', '[DRE] Pode atualizar cadastro de fornecedores.')),
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='FuncSmeFornecedores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '[SME] Parametrização Cadastro de Fornecedor',
                'verbose_name_plural': '[SME] Parametrizações Cadastro de Fornecedores',
                'permissions': (('access_fornecedores', '[SME] Pode acessar parametrizações cadastro de fornecedores.'), ('change_fornecedores', '[SME] Pode atualizar parametrizações cadastro de fornecedores.')),
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
