# Generated by Django 2.2.10 on 2021-08-18 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0193_funcdrefornecedores_funcsmefornecedores'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuncUeAnaliseDre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '[UE] Análise DRE',
                'verbose_name_plural': '[UE] Análises DRE',
                'permissions': (('access_analise_dre', '[UE] Pode acessar Análise DRE.'), ('change_analise_dre', '[UE] Pode atualizar Análise DRE.')),
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
