# Generated by Django 2.2.10 on 2021-08-12 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0193_funcdrefornecedores_funcsmefornecedores'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArquivoDownload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alterado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('arquivo', models.FileField(upload_to='', verbose_name='Arquivo')),
                ('status', models.CharField(choices=[('EM_PROCESSAMENTO', 'Em processamento'), ('CONCLUIDO', 'Concluído'), ('ERRO', 'Erro')], default='EM_PROCESSAMENTO', max_length=20, verbose_name='status')),
                ('msg_erro', models.CharField(blank=True, max_length=300, verbose_name='Mensagem erro')),
                ('lido', models.BooleanField(default=False, verbose_name='Foi lido?')),
                ('central_de_downloads', models.BooleanField(default=False, verbose_name='Deve ir para central de downloads?')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
