# Generated by Django 2.2.10 on 2021-08-12 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0194_arquivodownload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arquivodownload',
            name='arquivo',
            field=models.FileField(null=True, upload_to='', verbose_name='Arquivo'),
        ),
    ]
