# Generated by Django 2.2.10 on 2021-08-19 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0194_analiseprestacaoconta'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestacaoconta',
            name='analise_atual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.AnalisePrestacaoConta'),
        ),
    ]
