# Generated by Django 2.2.10 on 2021-08-20 13:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0038_auto_20210805_1046'),
        ('receitas', '0037_tiporeceita_possui_detalhamento'),
        ('core', '0195_prestacaoconta_analise_atual'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnaliseLancamentoPrestacaoConta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alterado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('tipo_lancamento', models.CharField(choices=[('CREDITO', 'Crédito'), ('GASTO', 'Gasto')], default='CREDITO', max_length=20, verbose_name='status')),
                ('resultado', models.CharField(choices=[('CORRETO', 'Lançamento Correto'), ('AJUSTE', 'Ajuste necessário')], default='CORRETO', max_length=20, verbose_name='status')),
                ('analise_prestacao_conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analises_de_lancamentos', to='core.AnalisePrestacaoConta')),
                ('despesa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='analises_de_lancamento_da_despesa', to='despesas.Despesa')),
                ('receita', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='analises_de_lancamento_da_receita', to='receitas.Receita')),
            ],
            options={
                'verbose_name': 'Análise de lançamento',
                'verbose_name_plural': '15.1) Análises de lançamentos',
            },
        ),
    ]
