# Generated by Django 2.2.10 on 2021-08-13 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0195_auto_20210812_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='arquivodownload',
            name='identificador',
            field=models.CharField(default='', max_length=20, verbose_name='Nome do arquivo'),
        ),
    ]
