# Generated by Django 2.2.10 on 2021-08-19 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0196_arquivodownload_identificador'),
        ('core', '0194_funcueanalisedre'),
    ]

    operations = [
    ]
