# Generated by Django 2.2.10 on 2021-08-22 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0197_merge_20210819_1025'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arquivodownload',
            options={'verbose_name': 'Arquivo Download', 'verbose_name_plural': '15.0) Arquivos Download'},
        ),
        migrations.AlterField(
            model_name='arquivodownload',
            name='identificador',
            field=models.CharField(default='', max_length=200, verbose_name='Nome do arquivo'),
        ),
    ]
