# Generated by Django 2.2.10 on 2021-08-22 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0198_auto_20210822_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arquivodownload',
            name='central_de_downloads',
        ),
    ]
