# Generated by Django 2.2.10 on 2021-08-23 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0196_analiselancamentoprestacaoconta'),
        ('core', '0199_remove_arquivodownload_central_de_downloads'),
    ]

    operations = [
    ]
