# Generated by Django 2.2.10 on 2021-08-26 14:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0201_tipoacertolancamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoAcertoLancamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alterado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('detalhamento', models.TextField(blank=True, default='', max_length=600, verbose_name='Motivo')),
                ('analise_lancamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_de_ajuste_da_analise', to='core.AnaliseLancamentoPrestacaoConta')),
                ('devolucao_ao_tesouro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitacao_de_ajuste_da_devolucao', to='core.DevolucaoAoTesouro')),
                ('tipo_acerto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.TipoAcertoLancamento')),
            ],
            options={
                'verbose_name': 'Solicitação de acerto em lançamento',
                'verbose_name_plural': '15.2) Solicitações de acertos em lançamentos',
            },
        ),
    ]
