# Generated by Django 2.2.10 on 2021-09-01 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0202_solicitacaoacertolancamento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analiselancamentoprestacaoconta',
            options={'verbose_name': 'Análise de lançamento', 'verbose_name_plural': '16.1) Análises de lançamentos'},
        ),
        migrations.AlterModelOptions(
            name='analiseprestacaoconta',
            options={'verbose_name': 'Análise de prestação de contas', 'verbose_name_plural': '16.0) Análises de prestações de contas'},
        ),
        migrations.AlterModelOptions(
            name='solicitacaoacertolancamento',
            options={'verbose_name': 'Solicitação de acerto em lançamento', 'verbose_name_plural': '16.3) Solicitações de acertos em lançamentos'},
        ),
        migrations.AlterModelOptions(
            name='tipoacertolancamento',
            options={'verbose_name': 'Tipo de acerto em lançamentos', 'verbose_name_plural': '16.2) Tipos de acerto em lançamentos'},
        ),
    ]
