# Generated by Django 2.2.10 on 2021-09-09 15:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0204_tipodocumentoprestacaoconta'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoAcertoDocumento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=160, verbose_name='Nome')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alterado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('tipos_documento_prestacao', models.ManyToManyField(blank=True, to='core.TipoDocumentoPrestacaoConta')),
            ],
            options={
                'verbose_name': 'Tipo de acerto em documentos',
                'verbose_name_plural': '16.5) Tipos de acerto em documentos',
            },
        ),
    ]
