# Generated by Django 2.2.10 on 2021-09-10 11:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0205_tipoacertodocumento'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnaliseDocumentoPrestacaoConta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alterado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('resultado', models.CharField(choices=[('CORRETO', 'Documento Correto'), ('AJUSTE', 'Ajuste necessário')], default='CORRETO', max_length=20, verbose_name='status')),
                ('analise_prestacao_conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analises_de_documento', to='core.AnalisePrestacaoConta')),
                ('tipo_documento_prestacao_conta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='analises_do_documento', to='core.TipoDocumentoPrestacaoConta')),
            ],
            options={
                'verbose_name': 'Análise de documentos de PC',
                'verbose_name_plural': '16.6) Análises de documentos de PC',
            },
        ),
    ]
