# Generated by Django 2.2.10 on 2021-09-13 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0206_analisedocumentoprestacaoconta'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipodocumentoprestacaoconta',
            name='documento_por_conta',
            field=models.BooleanField(default=False, verbose_name='Documento por tipode conta?'),
        ),
    ]
