# Generated by Django 2.2.10 on 2021-09-13 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0207_tipodocumentoprestacaoconta_documento_por_conta'),
    ]

    operations = [
        migrations.AddField(
            model_name='analisedocumentoprestacaoconta',
            name='tipo_conta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='analises_de_documento_do_tipo_conta', to='core.TipoConta'),
        ),
    ]
