# Generated by Django 2.2.10 on 2021-09-13 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0208_analisedocumentoprestacaoconta_tipo_conta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analisedocumentoprestacaoconta',
            name='tipo_conta',
        ),
        migrations.AddField(
            model_name='analisedocumentoprestacaoconta',
            name='conta_associacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='analises_de_documento_da_conta', to='core.ContaAssociacao'),
        ),
    ]
