# Generated by Django 2.2.10 on 2021-09-14 07:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0209_auto_20210913_1356'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoAcertoDocumento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alterado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('analise_documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_de_ajuste_da_analise', to='core.AnaliseDocumentoPrestacaoConta')),
                ('tipo_acerto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.TipoAcertoDocumento')),
            ],
            options={
                'verbose_name': 'Solicitação de acerto em documento',
                'verbose_name_plural': '16.7) Solicitações de acertos em documentos',
            },
        ),
    ]
