# Generated by Django 2.2.10 on 2021-09-22 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0210_solicitacaoacertodocumento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacaoacertolancamento',
            name='devolucao_ao_tesouro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacao_de_ajuste_da_devolucao', to='core.DevolucaoAoTesouro'),
        ),
    ]
