# Generated by Django 2.2.10 on 2021-09-29 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0211_auto_20210922_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipodocumentoprestacaoconta',
            name='documento_por_conta',
            field=models.BooleanField(default=False, verbose_name='Documento por tipo de conta?'),
        ),
    ]
