# Generated by Django 2.2.10 on 2021-10-07 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0214_auto_20210930_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='analiseprestacaoconta',
            name='arquivo_pdf',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Relatório em PDF'),
        ),
        migrations.AddField(
            model_name='analiseprestacaoconta',
            name='versao',
            field=models.CharField(choices=[('FINAL', 'final'), ('RASCUNHO', 'rascunho')], default='FINAL', max_length=20, verbose_name='versão'),
        ),
    ]
