# Generated by Django 2.2.10 on 2021-10-07 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0215_auto_20211007_0748'),
    ]

    operations = [
        migrations.AddField(
            model_name='analiseprestacaoconta',
            name='status_versao',
            field=models.CharField(choices=[('EM_PROCESSAMENTO', 'Em processamento'), ('CONCLUIDO', 'Geração concluída')], default='CONCLUIDO', max_length=20, verbose_name='status'),
        ),
    ]
