# Generated by Django 2.2.10 on 2021-10-04 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0215_auto_20211004_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestacaoconta',
            name='data_recebimento_apos_acertos',
            field=models.DateField(blank=True, null=True, verbose_name='data de recebimento pela DRE após acertos'),
        ),
    ]
