# Generated by Django 2.2.10 on 2021-10-07 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0216_analiseprestacaoconta_status_versao'),
    ]

    operations = [
        migrations.AddField(
            model_name='analiseprestacaoconta',
            name='arquivo_pdf_criado_em',
            field=models.DateTimeField(null=True, verbose_name='Arquivo pdf gerado em'),
        ),
    ]
