# Generated by Django 2.2.10 on 2021-10-13 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0216_prestacaoconta_data_recebimento_apos_acertos'),
        ('core', '0218_auto_20211008_1202'),
    ]

    operations = [
    ]
