# Generated by Django 2.2.10 on 2021-10-25 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dre', '0026_motivoreprovacao'),
        ('core', '0220_auto_20211018_0741'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestacaoconta',
            name='outros_motivos_reprovacao',
            field=models.TextField(blank=True, default='', verbose_name='Outros motivos para reprovação pela DRE'),
        ),
        migrations.RemoveField(
            model_name='prestacaoconta',
            name='motivos_reprovacao',
        ),
        migrations.AddField(
            model_name='prestacaoconta',
            name='motivos_reprovacao',
            field=models.ManyToManyField(blank=True, to='dre.MotivoReprovacao'),
        ),
    ]
