# Generated by Django 2.2.10 on 2021-10-26 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0221_auto_20211025_1330'),
        ('core', '0221_auto_20211020_1426'),
    ]

    operations = [
    ]
