# Generated by Django 2.2.10 on 2021-10-26 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0222_merge_20211026_0830'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaoacertodocumento',
            name='detalhamento',
            field=models.TextField(blank=True, default='', max_length=600, verbose_name='Motivo'),
        ),
    ]
