# Generated by Django 2.2.10 on 2021-10-26 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0222_merge_20211026_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacao',
            name='usuario',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
