# Generated by Django 2.2.10 on 2021-10-26 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0223_auto_20211026_1355'),
        ('core', '0223_solicitacaoacertodocumento_detalhamento'),
    ]

    operations = [
    ]
