# Generated by Django 2.2.10 on 2021-11-03 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0224_merge_20211026_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='associacao',
            name='cargo_substituto_presidente_ausente',
            field=models.CharField(blank=True, choices=[('PRESIDENTE_DIRETORIA_EXECUTIVA', 'Presidente da diretoria executiva'), ('VICE_PRESIDENTE_DIRETORIA_EXECUTIVA', 'Vice-Presidente da diretoria executiva'), ('SECRETARIO', 'Secretario'), ('TESOUREIRO', 'Tesoureiro'), ('VOGAL_1', 'Vogal 1'), ('VOGAL_2', 'Vogal 2'), ('VOGAL_3', 'Vogal 3'), ('VOGAL_4', 'Vogal 4'), ('VOGAL_5', 'Vogal 5'), ('PRESIDENTE_CONSELHO_FISCAL', 'Presidente do conselho fiscal'), ('CONSELHEIRO_1', 'Conselheiro 1'), ('CONSELHEIRO_2', 'Conselheiro 2'), ('CONSELHEIRO_3', 'Conselheiro 3'), ('CONSELHEIRO_4', 'Conselheiro 4')], default=None, max_length=65, null=True, verbose_name='Cargo substituto do presidente ausente'),
        ),
        migrations.AddField(
            model_name='associacao',
            name='status_presidente',
            field=models.CharField(choices=[('PRESENTE', 'Presente'), ('AUSENTE', 'Ausente')], default='PRESENTE', max_length=15, verbose_name='Status do Presidente'),
        ),
    ]
