# Generated by Django 2.2.10 on 2021-11-03 11:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0225_presentesata'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresenteAta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alterado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('identificacao', models.CharField(blank=True, default='', max_length=20, verbose_name='Identificacão do presente (RF,CPF ou EOL)')),
                ('nome', models.CharField(blank=True, default='', max_length=200, verbose_name='Nome')),
                ('cargo', models.CharField(blank=True, default='', max_length=200, verbose_name='Cargo')),
                ('membro', models.BooleanField(default=False, verbose_name='Membro ?')),
                ('ata', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='presentes_na_ata', to='core.Ata')),
            ],
            options={
                'verbose_name': 'Presente da ata',
                'verbose_name_plural': '09.10) Presentes das atas',
            },
        ),
        migrations.DeleteModel(
            name='PresentesAta',
        ),
    ]
