# Generated by Django 2.2.10 on 2021-11-09 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0227_auto_20211103_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='presenteata',
            name='conselho_fiscal',
            field=models.BooleanField(default=False, verbose_name='Pertence ao conselho fiscal ?'),
        ),
    ]
