# Generated by Django 2.2.10 on 2021-11-09 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0228_presenteata_conselho_fiscal'),
        ('core', '0227_auto_20211105_0842'),
    ]

    operations = [
    ]
