# Generated by Django 2.2.10 on 2021-11-11 09:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0230_auto_20211111_0911'),
    ]

    operations = [
    ]
