# Generated by Django 2.2.10 on 2021-11-11 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0231_auto_20211111_0918'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='presenteata',
            options={'verbose_name': 'Presente da ata', 'verbose_name_plural': '17.0) Presentes das atas'},
        ),
        migrations.AlterField(
            model_name='presenteata',
            name='ata',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presentes_na_ata', to='core.Ata'),
        ),
    ]
