# Generated by Django 2.2.10 on 2021-11-26 07:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0232_auto_20211111_1602'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnaliseValorReprogramadoPrestacaoConta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alterado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('valor_saldo_reprogramado_correto', models.BooleanField(default=True, verbose_name='O valor de saldo reprogramado inicial está correto?')),
                ('novo_saldo_reprogramado_custeio', models.DecimalField(decimal_places=2, default=None, max_digits=12, null=True, verbose_name='Novo Saldo Reprogramado (Custeio)')),
                ('novo_saldo_reprogramado_capital', models.DecimalField(decimal_places=2, default=None, max_digits=12, null=True, verbose_name='Novo Saldo Reprogramado (Capital)')),
                ('novo_saldo_reprogramado_livre', models.DecimalField(decimal_places=2, default=None, max_digits=12, null=True, verbose_name='Novo Saldo Reprogramado (livre)')),
                ('acao_associacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='analises_de_valores_reprogramados_da_acao', to='core.AcaoAssociacao')),
                ('analise_prestacao_conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analises_de_valores_reprogramados', to='core.AnalisePrestacaoConta')),
                ('conta_associacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='analises_de_valores_reprogramados_da_conta', to='core.ContaAssociacao')),
            ],
            options={
                'verbose_name': 'Análise de valor reprogramado de PC',
                'verbose_name_plural': '16.8) Análises de valores reprogramados de PC',
                'unique_together': {('analise_prestacao_conta', 'conta_associacao', 'acao_associacao')},
            },
        ),
    ]
