# Generated by Django 2.2.10 on 2021-12-09 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0233_analisevalorreprogramadoprestacaoconta'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuncDreComissoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '[DRE] Comissão',
                'verbose_name_plural': '[DRE] Comissões',
                'permissions': (('access_comissoes_dre', '[DRE] Pode acessar Comissões.'), ('change_comissoes_dre', '[DRE] Pode atualizar Comissões.')),
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
