# Generated by Django 2.2.10 on 2021-12-08 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0233_analisevalorreprogramadoprestacaoconta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='associacao',
            name='motivo_nao_regularidade',
        ),
        migrations.RemoveField(
            model_name='associacao',
            name='status_regularidade',
        ),
    ]
