# Generated by Django 2.2.10 on 2021-12-09 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0234_auto_20211208_0922'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuncRegularidadeAssociacoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '[DRE] Regularidade das Associações',
                'verbose_name_plural': '[DRE] Regularidade das Associações',
                'permissions': (('access_regularidade_dre', '[DRE] Pode acessar Regularidade das Associações.'), ('change_regularidade', '[DRE] Pode atualizar a Regularidade das Associações.')),
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.AlterModelOptions(
            name='funcdreassociacoesdadre',
            options={'default_permissions': (), 'managed': False, 'permissions': (('access_associacao_dre', '[DRE] Pode acessar Associações da DRE.'), ('access_dados_unidade_dre', '[DRE] Pode acessar dados de uma unidade.'), ('access_situacao_financeira_dre', '[DRE] Pode acessar a situação financeira de uma unidade.')), 'verbose_name': '[DRE] Associações da DRE', 'verbose_name_plural': '[DRE] Associações da DRE'},
        ),
    ]
