# Generated by Django 2.2.10 on 2021-12-10 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0234_funcdrecomissoes'),
        ('core', '0235_auto_20211209_1420'),
    ]

    operations = [
    ]
