# Generated by Django 2.2.10 on 2021-12-20 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0236_merge_20211210_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='ata',
            name='hora_reuniao',
            field=models.TimeField(default='00:00', verbose_name='Hora da reunião'),
        ),
    ]
