# Generated by Django 2.2.10 on 2021-12-22 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0237_ata_hora_reuniao'),
    ]

    operations = [
        migrations.AddField(
            model_name='acao',
            name='aceita_capital',
            field=models.BooleanField(default=False, verbose_name='Aceita capital?'),
        ),
        migrations.AddField(
            model_name='acao',
            name='aceita_custeio',
            field=models.BooleanField(default=False, verbose_name='Aceita custeio?'),
        ),
        migrations.AddField(
            model_name='acao',
            name='aceita_livre',
            field=models.BooleanField(default=False, verbose_name='Aceita livre aplicação?'),
        ),
    ]
