# Generated by Django 2.2.10 on 2022-01-03 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0238_auto_20211222_0747'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametros',
            name='enviar_email_notificacao',
            field=models.BooleanField(default=True, verbose_name='Envia e-mails de notificação?'),
        ),
    ]
