# Generated by Django 2.2.10 on 2022-01-03 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0239_parametros_enviar_email_notificacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analiselancamentoprestacaoconta',
            name='despesa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analises_de_lancamento_da_despesa', to='despesas.Despesa'),
        ),
        migrations.AlterField(
            model_name='analiselancamentoprestacaoconta',
            name='receita',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analises_de_lancamento_da_receita', to='receitas.Receita'),
        ),
    ]
