# Generated by Django 2.2.10 on 2022-01-10 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0240_auto_20220103_1032'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='funcuerecebimentodenotificacoes',
            options={'default_permissions': (), 'managed': False, 'permissions': (('recebe_notificacao_inicio_periodo_prestacao_de_contas', '[UE] Pode receber Notificação Início Período Prestação De Contas.'), ('recebe_notificacao_pendencia_envio_prestacao_de_contas', '[UE] Pode receber Notificação pendência envio Prestação De Contas.'), ('recebe_notificacao_proximidade_inicio_prestacao_de_contas', '[UE] Pode receber Notificação Proximidade Início Prestação De Contas.'), ('recebe_notificacao_prestacao_de_contas_devolvida_para_acertos', '[UE] Pode receber Notificação Prestação de Contas Devolvida para Acertos'), ('recebe_notificacao_proximidade_fim_periodo_prestacao_de_contas', '[UE] Pode receber Notificação Proximidade Fim Período Prestação de Contas'), ('recebe_notificacao_atraso_entrega_ajustes_prestacao_de_contas', '[UE] Pode receber Notificação Atraso Entrega Ajustes Prestação de Contas'), ('recebe_notificacao_proximidade_fim_prazo_ajustes_prestacao_de_contas', '[UE] Pode receber Notificação Proximidade Fim Prazo Ajustes Prestação de Contas'), ('recebe_notificacao_comentario_em_pc', '[UE] Pode receber Notificação de Comentários')), 'verbose_name': '[UE] Recebimento de notificações', 'verbose_name_plural': '[UE] Recebimento de notificações'},
        ),
    ]
