# Generated by Django 2.2.10 on 2022-01-20 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0241_auto_20220110_1411'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='funcdrerelatorioconsolidado',
            options={'default_permissions': (), 'managed': False, 'permissions': (('access_relatorio_consolidado_dre', '[DRE] Pode acessar Relatório Consolidado.'), ('change_relatorio_consolidado_dre', '[DRE] Pode atualizar informações dos Relatórios Consolidados.'), ('gerar_relatorio_consolidado_dre', '[DRE] Pode gerar Relatório Consolidado.'), ('change_ata_parecer_tecnico', '[DRE] Pode atualizar atas de Parecer Tecnico.')), 'verbose_name': '[DRE] Relatório consolidado', 'verbose_name_plural': '[DRE] Relatório consolidado'},
        ),
    ]
