# Generated by Django 2.2.10 on 2022-01-20 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0241_auto_20220114_0743'),
        ('core', '0241_auto_20220110_1411'),
    ]

    operations = [
    ]
