# Generated by Django 2.2.10 on 2022-01-21 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0242_auto_20220120_1148'),
        ('core', '0242_merge_20220120_0849'),
    ]

    operations = [
    ]
