# Generated by Django 2.2.10 on 2022-02-07 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0243_merge_20220121_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestacaoconta',
            name='recomendacoes',
            field=models.TextField(blank=True, default='', verbose_name='Recomendações para aprovação com ressalvas pela DRE'),
        ),
    ]
