# Generated by Django 2.2.10 on 2022-02-08 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0245_auto_20220208_0755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacao',
            name='categoria',
            field=models.CharField(choices=[('COMENTARIO_PC', 'Comentário na prestação de contas'), ('ELABORACAO_PC', 'Elaboração de PC'), ('ANALISE_PC', 'Análise de PC'), ('DEVOLUCAO_PC', 'Devolução de PC para ajustes'), ('APROVACAO_PC', 'Prestação de Contas Aprovada'), ('APROVACAO_RESSALVAS_PC', 'Prestação de Contas Aprovada com Ressalvas'), ('REPROVACAO_PC', 'Prestação de Contas Reprovada')], default='COMENTARIO_PC', max_length=15, verbose_name='Categoria'),
        ),
    ]
