# Generated by Django 2.2.10 on 2022-02-08 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0247_auto_20220208_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacao',
            name='categoria',
            field=models.CharField(choices=[('COMENTARIO_PC', 'Comentário na prestação de contas'), ('ELABORACAO_PC', 'Elaboração de PC'), ('ANALISE_PC', 'Análise de PC'), ('DEVOLUCAO_PC', 'Devolução de PC para ajustes'), ('APROVACAO_PC', 'Aprovação de PC'), ('APROVACAO_RESSALVAS_PC', 'Aprovação de PC com ressalvas'), ('REPROVACAO_PC', 'Reprovação de PC')], default='COMENTARIO_PC', max_length=40, verbose_name='Categoria'),
        ),
    ]
