# Generated by Django 2.2.10 on 2022-02-08 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0248_auto_20220208_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacao',
            name='descricao',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Descrição'),
        ),
    ]
