# Generated by Django 2.2.10 on 2022-02-09 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0249_auto_20220208_1052'),
        ('core', '0244_prestacaoconta_recomendacoes'),
    ]

    operations = [
    ]
