# Generated by Django 2.2.10 on 2022-02-10 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0249_auto_20220208_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='ata',
            name='justificativa_repasses_pendentes',
            field=models.TextField(blank=True, default='', verbose_name='Justificativas repasses pendentes'),
        ),
    ]
