# Generated by Django 2.2.10 on 2022-02-10 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0250_ata_justificativa_repasses_pendentes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ata',
            name='justificativa_repasses_pendentes',
            field=models.TextField(blank=True, default='', verbose_name='Justificativa repasses pendentes'),
        ),
    ]
