# Generated by Django 2.2.10 on 2022-02-14 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0250_merge_20220209_1512'),
        ('core', '0251_auto_20220210_1010'),
    ]

    operations = [
    ]
