# Generated by Django 2.2.10 on 2022-05-02 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0253_auto_20220223_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='analisecontaprestacaoconta',
            name='analise_prestacao_conta',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analises_de_extratos', to='core.AnalisePrestacaoConta'),
        ),
    ]
