# Generated by Django 2.2.10 on 2022-05-06 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0254_analisecontaprestacaoconta_analise_prestacao_conta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analisecontaprestacaoconta',
            name='analise_prestacao_conta',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analises_de_extratos', to='core.AnalisePrestacaoConta'),
        ),
        migrations.AlterField(
            model_name='analisecontaprestacaoconta',
            name='saldo_extrato',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='saldo do extrato'),
        ),
    ]
