# Generated by Django 2.2.10 on 2022-05-18 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0255_auto_20220506_1153'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CobrancaPrestacaoConta',
        ),
    ]
