# Generated by Django 2.2.10 on 2022-05-18 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0256_delete_cobrancaprestacaoconta'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentarioanaliseprestacao',
            name='notificado',
            field=models.BooleanField(default=False, verbose_name='Foi notificado?'),
        ),
        migrations.AddField(
            model_name='comentarioanaliseprestacao',
            name='notificado_em',
            field=models.DateField(blank=True, null=True, verbose_name='Notificado em'),
        ),
    ]
