# Generated by Django 2.2.10 on 2022-06-08 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0257_auto_20220518_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='associacao',
            name='status_valores_reprogramados',
            field=models.CharField(choices=[('NAO_FINALIZADO', 'Não finalizado'), ('EM_CONFERENCIA_DRE', 'Em conferência DRE'), ('EM_CORRECAO_UE', 'Em correção UE'), ('VALORES_CORRETOS', 'Valores corretos')], default='VALORES_CORRETOS', max_length=20, verbose_name='Status dos valores reprogramados'),
        ),
    ]
