# Generated by Django 2.2.10 on 2022-06-07 13:40

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0257_auto_20220518_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametros',
            name='texto_pagina_suporte_dre',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Texto da página de suporte (DRE)'),
        ),
        migrations.AddField(
            model_name='parametros',
            name='texto_pagina_suporte_sme',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Texto da página de suporte (SME)'),
        ),
    ]
