# Generated by Django 2.2.10 on 2022-06-13 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0258_associacao_status_valores_reprogramados'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuncValoresReprogramadosDRE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '[DRE] Valor Reprogramado',
                'verbose_name_plural': '[DRE] Valores Reprogramados',
                'permissions': (('access_valores_reprogramados_dre', '[DRE] Pode acessar Valores Reprogramados.'), ('change_valores_reprogramados_dre', '[DRE] Pode atualizar Valores Reprogramados.')),
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
