# Generated by Django 2.2.10 on 2022-06-13 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0259_funcdresuporteunidades_funcsmesuporteunidades'),
        ('core', '0259_funcvaloresreprogramadosdre'),
    ]

    operations = [
    ]
