# Generated by Django 2.2.10 on 2022-06-21 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dre', '0041_merge_20220613_1532'),
        ('core', '0260_merge_20220613_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestacaoconta',
            name='consolidado_dre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prestacoes_de_conta_do_consolidado_dre', to='dre.ConsolidadoDRE'),
        ),
        migrations.AddField(
            model_name='prestacaoconta',
            name='publicada',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Publicada'),
        ),
    ]
