# Generated by Django 2.2.10 on 2022-06-23 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0260_merge_20220613_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuncSmeExtracaoDeDados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '[SME] Extração de dados',
                'verbose_name_plural': '[SME] Extração de dados',
                'permissions': (('access_extracao_de_dados_sme', '[SME] Pode acessar Extração de dados da SME.'),),
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
