# Generated by Django 2.2.10 on 2022-06-23 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0261_funcsmeextracaodedados'),
        ('core', '0261_auto_20220621_1042'),
    ]

    operations = [
    ]
