# Generated by Django 2.2.10 on 2022-07-12 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0263_valoresreprogramados'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='valoresreprogramados',
            unique_together=set(),
        ),
    ]
