# Generated by Django 2.2.10 on 2022-07-18 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0264_auto_20220712_1436'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='funcuecreditosdaescola',
            options={'default_permissions': (), 'managed': False, 'permissions': (('access_receita', '[UE] Pode acessar Créditos da Escola.'), ('access_valores_reprogramados_ue', '[UE] Pode acessar Valores Reprogramados da Escola.'), ('add_receita', '[UE] Pode incluir Créditos da Escola.'), ('change_receita', '[UE] Pode editar Créditos da Escola.'), ('delete_receita', '[UE] Pode excluir Créditos da Escola.')), 'verbose_name': '[UE] Créditos da Escola', 'verbose_name_plural': '[UE] Créditos da Escola'},
        ),
    ]
