# Generated by Django 2.2.10 on 2022-07-18 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0265_auto_20220718_0803'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuncValoresReprogramadosUE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '[UE] Valor Reprogramado',
                'verbose_name_plural': '[UE] Valores Reprogramados',
                'permissions': (('access_valores_reprogramados_ue', '[UE] Pode acessar Valores Reprogramados.'), ('change_valores_reprogramados_ue', '[UE] Pode atualizar Valores Reprogramados.')),
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.AlterModelOptions(
            name='funcuecreditosdaescola',
            options={'default_permissions': (), 'managed': False, 'permissions': (('access_receita', '[UE] Pode acessar Créditos da Escola.'), ('add_receita', '[UE] Pode incluir Créditos da Escola.'), ('change_receita', '[UE] Pode editar Créditos da Escola.'), ('delete_receita', '[UE] Pode excluir Créditos da Escola.')), 'verbose_name': '[UE] Créditos da Escola', 'verbose_name_plural': '[UE] Créditos da Escola'},
        ),
    ]
