# Generated by Django 2.2.10 on 2022-08-08 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0266_auto_20220718_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestacaoconta',
            name='consolidado_dre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prestacoes_de_conta_do_consolidado_dre', to='dre.ConsolidadoDRE'),
        ),
    ]
