# Generated by Django 2.2.10 on 2022-07-22 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0266_auto_20220718_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoacertolancamento',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='tipoacertolancamento',
            name='categoria',
            field=models.CharField(choices=[('CATEGORIZAR', 'Categorizar'), ('DEVOLUCAO', 'Devolução ao tesouro'), ('EDICAO_LANCAMENTO', 'Edição do lançamento'), ('EXCLUSAO_LANCAMENTO', 'Exclusão do lançamento'), ('AJUSTES_EXTERNOS', 'Ajustes externos'), ('SOLICITACAO_ESCLARECIMENTO', 'Solicitação de esclarecimento')], default='CATEGORIZAR', max_length=35, verbose_name='Categoria'),
        ),
    ]
