# Generated by Django 2.2.10 on 2022-07-25 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0268_auto_20220725_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoacertodocumento',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='tipoacertodocumento',
            name='categoria',
            field=models.CharField(choices=[('INCLUSAO_CREDITO', 'Inclusão de crédito'), ('INCLUSAO_GASTO', 'Inclusão de gasto'), ('AJUSTES_EXTERNOS', 'Ajustes externos'), ('SOLICITACAO_ESCLARECIMENTO', 'Solicitação de esclarecimento')], default='SOLICITACAO_ESCLARECIMENTO', max_length=35, verbose_name='Categoria'),
        ),
    ]
