# Generated by Django 2.2.10 on 2022-08-12 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0268_auto_20220810_0919'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnaliseValorReprogramadoPrestacaoConta',
        ),
    ]
