# Generated by Django 2.2.10 on 2022-09-05 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0269_delete_analisevalorreprogramadoprestacaoconta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestacaoconta',
            name='devolucao_tesouro',
        ),
    ]
