# Generated by Django 2.2.10 on 2022-08-03 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0270_auto_20220803_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='analiselancamentoprestacaoconta',
            name='justificativa',
            field=models.TextField(blank=True, default=None, max_length=300, null=True, verbose_name='Justificativa'),
        ),
        migrations.AddField(
            model_name='analiselancamentoprestacaoconta',
            name='status_realizacao',
            field=models.CharField(blank=True, choices=[('PENDENTE', 'Pendente'), ('REALIZADO', 'Realizado'), ('JUSTIFICADO', 'Justificado')], default=None, max_length=15, null=True, verbose_name='Status de realização'),
        ),
    ]
