# Generated by Django 2.2.10 on 2022-08-03 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0271_auto_20220803_1042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipoacertolancamento',
            name='justificativa',
        ),
        migrations.RemoveField(
            model_name='tipoacertolancamento',
            name='status_realizacao',
        ),
        migrations.AlterField(
            model_name='analiselancamentoprestacaoconta',
            name='resultado',
            field=models.CharField(choices=[('CORRETO', 'Lançamento Correto'), ('AJUSTE', 'Ajuste necessário')], default='CORRETO', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='analiselancamentoprestacaoconta',
            name='tipo_lancamento',
            field=models.CharField(choices=[('CREDITO', 'Crédito'), ('GASTO', 'Gasto')], default='CREDITO', max_length=20, verbose_name='Tipo Lançamento'),
        ),
    ]
