# Generated by Django 2.2.10 on 2022-08-04 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0272_auto_20220803_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analiselancamentoprestacaoconta',
            name='status_realizacao',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('REALIZADO', 'Realizado'), ('JUSTIFICADO', 'Justificado')], default='PENDENTE', max_length=15, verbose_name='Status de realização'),
        ),
    ]
