# Generated by Django 2.2.10 on 2022-08-05 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0273_auto_20220804_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='analisedocumentoprestacaoconta',
            name='justificativa',
            field=models.TextField(blank=True, default=None, max_length=300, null=True, verbose_name='Justificativa'),
        ),
        migrations.AddField(
            model_name='analisedocumentoprestacaoconta',
            name='status_realizacao',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('REALIZADO', 'Realizado'), ('JUSTIFICADO', 'Justificado')], default='PENDENTE', max_length=15, verbose_name='Status de realização'),
        ),
    ]
