# Generated by Django 2.2.10 on 2022-08-08 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0274_auto_20220805_0808'),
        ('core', '0267_auto_20220808_0918'),
    ]

    operations = [
    ]
