# Generated by Django 2.2.10 on 2022-08-10 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0268_auto_20220810_0919'),
        ('core', '0275_merge_20220808_1132'),
    ]

    operations = [
    ]
