# Generated by Django 2.2.10 on 2022-08-15 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0269_delete_analisevalorreprogramadoprestacaoconta'),
        ('core', '0276_merge_20220810_1442'),
    ]

    operations = [
    ]
