# Generated by Django 2.2.10 on 2022-08-19 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0051_auto_20220516_1443'),
        ('receitas', '0046_auto_20220328_1506'),
        ('core', '0277_merge_20220815_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='analisedocumentoprestacaoconta',
            name='despesa_incluida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analise_de_documento_que_incluiu_a_despesa', to='despesas.Despesa'),
        ),
        migrations.AddField(
            model_name='analisedocumentoprestacaoconta',
            name='esclarecimentos',
            field=models.TextField(blank=True, default=None, max_length=300, null=True, verbose_name='Esclarecimentos'),
        ),
        migrations.AddField(
            model_name='analisedocumentoprestacaoconta',
            name='receita_incluida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analise_de_documento_que_incluiu_a_receita', to='receitas.Receita'),
        ),
    ]
