# Generated by Django 2.2.10 on 2022-08-22 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0277_merge_20220815_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='analiselancamentoprestacaoconta',
            name='devolucao_tesouro_atualizada',
            field=models.BooleanField(default=False, verbose_name='Devolução ao Tesouro Atualizada?'),
        ),
    ]
