# Generated by Django 2.2.10 on 2022-08-23 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0278_auto_20220819_0735'),
        ('core', '0278_analiselancamentoprestacaoconta_devolucao_tesouro_atualizada'),
    ]

    operations = [
    ]
