# Generated by Django 2.2.10 on 2022-09-09 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0270_remove_prestacaoconta_devolucao_tesouro'),
        ('core', '0281_prestacaoconta_justificativa_pendencia_realizacao'),
    ]

    operations = [
    ]
