# Generated by Django 2.2.10 on 2022-09-21 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0282_merge_20220909_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='analiseprestacaoconta',
            name='arquivo_pdf_apresentacao_apos_acertos',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Relatório em PDF de apresentação após acertos'),
        ),
        migrations.AddField(
            model_name='analiseprestacaoconta',
            name='arquivo_pdf_apresentacao_apos_acertos_criado_em',
            field=models.DateTimeField(null=True, verbose_name='Arquivo pdf apresentação após acertos gerado em'),
        ),
        migrations.AddField(
            model_name='analiseprestacaoconta',
            name='status_versao_apresentacao_apos_acertos',
            field=models.CharField(choices=[('NAO_GERADO', 'Não gerado'), ('EM_PROCESSAMENTO', 'Em processamento'), ('CONCLUIDO', 'Geração concluída')], default='NAO_GERADO', max_length=20, verbose_name='Status da geração do documento de apresentação após acertos'),
        ),
        migrations.AddField(
            model_name='analiseprestacaoconta',
            name='versao_pdf_apresentacao_apos_acertos',
            field=models.CharField(choices=[('-', '-'), ('FINAL', 'final'), ('RASCUNHO', 'rascunho')], default='-', max_length=20, verbose_name='Versão do documento de apresentação após acertos'),
        ),
        migrations.AlterField(
            model_name='analiseprestacaoconta',
            name='arquivo_pdf',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Relatório em PDF de solicitação de acertos'),
        ),
        migrations.AlterField(
            model_name='analiseprestacaoconta',
            name='arquivo_pdf_criado_em',
            field=models.DateTimeField(null=True, verbose_name='Arquivo pdf de solicitação de acertos gerado em'),
        ),
        migrations.AlterField(
            model_name='analiseprestacaoconta',
            name='status_versao',
            field=models.CharField(choices=[('NAO_GERADO', 'Não gerado'), ('EM_PROCESSAMENTO', 'Em processamento'), ('CONCLUIDO', 'Geração concluída')], default='NAO_GERADO', max_length=20, verbose_name='Status da geração do documento de solicitação de acertos'),
        ),
        migrations.AlterField(
            model_name='analiseprestacaoconta',
            name='versao',
            field=models.CharField(choices=[('-', '-'), ('FINAL', 'final'), ('RASCUNHO', 'rascunho')], default='-', max_length=20, verbose_name='Versão do documento de solicitação de acertos'),
        ),
    ]
