# Generated by Django 2.2.10 on 2022-09-26 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0283_auto_20220921_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaoacertolancamento',
            name='copiado',
            field=models.BooleanField(default=False, verbose_name='Solicitação copiada ?'),
        ),
    ]
