# Generated by Django 2.2.10 on 2022-09-26 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0283_auto_20220921_0940'),
        ('core', '0271_auto_20220923_1525'),
    ]

    operations = [
    ]
