# Generated by Django 2.2.10 on 2022-09-28 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0284_solicitacaoacertolancamento_copiado'),
        ('core', '0284_merge_20220926_1126'),
    ]

    operations = [
    ]
