# Generated by Django 2.2.10 on 2022-09-29 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0285_merge_20220928_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaoacertodocumento',
            name='copiado',
            field=models.BooleanField(default=False, verbose_name='Solicitação copiada ?'),
        ),
    ]
