# Generated by Django 2.2.10 on 2022-10-06 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0286_solicitacaoacertodocumento_copiado'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuncSmeAnaliseRelatoriosConsolidados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '[SME] Análise de Relatório Consolidado',
                'verbose_name_plural': '[SME] Análises de Relatórios Consolidados',
                'permissions': (('access_analise_relatorios_consolidados_sme', '[SME] Pode acessar a Análise de Relatórios Consolidados.'),),
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
