# Generated by Django 2.2.10 on 2022-10-05 08:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0286_solicitacaoacertodocumento_copiado'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoDevolucaoAoTesouro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alterado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('devolucao_total', models.BooleanField(default=True, verbose_name='Devolução total?')),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Valor')),
                ('motivo', models.TextField(blank=True, max_length=600, null=True, verbose_name='Motivo')),
                ('solicitacao_acerto_lancamento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacao_devolucao_ao_tesouro', to='core.SolicitacaoAcertoLancamento')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes_devolucoes_ao_tesouro_do_tipo', to='core.TipoDevolucaoAoTesouro')),
            ],
            options={
                'verbose_name': 'Solicitação de Devolução ao Tesouro',
                'verbose_name_plural': '16.8) Solicitações de Devolução ao Tesouro',
            },
        ),
    ]
