# Generated by Django 2.2.10 on 2022-10-06 13:48

from django.db import migrations


def migrar_solicitacoes_devolucao_tesouro(apps, schema_editor):
    model_solicitacao_acerto_lancamento = apps.get_model('core', 'SolicitacaoAcertoLancamento')
    model_solicitacao_devolucao_ao_tesouro = apps.get_model('core', 'SolicitacaoDevolucaoAoTesouro')
    solicitacoes_a_migrar = model_solicitacao_acerto_lancamento.objects.filter(devolucao_ao_tesouro__isnull=False).all()
    for solicitacao in solicitacoes_a_migrar:
        model_solicitacao_devolucao_ao_tesouro.objects.create(
            solicitacao_acerto_lancamento=solicitacao,
            tipo=solicitacao.devolucao_ao_tesouro.tipo,
            devolucao_total=solicitacao.devolucao_ao_tesouro.devolucao_total,
            valor=solicitacao.devolucao_ao_tesouro.valor,
            motivo=f'{solicitacao.devolucao_ao_tesouro.motivo} **migrado',
        )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0287_solicitacaodevolucaoaotesouro'),
    ]

    operations = [
        migrations.RunPython(migrar_solicitacoes_devolucao_tesouro, reverse_code=migrations.RunPython.noop)
    ]
