# Generated by Django 2.2.10 on 2022-10-10 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0287_documentoadicional'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentoadicional',
            options={'verbose_name': 'Documento adicional', 'verbose_name_plural': '19.0) Documentos Adicionais'},
        ),
    ]
