# Generated by Django 2.2.10 on 2022-10-10 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0288_auto_20221010_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentoadicional',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Arquivo'),
        ),
    ]
