# Generated by Django 2.2.10 on 2022-10-20 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0288_migra_solicitacoes_dev_tesouro'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipodocumentoprestacaoconta',
            name='e_relacao_bens',
            field=models.BooleanField(default=False, verbose_name='O documento é uma Relação de Bens?'),
        ),
        migrations.AlterField(
            model_name='tipodocumentoprestacaoconta',
            name='documento_por_conta',
            field=models.BooleanField(default=False, verbose_name='É um documento por tipo de conta?'),
        ),
    ]
