# Generated by Django 2.2.10 on 2022-10-10 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0289_auto_20221010_0812'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DocumentoAdicional',
        ),
    ]
