# Generated by Django 2.2.10 on 2022-11-07 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0289_auto_20221020_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaoacertolancamento',
            name='esclarecimentos',
            field=models.TextField(blank=True, default=None, max_length=300, null=True, verbose_name='Esclarecimentos'),
        ),
        migrations.AddField(
            model_name='solicitacaoacertolancamento',
            name='justificativa',
            field=models.TextField(blank=True, default=None, max_length=300, null=True, verbose_name='Justificativa'),
        ),
        migrations.AddField(
            model_name='solicitacaoacertolancamento',
            name='status_realizacao',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('REALIZADO', 'Realizado'), ('JUSTIFICADO', 'Justificado')], default='PENDENTE', max_length=15, verbose_name='Status de realização'),
        ),
    ]
