# Generated by Django 2.2.10 on 2022-10-11 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0290_delete_documentoadicional'),
        ('core', '0287_funcsmeanaliserelatoriosconsolidados'),
    ]

    operations = [
    ]
