# Generated by Django 2.2.10 on 2022-10-18 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0291_merge_20221011_0826'),
        ('core', '0288_migra_solicitacoes_dev_tesouro'),
    ]

    operations = [
    ]
