# Generated by Django 2.2.10 on 2022-10-21 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0292_merge_20221018_1103'),
        ('core', '0289_auto_20221020_1416'),
    ]

    operations = [
    ]
