# Generated by Django 2.2.10 on 2022-11-23 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0293_auto_20221122_0937'),
        ('core', '0293_auto_20221121_0857'),
    ]

    operations = [
    ]
