# Generated by Django 2.2.10 on 2022-10-21 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0289_auto_20221020_1416'),
        ('core', '0293_auto_20221020_1203'),
    ]

    operations = [
    ]
