# Generated by Django 2.2.10 on 2022-10-25 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0293_auto_20221020_1203'),
        ('core', '0293_merge_20221021_0947'),
    ]

    operations = [
    ]
