# Generated by Django 2.2.10 on 2022-11-23 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0294_merge_20221123_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analisedocumentoprestacaoconta',
            name='despesa_incluida',
        ),
        migrations.RemoveField(
            model_name='analisedocumentoprestacaoconta',
            name='esclarecimentos',
        ),
        migrations.RemoveField(
            model_name='analisedocumentoprestacaoconta',
            name='justificativa',
        ),
        migrations.RemoveField(
            model_name='analisedocumentoprestacaoconta',
            name='receita_incluida',
        ),
        migrations.AlterField(
            model_name='analisedocumentoprestacaoconta',
            name='status_realizacao',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('REALIZADO', 'Realizado'), ('JUSTIFICADO', 'Justificado'), ('REALIZADO_JUSTIFICADO', 'Realizado e justificado'), ('REALIZADO_PARCIALMENTE', 'Realizado parcialmente'), ('REALIZADO_JUSTIFICADO_PARCIALMENTE', 'Realizado e justificado parcialmente')], default='PENDENTE', max_length=15, verbose_name='Status de realização'),
        ),
    ]
