# Generated by Django 2.2.10 on 2022-10-21 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0293_merge_20221021_0947'),
        ('core', '0294_merge_20221021_0820'),
    ]

    operations = [
    ]
