# Generated by Django 2.2.10 on 2022-10-27 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0294_merge_20221025_0944'),
        ('core', '0294_auto_20221027_0836'),
    ]

    operations = [
    ]
