# Generated by Django 2.2.10 on 2022-10-31 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0295_merge_20221021_1024'),
        ('core', '0295_merge_20221027_1448'),
    ]

    operations = [
    ]
