# Generated by Django 2.2.10 on 2022-11-16 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0297_auto_20221103_1751'),
        ('core', '0292_auto_20221110_1451'),
    ]

    operations = [
    ]
