# Generated by Django 2.2.10 on 2023-01-05 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0298_auto_20221123_1549'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='funcdreacompanhamentodepcs',
            options={'default_permissions': (), 'managed': False, 'permissions': (('access_acompanhamento_pcs_dre', '[DRE] Pode acessar Acompanhamento de PCs.'), ('change_acompanhamento_pcs_dre', '[DRE] Pode atualizar Acompanhamento de PCs.')), 'verbose_name': '[DRE] Acompanhamento de PCs', 'verbose_name_plural': '[DRE] Acompanhamento de PCs'},
        ),
    ]
