# Generated by Django 2.2.10 on 2023-01-21 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0299_auto_20230105_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacao',
            name='categoria',
            field=models.CharField(choices=[('COMENTARIO_PC', 'Comentário na prestação de contas'), ('ELABORACAO_PC', 'Elaboração de PC'), ('ANALISE_PC', 'Análise de PC'), ('DEVOLUCAO_PC', 'Devolução de PC para ajustes'), ('APROVACAO_PC', 'Aprovação de PC'), ('APROVACAO_RESSALVAS_PC', 'Aprovação de PC com ressalvas'), ('REPROVACAO_PC', 'Reprovação de PC'), ('ERRO_AO_CONCLUIR_PC', 'Erro ao concluir PC')], default='COMENTARIO_PC', max_length=40, verbose_name='Categoria'),
        ),
    ]
