# Generated by Django 2.2.10 on 2022-11-28 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0300_auto_20221124_1418'),
        ('core', '0298_auto_20221123_1549'),
    ]

    operations = [
    ]
