# Generated by Django 2.2.10 on 2023-01-23 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0301_parametros_tempo_aguardar_conclusao_pc'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacao',
            name='periodo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes_do_periodo', to='core.Periodo', verbose_name='período'),
        ),
    ]
