# Generated by Django 2.2.10 on 2023-01-25 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0302_notificacao_periodo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametros',
            name='tempo_aguardar_conclusao_pc',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Quanto tempo deve-se aguardar a conclusão da PC (segundos)?'),
        ),
    ]
