# Generated by Django 2.2.10 on 2023-01-19 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0299_auto_20230105_1110'),
        ('core', '0302_auto_20221129_1118'),
    ]

    operations = [
    ]
