# Generated by Django 2.2.10 on 2023-01-27 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0303_auto_20230125_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametros',
            name='tempo_aguardar_conclusao_pc',
            field=models.PositiveSmallIntegerField(default=120, verbose_name='Quanto tempo deve-se aguardar a conclusão da PC (segundos)?'),
        ),
    ]
