# Generated by Django 2.2.10 on 2023-03-06 15:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0305_auto_20230127_0807'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferenciaEol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alterado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('eol_transferido', models.CharField(help_text='É o código eol que será transferido para a nova unidade.', max_length=6, verbose_name='EOL a ser transferido')),
                ('eol_historico', models.CharField(help_text='É o código que será usado para o histórico da unidade que usava anteriormente o condigo transferido.', max_length=6, verbose_name='EOL usado para o histórico')),
                ('tipo_nova_unidade', models.CharField(choices=[('ADM', 'ADM'), ('DRE', 'DRE'), ('IFSP', 'IFSP'), ('CMCT', 'CMCT'), ('CECI', 'CECI'), ('CEI', 'CEI'), ('CEMEI', 'CEMEI'), ('CIEJA', 'CIEJA'), ('EMEBS', 'EMEBS'), ('EMEF', 'EMEF'), ('EMEFM', 'EMEFM'), ('EMEI', 'EMEI'), ('CEU', 'CEU'), ('CEU CEI', 'CEU CEI'), ('CEU EMEF', 'CEU EMEF'), ('CEU EMEI', 'CEU EMEI'), ('CEU CEMEI', 'CEU CEMEI'), ('CEI DIRET', 'CEI DIRET')], default='CEMEI', help_text='Tipo da nova unidade que receberá o código transferido.', max_length=10)),
                ('data_inicio_atividades', models.DateField(help_text='Data de início das atividades da nova unidade.', verbose_name='Data de início das atividades')),
                ('status_processamento', models.CharField(choices=[('PENDENTE', 'Pendente'), ('SUCESSO', 'Sucesso'), ('ABORTADO', 'Abortado'), ('ERRO', 'Erro'), ('PROCESSANDO', 'Processando...')], default='PENDENTE', help_text='Status do processamento da transferência.', max_length=20, verbose_name='Status do processamento')),
                ('log_execucao', models.TextField(blank=True, help_text='Log de execução da transferência.', null=True, verbose_name='Log de execução')),
                ('tipo_conta_transferido', models.ForeignKey(help_text='Tipo de conta que será transferido para a nova unidade.', on_delete=django.db.models.deletion.PROTECT, to='core.TipoConta')),
            ],
            options={
                'verbose_name': 'Transferência de Código EOL',
                'verbose_name_plural': '99.9) Transferências de Código EOL',
            },
        ),
    ]
