# Generated by Django 2.2.10 on 2023-02-10 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0304_prestacaoconta_status_anterior_a_retificacao'),
        ('core', '0305_auto_20230127_0807'),
    ]

    operations = [
    ]
