# Generated by Django 2.2.10 on 2023-03-07 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0308_auto_20230223_0710'),
    ]

    operations = [
        migrations.AddField(
            model_name='analiselancamentoprestacaoconta',
            name='conciliacao_atualizada',
            field=models.BooleanField(default=False, verbose_name='Conciliação Atualizada?'),
        ),
    ]
