# Generated by Django 2.2.10 on 2023-03-06 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0310_falhageracaopc'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='falhageracaopc',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='falhageracaopc',
            name='prestacao_conta',
        ),
    ]
