# Generated by Django 2.2.10 on 2023-03-10 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0312_auto_20230307_1049'),
        ('core', '0309_analiselancamentoprestacaoconta_conciliacao_atualizada'),
    ]

    operations = [
    ]
