# Generated by Django 2.2.10 on 2023-03-17 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0313_merge_20230310_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arquivo',
            name='tipo_carga',
            field=models.CharField(choices=[('REPASSE_REALIZADO', 'Repasses realizados'), ('CARGA_PERIODO_INICIAL', 'Carga período inicial'), ('REPASSE_PREVISTO', 'Repasses previstos'), ('CARGA_ASSOCIACOES', 'Carga de Associações'), ('CARGA_USUARIOS', 'Carga de usuários'), ('CARGA_CENSO', 'Carga de censo'), ('CARGA_REPASSE_PREVISTO_SME', 'Repasses previstos sme'), ('CARGA_DEVOLUCAO_TESOURO', 'Devoluções ao Tesouro'), ('CARGA_MATERIAIS_SERVICOS', 'Especificações de Materiais e Serviços')], default='REPASSE_REALIZADO', max_length=35, verbose_name='tipo de carga'),
        ),
        migrations.AlterField(
            model_name='modelocarga',
            name='tipo_carga',
            field=models.CharField(choices=[('REPASSE_REALIZADO', 'Repasses realizados'), ('CARGA_PERIODO_INICIAL', 'Carga período inicial'), ('REPASSE_PREVISTO', 'Repasses previstos'), ('CARGA_ASSOCIACOES', 'Carga de Associações'), ('CARGA_USUARIOS', 'Carga de usuários'), ('CARGA_CENSO', 'Carga de censo'), ('CARGA_REPASSE_PREVISTO_SME', 'Repasses previstos sme'), ('CARGA_DEVOLUCAO_TESOURO', 'Devoluções ao Tesouro'), ('CARGA_MATERIAIS_SERVICOS', 'Especificações de Materiais e Serviços')], default='CARGA_ASSOCIACOES', max_length=35, unique=True, verbose_name='tipo de carga'),
        ),
        migrations.AlterField(
            model_name='tipoacertodocumento',
            name='categoria',
            field=models.CharField(choices=[('INCLUSAO_CREDITO', 'Inclusão de crédito'), ('INCLUSAO_GASTO', 'Inclusão de gasto'), ('AJUSTES_EXTERNOS', 'Ajustes externos'), ('SOLICITACAO_ESCLARECIMENTO', 'Solicitação de esclarecimento'), ('EDICAO_INFORMACAO', 'Edição de informação')], default='SOLICITACAO_ESCLARECIMENTO', max_length=35, verbose_name='Categoria'),
        ),
    ]
