# Generated by Django 2.2.10 on 2023-03-17 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0314_auto_20230317_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoacertodocumento',
            name='categoria',
            field=models.CharField(choices=[('INCLUSAO_CREDITO', 'Inclusão de crédito'), ('INCLUSAO_GASTO', 'Inclusão de gasto'), ('EDICAO_INFORMACAO', 'Edição de informação'), ('AJUSTES_EXTERNOS', 'Ajustes externos'), ('SOLICITACAO_ESCLARECIMENTO', 'Solicitação de esclarecimento')], default='SOLICITACAO_ESCLARECIMENTO', max_length=35, verbose_name='Categoria'),
        ),
    ]
