# Generated by Django 2.2.28 on 2023-03-22 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0315_auto_20230317_1028'),
        ('core', '0307_transferenciaeol_cnpj_nova_associacao'),
    ]

    operations = [
    ]
