# Generated by Django 2.2.10 on 2023-03-21 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0315_auto_20230317_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='analisedocumentoprestacaoconta',
            name='informacao_conciliacao_atualizada',
            field=models.BooleanField(default=False, verbose_name='Informação de Conciliação Atualizada?'),
        ),
    ]
