# Generated by Django 2.2.10 on 2023-03-21 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0316_analisedocumentoprestacaoconta_informacao_conciliacao_atualizada'),
    ]

    operations = [
        migrations.AddField(
            model_name='observacaoconciliacao',
            name='justificativa_original',
            field=models.TextField(blank=True, max_length=600, null=True, verbose_name='Observações da conciliação original'),
        ),
    ]
