# Generated by Django 2.2.10 on 2023-03-21 09:40

import logging

from django.db import migrations

logger = logging.getLogger(__name__)

def atualiza_justificativa_original_com_texto(apps, schema_editor):
    model_observacao_conciliacao = apps.get_model('core', 'ObservacaoConciliacao')
    observacoes = model_observacao_conciliacao.objects.filter(
        texto__isnull=False,
    ).all()
    logger.info(f'Atualizando justificativa_original de {observacoes.count()} observacoes de conciliacao')

    for obs in observacoes:
        obs.justificativa_original = obs.texto
        obs.save()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0317_observacaoconciliacao_justificativa_original'),
    ]

    operations = [
        migrations.RunPython(atualiza_justificativa_original_com_texto, reverse_code=migrations.RunPython.noop),
    ]
