# Generated by Django 2.2.10 on 2023-03-23 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0316_merge_20230322_1326'),
        ('core', '0318_update_justificativa_original_com_texto_na_observacao_conciliacao'),
    ]

    operations = [
    ]
