# Generated by Django 2.2.28 on 2023-03-30 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0319_merge_20230323_0705'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuncDreRetificacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '[DRE] Retificacao',
                'verbose_name_plural': '[DRE] Retificacoes',
                'permissions': (('access_retificacao_dre', '[DRE] Pode acessar Retificacao.'),),
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
