# Generated by Django 2.2.28 on 2023-03-29 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0319_merge_20230323_0705'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidade',
            name='observacao',
            field=models.CharField(blank=True, default='', help_text='Preencha este campo, se necessário, com informações relacionadas a unidade educacional.', max_length=255, null=True, verbose_name='Observação'),
        ),
    ]
