# Generated by Django 2.2.28 on 2023-03-30 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0320_funcdreretificacao'),
        ('core', '0320_unidade_observacao'),
    ]

    operations = [
    ]
