# Generated by Django 2.2.10 on 2023-04-06 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0321_merge_20230330_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='analiselancamentoprestacaoconta',
            name='analise_corrigida_via_admin_action',
            field=models.BooleanField(default=False, verbose_name='Análise corrigida via admin action?'),
        ),
        migrations.AddField(
            model_name='analiselancamentoprestacaoconta',
            name='analise_prestacao_conta_auxiliar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analises_de_lancamentos_auxiliar', to='core.AnalisePrestacaoConta'),
        ),
        migrations.AlterField(
            model_name='analiselancamentoprestacaoconta',
            name='analise_prestacao_conta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analises_de_lancamentos', to='core.AnalisePrestacaoConta'),
        ),
    ]
