# Generated by Django 2.2.28 on 2023-04-10 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0321_merge_20230330_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='analiselancamentoprestacaoconta',
            name='houve_considerados_corretos_automaticamente',
            field=models.BooleanField(default=False, verbose_name='Houve considerados corretos automaticamente?'),
        ),
    ]
