# Generated by Django 2.2.10 on 2023-04-18 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0322_auto_20230406_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='associacao',
            name='data_de_encerramento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de encerramento'),
        ),
    ]
