# Generated by Django 2.2.28 on 2023-04-18 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0322_auto_20230406_0851'),
        ('core', '0322_analiselancamentoprestacaoconta_houve_considerados_corretos_automaticamente'),
    ]

    operations = [
    ]
