# Generated by Django 2.2.28 on 2023-04-19 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0323_merge_20230418_0652'),
        ('core', '0323_merge_20230412_1315'),
    ]

    operations = [
    ]
