# Generated by Django 2.2.10 on 2023-04-18 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0323_associacao_data_de_encerramento'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametros',
            name='desconsiderar_associacoes_nao_iniciadas',
            field=models.BooleanField(default=False, verbose_name='Desconsiderar associações não iniciadas?'),
        ),
    ]
