# Generated by Django 2.2.10 on 2023-04-19 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0325_funcsmeencerrarassociacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associacao',
            name='data_de_encerramento',
            field=models.DateField(blank=True, help_text='A associação deixará de ser exibida nos períodos posteriores à data de encerramento informada.', null=True, verbose_name='Data de encerramento'),
        ),
    ]
