# Generated by Django 2.2.10 on 2023-04-20 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0323_merge_20230418_0652'),
        ('core', '0326_auto_20230419_1331'),
    ]

    operations = [
    ]
