# Generated by Django 2.2.28 on 2023-05-05 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0324_merge_20230419_0921'),
        ('core', '0329_auto_20230503_1452'),
    ]

    operations = [
    ]
