# Generated by Django 2.2.28 on 2023-05-08 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0330_merge_20230505_0816'),
        ('core', '0330_auto_20230505_1727'),
    ]

    operations = [
    ]
