# Generated by Django 2.2.28 on 2023-05-11 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0330_auto_20230511_0624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membroassociacao',
            name='cargo_educacao',
            field=models.CharField(blank=True, default='', max_length=160, null=True, verbose_name='Cargo Educação'),
        ),
    ]
