# Generated by Django 3.0.14 on 2023-05-17 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0331_auto_20230511_0626'),
        ('core', '0330_auto_20230510_0811'),
    ]

    operations = [
    ]
