# Generated by Django 2.2.10 on 2023-05-12 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0332_auto_20230508_0945'),
        ('core', '0331_auto_20230511_0626'),
    ]

    operations = [
    ]
