# Generated by Django 3.0.14 on 2023-06-05 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0332_merge_20230517_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='presenteata',
            name='presente',
            field=models.BooleanField(default=True, verbose_name='Presente ?'),
        ),
    ]
