# Generated by Django 3.0.14 on 2023-06-11 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0333_presenteata_presente'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PresenteAta',
            new_name='Participante',
        ),
    ]
