# Generated by Django 3.0.14 on 2023-05-22 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0333_merge_20230512_0943'),
        ('core', '0332_merge_20230517_1106'),
    ]

    operations = [
    ]
