# Generated by Django 3.1.14 on 2023-06-20 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0334_auto_20230611_2044'),
        ('core', '0334_merge_20230522_1856'),
    ]

    operations = [
    ]
