# Generated by Django 3.1.14 on 2023-07-04 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0335_auto_20230620_1250'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participante',
            options={'verbose_name': 'Participantes ata', 'verbose_name_plural': '17.0) Participantes ata'},
        ),
    ]
