# Generated by Django 3.1.14 on 2023-07-05 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0335_auto_20230620_1250'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuncDreGestaoUsuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '[DRE] Gestão de usuários',
                'verbose_name_plural': '[DRE] Gestão de usuários',
                'permissions': (('access_gestao_usuarios_dre', '[DRE] Pode acessar Gestão de Usuários da DRE.'), ('change_gestao_usuarios_dre', '[DRE] Pode atualizar Gestão de Usuários da DRE.')),
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='FuncSmeGestaoUsuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '[SME] Gestão de usuários',
                'verbose_name_plural': '[SME] Gestão de usuários',
                'permissions': (('access_gestao_usuarios_sme', '[SME] Pode acessar Gestão de Usuários da SME.'), ('change_gestao_usuarios_sme', '[SME] Pode atualizar Gestão de Usuários da SME.')),
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='FuncUeGestaoUsuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '[UE] Gestão de usuários',
                'verbose_name_plural': '[UE] Gestão de usuários',
                'permissions': (('access_gestao_usuarios_ue', '[UE] Pode acessar Gestão de Usuários da UE.'), ('change_gestao_usuarios_ue', '[UE] Pode atualizar Gestão de Usuários da UE.')),
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
