# Generated by Django 3.1.14 on 2023-07-04 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0335_auto_20230620_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='analisecontaprestacaoconta',
            name='observacao_solicitar_envio_do_comprovante_do_saldo_da_conta',
            field=models.TextField(blank=True, max_length=600, null=True, verbose_name='Observação solicitação de envio do comprovante do saldo da conta'),
        ),
        migrations.AddField(
            model_name='analisecontaprestacaoconta',
            name='solicitar_envio_do_comprovante_do_saldo_da_conta',
            field=models.BooleanField(default=False, verbose_name='Solicitar envio do comprovante do saldo da conta'),
        ),
    ]
