# Generated by Django 3.1.14 on 2023-07-03 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0335_merge_20230620_0643'),
        ('core', '0335_auto_20230620_1250'),
    ]

    operations = [
    ]
