# Generated by Django 3.1.14 on 2023-07-04 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0336_auto_20230704_1211'),
        ('core', '0336_auto_20230704_1443'),
    ]

    operations = [
    ]
