# Generated by Django 3.1.14 on 2023-07-10 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0337_merge_20230704_1640'),
        ('core', '0336_funcdregestaousuarios_funcsmegestaousuarios_funcuegestaousuarios'),
    ]

    operations = [
    ]
