# Generated by Django 3.1.14 on 2023-07-10 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0337_merge_20230704_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoconta',
            name='permite_inativacao',
            field=models.BooleanField(default=False, verbose_name='Permite inativação da conta?'),
        ),
    ]
