# Generated by Django 3.1.14 on 2023-07-13 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0338_merge_20230710_1039'),
        ('core', '0339_auto_20230711_1623'),
    ]

    operations = [
    ]
