# Generated by Django 3.1.14 on 2023-07-19 16:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0340_merge_20230713_0649'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoEncerramentoContaAssociacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alterado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('REJEITADA', 'Rejeitada'), ('APROVADA', 'Aprovada')], default='PENDENTE', max_length=15, verbose_name='status')),
                ('data_de_encerramento_na_agencia', models.DateField(blank=True, null=True, verbose_name='Data de encerramento na agência')),
                ('conta_associacao', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitacao_encerramento', to='core.contaassociacao')),
            ],
            options={
                'verbose_name': 'Solicitação de Encerramento de Conta de Associação',
                'verbose_name_plural': '07.4) Solicitações de Encerramento de Conta de Associação',
            },
        ),
    ]
