# Generated by Django 3.1.14 on 2023-07-18 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0340_merge_20230713_0649'),
        ('core', '0336_merge_20230703_1127'),
    ]

    operations = [
    ]
