# Generated by Django 3.1.14 on 2023-07-21 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0341_merge_20230718_0926'),
        ('core', '0341_taskcelery'),
    ]

    operations = [
    ]
