# Generated by Django 3.1.14 on 2023-07-25 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0342_motivorejeicaoencerramentocontaassociacao'),
        ('core', '0341_taskcelery'),
    ]

    operations = [
    ]
