# Generated by Django 3.1.14 on 2023-07-27 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0343_merge_20230725_0802'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuncDreRecebimentoDeNotificacoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '[DRE] Recebimento de notificações',
                'verbose_name_plural': '[DRE] Recebimento de notificações',
                'permissions': (('recebe_notificacao_encerramento_conta', '[DRE] Pode receber Notificação de Solicitação de Encerramento de Conta Bancária'),),
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='remetente',
            field=models.CharField(choices=[('SISTEMA', 'Sistema'), ('DRE', 'DRE'), ('ASSOCIACAO', 'Associação'), ('SME', 'SME')], default='SISTEMA', max_length=15, verbose_name='Remetente'),
        ),
    ]
