# Generated by Django 3.1.14 on 2023-08-04 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0341_merge_20230718_0926'),
        ('core', '0345_auto_20230801_1342'),
    ]

    operations = [
    ]
