# Generated by Django 3.1.14 on 2023-08-03 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0345_auto_20230801_1342'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuncUeMembrosDaAssociacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '[UE] Membro da Associação',
                'verbose_name_plural': '[UE] Membros da Associação',
                'permissions': (('access_membros_da_associacao', '[UE] Pode acessar Membros da Associação.'), ('change_membros_da_associacao', '[UE] Pode editar Membros da Associação.')),
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
