# Generated by Django 3.1.14 on 2023-08-09 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0346_funcuemembrosdaassociacao'),
        ('core', '0346_auto_20230804_1306'),
    ]

    operations = [
    ]
