# Generated by Django 3.1.14 on 2023-08-10 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0347_merge_20230809_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaoencerramentocontaassociacao',
            name='outros_motivos_rejeicao',
            field=models.TextField(blank=True, default='', verbose_name='Outros motivos para rejeição pela DRE'),
        ),
    ]
