# Generated by Django 3.1.14 on 2023-08-21 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0346_merge_20230804_0739'),
        ('core', '0349_auto_20230814_0827'),
    ]

    operations = [
    ]
