# Generated by Django 3.2.20 on 2023-09-06 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0349_auto_20230814_0827'),
    ]

    operations = [
        migrations.AddField(
            model_name='contaassociacao',
            name='data_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Data de início da conta'),
        ),
    ]
