# Generated by Django 3.2.20 on 2023-09-20 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0350_merge_20230821_1131'),
        ('core', '0351_update_data_de_inicio_da_conta_de_associacao'),
    ]

    operations = [
    ]
