# Generated by Django 3.2.21 on 2023-10-06 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0352_auto_20231006_0744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferenciaeol',
            name='tipo_conta_transferido',
            field=models.ForeignKey(blank=True, help_text='Tipo de conta que será transferido para a nova unidade. Deixe vazio, caso o comportamento escolhido seja copiar todas as contas.', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.tipoconta'),
        ),
    ]
