# Generated by Django 3.2.21 on 2023-10-10 08:54

from django.db import migrations, models
import sme_ptrf_apps.core.models.validators


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0354_transferenciaeol_copiar_membros'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associacao',
            name='cnpj',
            field=models.CharField(blank=True, default='', max_length=20, validators=[sme_ptrf_apps.core.models.validators.cnpj_validation], verbose_name='CNPJ'),
        ),
    ]
