# Generated by Django 3.2.21 on 2023-10-28 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0356_transferenciaeol_periodo_inicial_associacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='associacao',
            name='migrada_para_historico_de_membros',
            field=models.BooleanField(default=False, help_text='Identifica se esta associação foi migrada para o histórico de membros', verbose_name='Migrada para o histórico de membros?'),
        ),
    ]
