# Generated by Django 4.1.12 on 2023-10-27 09:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0356_transferenciaeol_periodo_inicial_associacao"),
    ]

    operations = [
        migrations.CreateModel(
            name="FuncDreExtracaoDeDados",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "[DRE] Extração de dados",
                "verbose_name_plural": "[DRE] Extração de dados",
                "permissions": (
                    (
                        "access_extracao_de_dados_dre",
                        "[DRE] Pode acessar Extração de dados da DRE.",
                    ),
                ),
                "managed": False,
                "default_permissions": (),
            },
        ),
    ]
