# Generated by Django 3.2.21 on 2023-10-20 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0352_merge_20230920_0810'),
        ('core', '0356_transferenciaeol_periodo_inicial_associacao'),
    ]

    operations = [
    ]
