# Generated by Django 3.2.21 on 2023-10-30 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0357_associacao_migrada_para_historico_de_membros'),
        ('core', '0357_funcdreextracaodedados'),
    ]

    operations = [
    ]
