# Generated by Django 4.1.12 on 2023-10-31 16:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import sme_ptrf_apps.core.models.validators
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0358_merge_20231030_0928"),
    ]

    operations = [
        migrations.CreateModel(
            name="RelatorioRelacaoBens",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "alterado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Alterado em"),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "periodo_referencia",
                    models.CharField(max_length=200, verbose_name="Período referência"),
                ),
                (
                    "periodo_data_inicio",
                    models.DateField(
                        blank=True, null=True, verbose_name="Período data início"
                    ),
                ),
                (
                    "periodo_data_fim",
                    models.DateField(
                        blank=True, null=True, verbose_name="Período data fim"
                    ),
                ),
                (
                    "conta",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Conta"
                    ),
                ),
                (
                    "tipo_unidade",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Tipo unidade",
                    ),
                ),
                (
                    "nome_unidade",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Nome unidade",
                    ),
                ),
                (
                    "nome_associacao",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Nome associação",
                    ),
                ),
                (
                    "cnpj_associacao",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=20,
                        null=True,
                        validators=[
                            sme_ptrf_apps.core.models.validators.cnpj_validation
                        ],
                        verbose_name="CNPJ da Associação",
                    ),
                ),
                (
                    "codigo_eol_associacao",
                    models.CharField(
                        max_length=6,
                        validators=[django.core.validators.MinLengthValidator(6)],
                        verbose_name="Código eol associação",
                    ),
                ),
                (
                    "nome_dre_associacao",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Nome associação",
                    ),
                ),
                (
                    "presidente_diretoria_executiva",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Presidente diretoria executiva",
                    ),
                ),
                (
                    "cargo_substituto_presidente_ausente",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Cargo substituto presidente ausente",
                    ),
                ),
                ("data_geracao", models.DateTimeField(verbose_name="Data geração")),
                (
                    "usuario",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Usuário"
                    ),
                ),
                (
                    "valor_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=8,
                        verbose_name="Valor total",
                    ),
                ),
                (
                    "relacao_bens",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.relacaobens",
                    ),
                ),
            ],
            options={
                "verbose_name": "Relatório Relação de bens",
                "verbose_name_plural": "09.3.1) Relatório Relações de bens",
            },
        ),
        migrations.CreateModel(
            name="ItemRelatorioRelacaoDeBens",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "alterado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Alterado em"),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "tipo_documento",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Tipo documento",
                    ),
                ),
                (
                    "numero_documento",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="Nº do documento",
                    ),
                ),
                ("data_documento", models.DateField(verbose_name="Data documento")),
                (
                    "especificacao_material",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Especificação material",
                    ),
                ),
                (
                    "numero_documento_incorporacao",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="Nº documento incorporação",
                    ),
                ),
                ("quantidade", models.PositiveIntegerField(verbose_name="Quantidade")),
                (
                    "valor_item",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=8,
                        verbose_name="Valor total",
                    ),
                ),
                (
                    "valor_rateio",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=8,
                        verbose_name="Valor total",
                    ),
                ),
                (
                    "relatorio",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bens",
                        to="core.relatoriorelacaobens",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
