# Generated by Django 4.1.12 on 2023-11-07 07:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0359_relatoriorelacaobens_itemrelatoriorelacaodebens"),
    ]

    operations = [
        migrations.AlterField(
            model_name="relatoriorelacaobens",
            name="nome_dre_associacao",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="Nome DRE associação",
            ),
        ),
    ]
