# Generated by Django 3.2.21 on 2023-11-07 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0357_merge_20231020_0831'),
        ('core', '0359_relatoriorelacaobens_itemrelatoriorelacaodebens'),
    ]

    operations = [
    ]
