# Generated by Django 4.1.12 on 2023-11-07 08:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0360_alter_relatoriorelacaobens_nome_dre_associacao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prestacaoconta",
            name="status",
            field=models.CharField(
                choices=[
                    ("NAO_APRESENTADA", "Não apresentada"),
                    ("NAO_RECEBIDA", "Não recebida"),
                    ("RECEBIDA", "Recebida"),
                    ("EM_ANALISE", "Em análise"),
                    ("DEVOLVIDA", "Devolvida para acertos"),
                    ("DEVOLVIDA_RETORNADA", "Apresentada após acertos"),
                    ("DEVOLVIDA_RECEBIDA", "Recebida após acertos"),
                    ("APROVADA", "Aprovada"),
                    ("APROVADA_RESSALVA", "Aprovada com ressalvas"),
                    ("REPROVADA", "Reprovada"),
                    ("EM_PROCESSAMENTO", "Em processamento"),
                    ("A_PROCESSAR", "A processar"),
                ],
                default="NAO_APRESENTADA",
                max_length=20,
                verbose_name="status",
            ),
        ),
    ]
