# Generated by Django 4.2.7 on 2023-11-16 07:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0361_alter_prestacaoconta_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="DadosDemonstrativoFinanceiro",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "alterado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Alterado em"),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "periodo_referencia",
                    models.CharField(
                        default="", max_length=10, verbose_name="Periodo de referencia"
                    ),
                ),
                (
                    "periodo_data_inicio",
                    models.DateField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="Periodo de data inicio",
                    ),
                ),
                (
                    "periodo_data_fim",
                    models.DateField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="Periodo de data fim",
                    ),
                ),
                (
                    "conta_associacao",
                    models.CharField(
                        default="", max_length=160, verbose_name="Conta associação"
                    ),
                ),
                (
                    "nome_associacao",
                    models.CharField(
                        default="", max_length=160, verbose_name="Nome da associação"
                    ),
                ),
                (
                    "cnpj_associacao",
                    models.CharField(
                        default="", max_length=20, verbose_name="Nome da associação"
                    ),
                ),
                (
                    "nome_dre_associacao",
                    models.CharField(
                        default="", max_length=160, verbose_name="Nome da dre"
                    ),
                ),
                (
                    "codigo_eol_associacao",
                    models.CharField(
                        default="000000",
                        max_length=6,
                        validators=[django.core.validators.MinLengthValidator(6)],
                        verbose_name="Codigo eol",
                    ),
                ),
                (
                    "banco",
                    models.CharField(
                        default="", max_length=50, verbose_name="Nome do banco"
                    ),
                ),
                (
                    "agencia",
                    models.CharField(
                        default="", max_length=15, verbose_name="Nº agência"
                    ),
                ),
                (
                    "conta",
                    models.CharField(
                        blank=True, default="", max_length=30, verbose_name="Nº conta"
                    ),
                ),
                (
                    "data_extrato",
                    models.DateField(
                        blank=True, default=None, null=True, verbose_name="Data extrato"
                    ),
                ),
                (
                    "saldo_extrato",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Saldo do extrato",
                    ),
                ),
                (
                    "conta_encerrada_em",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=50,
                        verbose_name="Conta encerrada em",
                    ),
                ),
                (
                    "total_creditos",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Total créditos",
                    ),
                ),
                (
                    "total_despesas_demonstradas",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Total despesas demonstradas",
                    ),
                ),
                (
                    "total_despesas_nao_demonstradas",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Total despesas não demonstradas",
                    ),
                ),
                (
                    "total_despesas_nao_demonstradas_periodos_anteriores",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Total despesas não demonstradas de periodos anteriores",
                    ),
                ),
                (
                    "justificativa_info_adicionais",
                    models.TextField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="Justificativa e informações adicionais",
                    ),
                ),
                (
                    "cargo_substituto_presidente_ausente",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=160,
                        null=True,
                        verbose_name="Cargo substituto presidente ausente",
                    ),
                ),
                (
                    "presidente_diretoria_executiva",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=160,
                        null=True,
                        verbose_name="Presidente da diretoria executiva",
                    ),
                ),
                (
                    "presidente_conselho_fiscal",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=160,
                        null=True,
                        verbose_name="Presidente do conselho fiscal",
                    ),
                ),
                (
                    "tipo_unidade",
                    models.CharField(
                        default="", max_length=50, verbose_name="Tipo unidade"
                    ),
                ),
                (
                    "nome_unidade",
                    models.CharField(
                        default="", max_length=160, verbose_name="Nome unidade"
                    ),
                ),
                (
                    "texto_rodape",
                    models.TextField(
                        blank=True, default=None, null=True, verbose_name="Texto rodapé"
                    ),
                ),
                (
                    "data_geracao",
                    models.DateField(
                        blank=True, default=None, null=True, verbose_name="Data geração"
                    ),
                ),
                (
                    "demonstrativo",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dados",
                        to="core.demonstrativofinanceiro",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dados Demonstrativo Financeiro",
                "verbose_name_plural": "20.0) Dados dos Demonstrativos Financeiros",
            },
        ),
        migrations.CreateModel(
            name="ItemResumoPorAcao",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "alterado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Alterado em"),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "acao_associacao",
                    models.CharField(
                        max_length=160, verbose_name="Nome da ação associação"
                    ),
                ),
                (
                    "total_geral",
                    models.BooleanField(
                        default=False, verbose_name="É registro de total geral ?"
                    ),
                ),
                (
                    "custeio_saldo_anterior",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Linha custeio saldo anterior",
                    ),
                ),
                (
                    "custeio_credito",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Linha custeio credito",
                    ),
                ),
                (
                    "custeio_despesa_realizada",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Linha custeio despesa realizada",
                    ),
                ),
                (
                    "custeio_despesa_nao_realizada",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Linha custeio despesa não realizada",
                    ),
                ),
                (
                    "custeio_saldo_reprogramado_proximo",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Linha custeio saldo reprogramado proximo periodo",
                    ),
                ),
                (
                    "custeio_despesa_nao_demostrada_outros_periodos",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Linha custeio despesa não demonstrada outros períodos",
                    ),
                ),
                (
                    "custeio_valor_saldo_bancario_custeio",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Linha custeio valor saldo bancario",
                    ),
                ),
                (
                    "livre_saldo_anterior",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Linha livre saldo anterior",
                    ),
                ),
                (
                    "livre_credito",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Linha livre credito",
                    ),
                ),
                (
                    "livre_saldo_reprogramado_proximo",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Linha livre saldo reprogramado proximo periodo",
                    ),
                ),
                (
                    "livre_valor_saldo_reprogramado_proximo_periodo",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Linha livre valor saldo reprogramado proximo periodo",
                    ),
                ),
                (
                    "capital_saldo_anterior",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Linha capital saldo anterior",
                    ),
                ),
                (
                    "capital_credito",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Linha capital credito",
                    ),
                ),
                (
                    "capital_despesa_realizada",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Linha capital despesa realizada",
                    ),
                ),
                (
                    "capital_despesa_nao_realizada",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Linha capital despesa não realizada",
                    ),
                ),
                (
                    "capital_saldo_reprogramado_proximo",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Linha capital saldo reprogramado proximo periodo",
                    ),
                ),
                (
                    "capital_despesa_nao_demostrada_outros_periodos",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Linha capital despesa não demonstrada outros periodos",
                    ),
                ),
                (
                    "capital_valor_saldo_bancario_capital",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Linha capital valor saldo bancario",
                    ),
                ),
                (
                    "total_valores",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Total valores",
                    ),
                ),
                (
                    "saldo_bancario",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Saldo bancario",
                    ),
                ),
                (
                    "dados_demonstrativo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens_resumo_por_acao",
                        to="core.dadosdemonstrativofinanceiro",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dados Demonstrativo Financeiro Item Resumo por Ação",
                "verbose_name_plural": "20.1) Dados dos Demonstrativos Financeiros Itens Resumo por Ação",
            },
        ),
        migrations.CreateModel(
            name="ItemDespesa",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "alterado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Alterado em"),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "categoria_despesa",
                    models.CharField(
                        choices=[
                            ("DEMONSTRADA", "Demonstrada"),
                            ("NAO_DEMONSTRADA", "Não Demonstrada"),
                            (
                                "NAO_DEMONSTRADA_PERIODO_ANTERIOR",
                                "Não demonstrada periodo anterior",
                            ),
                        ],
                        default="DEMONSTRADA",
                        max_length=50,
                        verbose_name="Categoria despesa",
                    ),
                ),
                (
                    "info_despesa",
                    models.CharField(
                        choices=[
                            ("NAO_GEROU_IMPOSTOS", "Despesa não gerou impostos"),
                            ("GEROU_IMPOSTOS", "Despesa gerou impostos"),
                            ("IMPOSTO_GERADO", "Imposto gerado"),
                        ],
                        default="NAO_GEROU_IMPOSTOS",
                        help_text="Informação se a despesa é uma geradora de impostos, um imposto ou uma despesa sem impostos",
                        max_length=50,
                        verbose_name="Informação despesa",
                    ),
                ),
                (
                    "uuid_despesa_referencia",
                    models.CharField(
                        default=None,
                        help_text="Referencia da despesa utilizada para gravação dos dados",
                        max_length=300,
                        null=True,
                        verbose_name="Uuid despesa",
                    ),
                ),
                (
                    "uuid_rateio_referencia",
                    models.CharField(
                        default=None,
                        help_text="Referencia do rateio utilizado para gravação dos dados",
                        max_length=300,
                        null=True,
                        verbose_name="Uuid rateio",
                    ),
                ),
                (
                    "razao_social",
                    models.CharField(
                        default=None,
                        max_length=300,
                        null=True,
                        verbose_name="Razão social",
                    ),
                ),
                (
                    "cnpj_cpf",
                    models.CharField(max_length=20, verbose_name="CNPJ ou CPF"),
                ),
                (
                    "tipo_documento",
                    models.CharField(
                        default=None,
                        max_length=160,
                        null=True,
                        verbose_name="Tipo documento",
                    ),
                ),
                (
                    "numero_documento",
                    models.CharField(
                        default=None,
                        max_length=100,
                        null=True,
                        verbose_name="Numero documento",
                    ),
                ),
                (
                    "data_documento",
                    models.DateField(
                        default=None, null=True, verbose_name="Data documento"
                    ),
                ),
                (
                    "nome_acao_documento",
                    models.CharField(
                        default=None,
                        max_length=300,
                        null=True,
                        verbose_name="Tipo documento",
                    ),
                ),
                (
                    "especificacao_material",
                    models.CharField(
                        default=None,
                        max_length=300,
                        null=True,
                        verbose_name="Especificacao material",
                    ),
                ),
                (
                    "tipo_despesa",
                    models.CharField(
                        default=None,
                        max_length=100,
                        null=True,
                        verbose_name="Tipo despesa",
                    ),
                ),
                (
                    "tipo_transacao",
                    models.CharField(
                        default=None,
                        max_length=200,
                        null=True,
                        verbose_name="Tipo transação",
                    ),
                ),
                (
                    "data_transacao",
                    models.DateField(
                        default=None, null=True, verbose_name="Data transacao"
                    ),
                ),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        null=True,
                        verbose_name="Valor",
                    ),
                ),
                (
                    "dados_demonstrativo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens_despesa",
                        to="core.dadosdemonstrativofinanceiro",
                    ),
                ),
                (
                    "despesas_impostos",
                    models.ManyToManyField(
                        blank=True,
                        related_name="despesa_geradora",
                        to="core.itemdespesa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dados Demonstrativo Financeiro Item de Despesa",
                "verbose_name_plural": "20.3) Dados dos Demonstrativos Financeiros Itens de Despesas",
            },
        ),
        migrations.CreateModel(
            name="ItemCredito",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "alterado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Alterado em"),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "tipo_receita",
                    models.CharField(
                        default=None,
                        max_length=160,
                        null=True,
                        verbose_name="Tipo receita",
                    ),
                ),
                (
                    "detalhamento",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=160,
                        null=True,
                        verbose_name="Detalhamento",
                    ),
                ),
                (
                    "nome_acao",
                    models.CharField(
                        default=None, max_length=160, null=True, verbose_name="Ação"
                    ),
                ),
                (
                    "data",
                    models.DateField(default=None, null=True, verbose_name="Data"),
                ),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        null=True,
                        verbose_name="Valor",
                    ),
                ),
                (
                    "receita_estornada",
                    models.BooleanField(default=False, verbose_name="É um estorno"),
                ),
                (
                    "data_estorno",
                    models.DateField(
                        blank=True, default=None, null=True, verbose_name="Data estorno"
                    ),
                ),
                (
                    "numero_documento_despesa",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=160,
                        null=True,
                        verbose_name="N documento despesa",
                    ),
                ),
                (
                    "motivos_estorno",
                    models.TextField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="Motivos para estorno",
                    ),
                ),
                (
                    "outros_motivos_estorno",
                    models.TextField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="Outros motivos para estorno",
                    ),
                ),
                (
                    "dados_demonstrativo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens_creditos",
                        to="core.dadosdemonstrativofinanceiro",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dados Demonstrativo Financeiro Item de Crédito",
                "verbose_name_plural": "20.2) Dados dos Demonstrativos Financeiros Itens de Créditos",
            },
        ),
    ]
