# Generated by Django 4.2.7 on 2023-11-16 13:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0362_dadosdemonstrativofinanceiro_itemresumoporacao_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemdespesa",
            name="valor_total",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=12,
                null=True,
                verbose_name="Valor Total",
            ),
        ),
    ]
