# Generated by Django 4.2.7 on 2023-11-23 08:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0360_merge_20231107_0759"),
        ("core", "0363_itemdespesa_valor_total"),
    ]

    operations = []
