# Generated by Django 4.2.7 on 2023-11-23 11:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0363_itemdespesa_valor_total"),
    ]

    operations = [
        migrations.AddField(
            model_name="parametros",
            name="permite_saldo_acoes_negativo",
            field=models.BooleanField(
                default=True, verbose_name="Permite saldo negativo em ações?"
            ),
        ),
    ]
