# Generated by Django 4.2.7 on 2023-12-05 07:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0364_merge_20231123_0801"),
        ("core", "0364_parametros_permite_saldo_acoes_negativo"),
    ]

    operations = []
