# Generated by Django 4.2.7 on 2023-12-21 15:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0364_parametros_permite_saldo_acoes_negativo"),
    ]

    operations = [
        migrations.AddField(
            model_name="demonstrativofinanceiro",
            name="arquivo_pdf_regerado",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="demonstrativofinanceiro",
            name="arquivo_pdf_substituido",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="",
                verbose_name="Relatório em PDF Substituido",
            ),
        ),
        migrations.AlterField(
            model_name="demonstrativofinanceiro",
            name="status",
            field=models.CharField(
                choices=[
                    ("EM_PROCESSAMENTO", "Em processamento"),
                    ("CONCLUIDO", "Geração concluída"),
                    ("A_PROCESSAR", "A processar"),
                ],
                default="CONCLUIDO",
                max_length=20,
                verbose_name="status",
            ),
        ),
        migrations.AlterField(
            model_name="relacaobens",
            name="status",
            field=models.CharField(
                choices=[
                    ("EM_PROCESSAMENTO", "Em processamento"),
                    ("CONCLUIDO", "Geração concluída"),
                    ("A_PROCESSAR", "A processar"),
                ],
                default="CONCLUIDO",
                max_length=20,
                verbose_name="status",
            ),
        ),
    ]
