# Generated by Django 4.2.7 on 2023-12-22 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0365_alter_demonstrativofinanceiro_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemrelatoriorelacaodebens",
            name="relatorio",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bens",
                to="core.relatoriorelacaobens",
            ),
        ),
        migrations.AlterField(
            model_name="prestacaoconta",
            name="status",
            field=models.CharField(
                choices=[
                    ("NAO_APRESENTADA", "Não apresentada"),
                    ("NAO_RECEBIDA", "Não recebida"),
                    ("RECEBIDA", "Recebida"),
                    ("EM_ANALISE", "Em análise"),
                    ("DEVOLVIDA", "Devolvida para acertos"),
                    ("DEVOLVIDA_RETORNADA", "Apresentada após acertos"),
                    ("DEVOLVIDA_RECEBIDA", "Recebida após acertos"),
                    ("APROVADA", "Aprovada"),
                    ("APROVADA_RESSALVA", "Aprovada com ressalvas"),
                    ("REPROVADA", "Reprovada"),
                    ("EM_PROCESSAMENTO", "Em processamento"),
                    ("A_PROCESSAR", "A processar"),
                    ("CALCULADA", "PC calculada. Gerando relatórios"),
                    ("DEVOLVIDA_CALCULADA", "PC calculada. Gerando relatórios"),
                ],
                default="NAO_APRESENTADA",
                max_length=20,
                verbose_name="status",
            ),
        ),
        migrations.AlterField(
            model_name="relatoriorelacaobens",
            name="relacao_bens",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.relacaobens",
            ),
        ),
    ]
