# Generated by Django 4.2.7 on 2023-12-21 15:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0365_demonstrativofinanceiro_arquivo_pdf_regerado_and_more"),
        ("core", "0365_merge_20231205_0759"),
    ]

    operations = []
