# Generated by Django 4.2.7 on 2023-12-26 13:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0366_alter_funcuerecebimentodenotificacoes_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificacao",
            name="categoria",
            field=models.CharField(
                choices=[
                    ("COMENTARIO_PC", "Comentário na prestação de contas"),
                    ("ELABORACAO_PC", "Elaboração de PC"),
                    ("ANALISE_PC", "Análise de PC"),
                    ("DEVOLUCAO_PC", "Devolução de PC para ajustes"),
                    ("APROVACAO_PC", "Aprovação de PC"),
                    ("APROVACAO_RESSALVAS_PC", "Aprovação de PC com ressalvas"),
                    ("REPROVACAO_PC", "Reprovação de PC"),
                    ("ERRO_AO_CONCLUIR_PC", "Erro ao concluir PC"),
                    ("DEVOLUCAO_CONSOLIDADO", "Devolução de relatório consolidado"),
                    (
                        "COMENTARIO_CONSOLIDADO_DRE",
                        "Comentário no relatório consolidado",
                    ),
                    ("ENCERRAMENTO_CONTA_BANCARIA", "Encerramento de Conta Bancária"),
                    ("GERACAO_ATA", "Geração de Ata"),
                ],
                default="COMENTARIO_PC",
                max_length=40,
                verbose_name="Categoria",
            ),
        ),
    ]
