# Generated by Django 4.2.7 on 2023-12-28 08:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0365_demonstrativofinanceiro_arquivo_pdf_regerado_and_more"),
        ("core", "0368_remove_itemdespesa_despesas_impostos_and_more"),
    ]

    operations = []
