# Generated by Django 4.2.7 on 2023-12-29 08:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0366_alter_itemrelatoriorelacaodebens_relatorio_and_more"),
        ("core", "0369_merge_20231228_0810"),
    ]

    operations = []
