# Generated by Django 4.2.7 on 2024-01-05 14:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0370_merge_20231229_0855"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dadosdemonstrativofinanceiro",
            options={
                "verbose_name": "Dados Demonstrativo Financeiro",
                "verbose_name_plural": "09.2.1) Dados dos Demonstrativos Financeiros",
            },
        ),
        migrations.AlterModelOptions(
            name="itemcredito",
            options={
                "verbose_name": "Dados Demonstrativo Financeiro Item de Crédito",
                "verbose_name_plural": "Dados dos Demonstrativos Financeiros Itens de Créditos",
            },
        ),
        migrations.AlterModelOptions(
            name="itemdespesa",
            options={
                "verbose_name": "Dados Demonstrativo Financeiro Item de Despesa",
                "verbose_name_plural": "Dados dos Demonstrativos Financeiros Itens de Despesas",
            },
        ),
        migrations.AlterModelOptions(
            name="itemresumoporacao",
            options={
                "verbose_name": "Dados Demonstrativo Financeiro Item Resumo por Ação",
                "verbose_name_plural": "Dados dos Demonstrativos Financeiros Itens Resumo por Ação",
            },
        ),
        migrations.AlterModelOptions(
            name="relatoriorelacaobens",
            options={
                "verbose_name": "Dados da Relação de bens",
                "verbose_name_plural": "09.3.1) Dados das Relações de bens",
            },
        ),
        migrations.AlterField(
            model_name="dadosdemonstrativofinanceiro",
            name="cnpj_associacao",
            field=models.CharField(
                default="", max_length=20, verbose_name="CNPJ da associação"
            ),
        ),
    ]
