# Generated by Django 4.2.7 on 2024-01-04 09:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0366_merge_20231221_1539"),
        ("core", "0370_merge_20231229_0855"),
    ]

    operations = []
