# Generated by Django 4.2.7 on 2024-01-18 09:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0371_alter_dadosdemonstrativofinanceiro_options_and_more"),
        ("core", "0371_merge_20240104_0947"),
    ]

    operations = []
