# Generated by Django 4.2.7 on 2024-02-12 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0372_ata_composicao"),
    ]

    operations = [
        migrations.AddField(
            model_name="ata",
            name="presidente_da_reuniao",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="presidente_participante_ata",
                to="core.participante",
            ),
        ),
        migrations.AddField(
            model_name="ata",
            name="secretario_da_reuniao",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="secretario_participante_ata",
                to="core.participante",
            ),
        ),
    ]
