# Generated by Django 4.2.10 on 2024-02-21 10:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0375_alter_ata_presidente_da_reuniao_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="analiseprestacaoconta",
            name="status_versao",
            field=models.CharField(
                choices=[
                    ("NAO_GERADO", "Não gerado"),
                    ("EM_PROCESSAMENTO", "Em processamento"),
                    ("FALHA_AO_GERAR", "Falha ao gerar"),
                    ("CONCLUIDO", "Geração concluída"),
                ],
                default="NAO_GERADO",
                max_length=20,
                verbose_name="Status da geração do documento de solicitação de acertos",
            ),
        ),
        migrations.AlterField(
            model_name="analiseprestacaoconta",
            name="status_versao_apresentacao_apos_acertos",
            field=models.CharField(
                choices=[
                    ("NAO_GERADO", "Não gerado"),
                    ("EM_PROCESSAMENTO", "Em processamento"),
                    ("FALHA_AO_GERAR", "Falha ao gerar"),
                    ("CONCLUIDO", "Geração concluída"),
                ],
                default="NAO_GERADO",
                max_length=20,
                verbose_name="Status da geração do documento de apresentação após acertos",
            ),
        ),
    ]
