# Generated by Django 4.2.7 on 2024-02-21 19:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0376_alter_analiseprestacaoconta_status_versao_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="parametros",
            name="desconsiderar_associacoes_nao_iniciadas",
        ),
    ]
