# Generated by Django 4.2.10 on 2024-03-05 07:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0372_merge_20240118_0929"),
        ("core", "0377_remove_parametros_desconsiderar_associacoes_nao_iniciadas"),
    ]

    operations = []
