# Generated by Django 4.2.7 on 2024-03-07 13:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0378_prestacaocontareprovadanaoapresentacao"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comentarioanaliseprestacao",
            options={
                "verbose_name": "Observação de análise de prestação de contas",
                "verbose_name_plural": "09.10) Observações de análise de prestações de contas",
            },
        ),
    ]
