# Generated by Django 4.2.10 on 2024-03-18 09:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0381_alter_notificacao_categoria"),
    ]

    operations = [
        migrations.AddField(
            model_name="arquivodownload",
            name="informacoes",
            field=models.TextField(blank=True, default="", verbose_name="Informações"),
        ),
    ]
