# Generated by Django 4.2.7 on 2024-03-22 08:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0378_merge_20240305_0752"),
        ("core", "0381_alter_notificacao_categoria"),
    ]

    operations = []
