# Generated by Django 4.2.10 on 2024-03-19 06:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0381_alter_notificacao_categoria"),
    ]

    operations = [
        migrations.AddField(
            model_name="processoassociacao",
            name="periodos",
            field=models.ManyToManyField(
                blank=True, related_name="processos", to="core.periodo"
            ),
        ),
    ]
