# Generated by Django 4.2.11 on 2024-03-22 15:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0382_arquivodownload_informacoes"),
        ("core", "0382_processoassociacao_periodos"),
    ]

    operations = []
