# Generated by Django 4.2.7 on 2024-04-04 09:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0383_merge_20240322_1517"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="funcsmepainelparametrizacoes",
            options={
                "default_permissions": (),
                "managed": False,
                "permissions": (
                    (
                        "access_painel_parametrizacoes",
                        "[SME] Pode acessar o Painel de parametrizações.",
                    ),
                    (
                        "change_painel_parametrizacoes",
                        "[SME] Pode atualizar o Painel de parametrizações ",
                    ),
                ),
                "verbose_name": "[SME] Painel de Parametrizacoes",
                "verbose_name_plural": "[SME] Painel de Parametrizacoes",
            },
        ),
    ]
