# Generated by Django 4.2.11 on 2024-04-04 07:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0382_merge_20240322_0845"),
        ("core", "0383_merge_20240322_1517"),
    ]

    operations = []
