# Generated by Django 4.2.11 on 2024-04-10 12:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0384_alter_funcsmepainelparametrizacoes_options"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FuncSmeFornecedores",
        ),
    ]
