# Generated by Django 4.2.7 on 2024-04-15 11:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0385_delete_funcsmefornecedores"),
    ]

    operations = [
        migrations.AddField(
            model_name="ata",
            name="pdf_gerado_previamente",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="O PDF já foi gerado previamente, foi apagado e precisa ser regerado quando editado/apagado",
                verbose_name="PDF gerado previamente",
            ),
        ),
    ]
