# Generated by Django 4.2.7 on 2024-04-15 11:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0387_alter_ata_pdf_gerado_previamente"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ata",
            name="pdf_gerado_previamente",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="O PDF já foi gerado e precisa ser regerado quando a ata é editada/apagada",
                verbose_name="PDF gerado previamente",
            ),
        ),
    ]
