# Generated by Django 4.2.7 on 2024-04-15 12:16

from django.db import migrations

def migrar_campo_pdf_gerado_previamente(apps, schema_editor):
    model_ata = apps.get_model('core', 'Ata')
    atas_com_pdf = model_ata.objects.exclude(arquivo_pdf='')
    for ata in atas_com_pdf:
        ata.pdf_gerado_previamente = True
        ata.save()
    

class Migration(migrations.Migration):
    dependencies = [
        ("core", "0388_alter_ata_pdf_gerado_previamente"),
    ]

    operations = [
        migrations.RunPython(migrar_campo_pdf_gerado_previamente, reverse_code=migrations.RunPython.noop)
    ]