# Generated by Django 4.2.7 on 2024-04-18 11:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0384_merge_20240404_0725"),
        ("core", "0389_migrar_campo_pdf_gerado_previamente"),
    ]

    operations = []
