# Generated by Django 4.2.7 on 2024-05-15 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0393_alter_arquivo_tipo_carga_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="arquivo",
            name="periodo",
            field=models.ForeignKey(
                blank=True,
                help_text="Período associado ao arquivo (opcional dependendo do tipo de carga)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.periodo",
                verbose_name="Período",
            ),
        ),
    ]
