# Generated by Django 4.2.11 on 2024-05-20 07:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0390_merge_20240418_1112"),
        ("core", "0394_alter_arquivo_periodo"),
    ]

    operations = []
