# Generated by Django 4.2.11 on 2024-06-06 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0395_arquivo_tipo_de_conta"),
        ("core", "0395_merge_20240520_0722"),
    ]

    operations = []
