# Generated by Django 4.2.11 on 2025-03-24 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0397_categoriapdde_acaopdde'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acaopdde',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.categoriapdde'),
        ),
    ]
