# Generated by Django 4.2.11 on 2025-03-10 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0397_categoriapdde_acaopdde"),
    ]

    operations = [
        migrations.AddField(
            model_name="previsaorepassesme",
            name="carga",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.arquivo",
            ),
        ),
    ]
