# Generated by Django 4.2.11 on 2025-03-11 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0398_previsaorepassesme_carga"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="previsaorepassesme",
            unique_together={("associacao", "periodo", "conta_associacao", "carga")},
        ),
    ]
