# Generated by Django 4.2.11 on 2025-03-13 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0399_alter_previsaorepassesme_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="FuncUePlanoAnualDeAtividade",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "[UE] Plano anual de atividade",
                "verbose_name_plural": "[UE] Plano anual de atividade",
                "permissions": (
                    ("access_paa", "[UE] Pode acessar Plano Anual de Atividade."),
                    ("change_paa", '[UE] Pode editar Plano Anual de Atividade".'),
                ),
                "managed": False,
                "default_permissions": (),
            },
        ),
    ]
