# Generated by Django 4.2.11 on 2025-03-24 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0398_alter_acaopdde_categoria'),
        ('core', '0401_receitaprevistapaa'),
    ]

    operations = [
    ]
