# Generated by Django 4.2.20 on 2025-04-02 14:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


def carregar_dados(apps, schema_editor):
    fonte_recurso_model = apps.get_model('core', 'FonteRecursoPaa')
    fontes  = [
        "Campanhas com Arrecadação",
        "Campanhas sem Arrecadação",
        "Convênios e Parcerias",
        "Doações",
        "Festas com Arrecadação",
        "Festas sem Arrecadação",
        "Juros",
        "Outras Fontes",
        "Reuniões Ordinárias"
        
    ]
    registros = [fonte_recurso_model(nome=fonte) for fonte in fontes]
    fonte_recurso_model.objects.bulk_create(registros)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0402_merge_20250324_1256"),
    ]

    operations = [
        migrations.CreateModel(
            name="FonteRecursoPaa",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=160, verbose_name="Nome")),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "alterado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Alterado em"),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
            ],
            options={
                "verbose_name": "Fonte Recursos PAA",
                "verbose_name_plural": "22.0) Fonte Recursos PAA",
            },
        ),
        migrations.RunPython(carregar_dados),
    ]
