# Generated by Django 4.2.20 on 2025-04-02 14:58

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0403_fonte_recurso_paa"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecursoProprioPaa",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "alterado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Alterado em"),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("data_prevista", models.DateField(default=datetime.date.today)),
                ("descricao", models.CharField(max_length=255)),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=20, verbose_name="Valor"
                    ),
                ),
                (
                    "associacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="associacao",
                        to="core.associacao",
                    ),
                ),
                (
                    "fonte_recurso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recurso_proprio",
                        to="core.fonterecursopaa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recurso Próprio PAA",
                "verbose_name_plural": "23.0) Recursos Próprios PAA",
            },
        ),
    ]
