# Generated by Django 4.2.20 on 2025-04-02 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0404_recurso_proprio_paa"),
    ]

    operations = [
        migrations.AlterField(
            model_name="acaopdde",
            name="categoria",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.categoriapdde",
            ),
        ),
    ]
