# Generated by Django 4.2.20 on 2025-04-08 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0403_acaopdde_previsao_valor_capital_and_more"),
        ("core", "0405_alter_acaopdde_categoria"),
    ]

    operations = []
