# Generated by Django 4.2.20 on 2025-05-14 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0406_merge_20250408_0913"),
    ]

    operations = [
        migrations.CreateModel(
            name="FuncUeSituacaoPatrimonial",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "[UE] Situação Patrimonial",
                "verbose_name_plural": "[UE] Situação Patrimonial",
                "permissions": (
                    (
                        "access_situacao_patrimonial",
                        "[UE] Pode acessar Situação Patrimonial.",
                    ),
                    (
                        "change_situacao_patrimonial",
                        '[UE] Pode editar Situação Patrimonial".',
                    ),
                ),
                "managed": False,
                "default_permissions": (),
            },
        ),
    ]
