# Generated by Django 4.2.20 on 2025-08-06 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0408_alter_categoriapdde_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="acaoassociacao",
            options={
                "verbose_name": "Ação de Associação",
                "verbose_name_plural": "07.3) Ações de Associações",
            },
        ),
        migrations.AlterModelOptions(
            name="membroassociacao",
            options={
                "verbose_name": "Membro da Associação",
                "verbose_name_plural": "07.4) Membros das Associações",
            },
        ),
        migrations.AlterModelOptions(
            name="motivorejeicaoencerramentocontaassociacao",
            options={
                "verbose_name": "Motivo de rejeição de encerramento de conta de associação",
                "verbose_name_plural": "07.6) Motivos de rejeição de encerramento de conta de associação",
            },
        ),
        migrations.AlterModelOptions(
            name="processoassociacao",
            options={
                "verbose_name": "Processo de prestação de contas",
                "verbose_name_plural": "07.2) Processos de prestação de contas",
            },
        ),
        migrations.AlterModelOptions(
            name="solicitacaoencerramentocontaassociacao",
            options={
                "verbose_name": "Solicitação de Encerramento de Conta de Associação",
                "verbose_name_plural": "07.5) Solicitações de Encerramento de Conta de Associação",
            },
        ),
    ]
