# Generated by Django 4.2.20 on 2025-08-26 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0409_alter_acaoassociacao_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analisecontaprestacaoconta',
            name='solicitar_correcao_da_data_do_saldo_da_conta',
            field=models.BooleanField(default=False, verbose_name='Solicitar correção da data do saldo da conta'),
        ),
    ]
