# Generated by Django 4.2.20 on 2025-09-10 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "core",
            "0410_analisecontaprestacaoconta_solicitar_correcao_da_data_do_saldo_da_conta",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="funcdreassociacoesdadre",
            options={
                "default_permissions": (),
                "managed": False,
                "permissions": (
                    ("access_associacao_dre", "[DRE] Pode acessar Associações da DRE."),
                    (
                        "access_dados_unidade_dre",
                        "[DRE] Pode acessar dados de uma unidade.",
                    ),
                    (
                        "access_situacao_financeira_dre",
                        "[DRE] Pode acessar a situação financeira de uma unidade.",
                    ),
                    (
                        "access_situacao_patrimonial_dre",
                        "[DRE] Pode acessar a situação patrimonial de uma unidade.",
                    ),
                ),
                "verbose_name": "[DRE] Associações da DRE",
                "verbose_name_plural": "[DRE] Associações da DRE",
            },
        ),
    ]
