# Generated by Django 4.2.20 on 2025-09-09 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "core",
            "0410_analisecontaprestacaoconta_solicitar_correcao_da_data_do_saldo_da_conta",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="funcuerecebimentodenotificacoes",
            options={
                "default_permissions": (),
                "managed": False,
                "permissions": (
                    (
                        "recebe_notificacao_inicio_periodo_prestacao_de_contas",
                        "[UE] Pode receber Notificação Início Período Prestação De Contas.",
                    ),
                    (
                        "recebe_notificacao_pendencia_envio_prestacao_de_contas",
                        "[UE] Pode receber Notificação pendência envio Prestação De Contas.",
                    ),
                    (
                        "recebe_notificacao_proximidade_inicio_prestacao_de_contas",
                        "[UE] Pode receber Notificação Proximidade Início Prestação De Contas.",
                    ),
                    (
                        "recebe_notificacao_prestacao_de_contas_devolvida_para_acertos",
                        "[UE] Pode receber Notificação Prestação de Contas Devolvida para Acertos",
                    ),
                    (
                        "recebe_notificacao_proximidade_fim_periodo_prestacao_de_contas",
                        "[UE] Pode receber Notificação Proximidade Fim Período Prestação de Contas",
                    ),
                    (
                        "recebe_notificacao_atraso_entrega_ajustes_prestacao_de_contas",
                        "[UE] Pode receber Notificação Atraso Entrega Ajustes Prestação de Contas",
                    ),
                    (
                        "recebe_notificacao_proximidade_fim_prazo_ajustes_prestacao_de_contas",
                        "[UE] Pode receber Notificação Proximidade Fim Prazo Ajustes Prestação de Contas",
                    ),
                    (
                        "recebe_notificacao_comentario_em_pc",
                        "[UE] Pode receber Notificação de Comentários",
                    ),
                    (
                        "recebe_notificacao_aprovacao_pc",
                        "[UE] Pode receber Notificação Prestação de Contas Aprovada",
                    ),
                    (
                        "recebe_notificacao_reprovacao_pc_nao_incluindo_motivos",
                        "[UE] Pode receber Notificação Prestação de Contas Reprovada Não Incluindo Motivos",
                    ),
                    (
                        "recebe_notificacao_reprovacao_pc_incluindo_motivos",
                        "[UE] Pode receber Notificação Prestação de Contas Reprovada Incluindo Motivos",
                    ),
                    (
                        "recebe_notificacao_automatica_inativacao_conta",
                        "[UE] Pode receber Notificação Encerramento de Conta Bancária",
                    ),
                    (
                        "recebe_notificacao_resultado_encerramento_conta",
                        "[UE] Pode receber Notificação Resultado Encerramento de Conta Bancária",
                    ),
                    (
                        "recebe_notificacao_geracao_ata_apresentacao",
                        "[UE] Pode receber Notificação Geração Ata de Apresentação",
                    ),
                    (
                        "recebe_notificacao_geracao_ata_retificacao",
                        "[UE] Pode receber Notificação Geração Ata de Retificação",
                    ),
                    (
                        "recebe_notificacao_conclusao_reprovada_pc_nao_apresentada",
                        "[UE] Pode receber Notificação Prestação de Contas Reprovada Não Apresentação",
                    ),
                ),
                "verbose_name": "[UE] Recebimento de notificações",
                "verbose_name_plural": "[UE] Recebimento de notificações",
            },
        ),
    ]
