# Generated by Django 4.2.20 on 2025-09-10 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0411_alter_funcdreassociacoesdadre_options"),
        ("core", "0411_alter_funcuerecebimentodenotificacoes_options"),
    ]

    operations = []
