# Generated by Django 4.2.20 on 2025-09-12 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0412_merge_20250910_1125"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="parametros",
            name="texto_pagina_paa_ue",
        ),
    ]
