# Generated by Django 4.2.20 on 2025-09-17 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0413_remove_parametros_texto_pagina_paa_ue"),
    ]

    operations = [
        migrations.AddField(
            model_name="tipoacertodocumento",
            name="pode_alterar_saldo_conciliacao",
            field=models.BooleanField(
                default=False,
                verbose_name="Este tipo de acerto pode alterar o saldo em conciliação bancária",
            ),
        ),
        migrations.AddField(
            model_name="tipoacertolancamento",
            name="pode_alterar_saldo_conciliacao",
            field=models.BooleanField(
                default=False,
                verbose_name="Este tipo de acerto pode alterar o saldo em conciliação bancária",
            ),
        ),
    ]
