# Generated by Django 4.2.20 on 2025-09-30 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0414_tipoacertodocumento_pode_alterar_saldo_conciliacao_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="funcdreassociacoesdadre",
            options={
                "default_permissions": (),
                "managed": False,
                "permissions": (
                    ("access_associacao_dre", "[DRE] Pode acessar Associações da DRE."),
                    (
                        "access_dados_unidade_dre",
                        "[DRE] Pode acessar dados de uma unidade.",
                    ),
                    (
                        "access_situacao_financeira_dre",
                        "[DRE] Pode acessar a situação financeira de uma unidade.",
                    ),
                    (
                        "access_situacao_patrimonial_dre",
                        "[DRE] Pode acessar a situação patrimonial de uma unidade.",
                    ),
                    (
                        "aceita_e_rejeita_cancelamento_conta",
                        "[DRE] Pode aceitar e rejeitar cancelamento de conta.",
                    ),
                ),
                "verbose_name": "[DRE] Associações da DRE",
                "verbose_name_plural": "[DRE] Associações da DRE",
            },
        ),
    ]
