# Generated by Django 4.2.20 on 2025-10-17 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0416_alter_funcdreassociacoesdadre_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="acao",
            name="exibir_paa",
            field=models.BooleanField(
                default=True,
                help_text="Considera a Ação para o PAA (Receitas previstas PAA, Prioridades do PAA)",
                verbose_name="Exibir no PAA?",
            ),
        ),
    ]
