# Generated by Django 4.2.20 on 2025-10-30 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0417_acao_exibir_paa"),
    ]

    operations = [
        migrations.AddField(
            model_name="arquivodownload",
            name="dre",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"tipo_unidade": "DRE"},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="arquivos_download_da_dre",
                to="core.unidade",
            ),
        ),
    ]
