# Generated by Django 4.2.20 on 2025-10-29 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0417_acao_exibir_paa"),
    ]

    operations = [
        migrations.AddField(
            model_name="analisecontaprestacaoconta",
            name="solicitar_correcao_de_justificativa_de_conciliacao",
            field=models.BooleanField(
                default=False, verbose_name="Solicitar correção de justificativa"
            ),
        ),
    ]
