# Generated by Django 4.2.20 on 2025-10-31 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "core",
            "0418_analisecontaprestacaoconta_solicitar_correcao_de_justificativa_de_conciliacao",
        ),
        ("core", "0418_arquivodownload_dre"),
    ]

    operations = []
