# Generated by Django 4.2.20 on 2025-12-10 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0419_merge_20251031_1017"),
    ]

    operations = [
        migrations.AddField(
            model_name="participante",
            name="professor_gremio",
            field=models.BooleanField(
                default=False, verbose_name="Professor do grêmio ?"
            ),
        ),
    ]
