# Generated by Django 4.2.20 on 2026-01-21 17:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0420_participante_professor_gremio"),
    ]

    operations = [
        migrations.AddField(
            model_name="parametros",
            name="tipos_unidades_professor_gremio",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("ADM", "ADM"),
                        ("DRE", "DRE"),
                        ("IFSP", "IFSP"),
                        ("CMCT", "CMCT"),
                        ("CECI", "CECI"),
                        ("CEI", "CEI"),
                        ("CEMEI", "CEMEI"),
                        ("CIEJA", "CIEJA"),
                        ("EMEBS", "EMEBS"),
                        ("EMEF", "EMEF"),
                        ("EMEFM", "EMEFM"),
                        ("EMEI", "EMEI"),
                        ("CEU", "CEU"),
                        ("CEU CEI", "CEU CEI"),
                        ("CEU EMEF", "CEU EMEF"),
                        ("CEU EMEI", "CEU EMEI"),
                        ("CEU CEMEI", "CEU CEMEI"),
                        ("CEI DIRET", "CEI DIRET"),
                    ],
                    max_length=20,
                ),
                blank=True,
                default=list,
                size=None,
                verbose_name="Tipos de unidades que possuem professor grêmio na ata do PAA",
            ),
        ),
    ]
