# Generated by Django 4.2.20 on 2026-01-21 10:26

from django.db import migrations, models
import uuid


def criar_recurso_legado(apps, schema_editor):
    Recurso = apps.get_model('core', 'Recurso')

    Recurso.objects.filter(legado=True).update(legado=False)

    Recurso.objects.get_or_create(
        nome="Programa de Transferência de Recursos Financeiros - PTRF",
        defaults={
            "nome_exibicao": "PTRF",
            "cor": "#01585E",
            "legado": True,
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0421_parametros_tipos_unidades_professor_gremio"),
    ]

    operations = [
        migrations.CreateModel(
            name="Recurso",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=160, verbose_name="Nome")),
                (
                    "ativo",
                    models.BooleanField(default=True, verbose_name="Está ativo?"),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "alterado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Alterado em"),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "nome_exibicao",
                    models.CharField(
                        help_text="Será usado no seletor de recursos do site.",
                        max_length=160,
                        verbose_name="Nome exibição",
                    ),
                ),
                (
                    "logo",
                    models.FileField(
                        blank=True,
                        help_text="Será usada no header do site.",
                        null=True,
                        upload_to="",
                        verbose_name="Logo",
                    ),
                ),
                (
                    "icone",
                    models.FileField(
                        blank=True,
                        help_text="Será usado no menu lateral e modal de escolha de recurso.",
                        null=True,
                        upload_to="",
                        verbose_name="Ícone",
                    ),
                ),
                (
                    "cor",
                    models.CharField(
                        choices=[
                            ("#3982AC", "Azul"),
                            ("#01585E", "Verde"),
                            ("#0D3B66", "Azul Marinho"),
                            ("#C65A1E", "Laranja"),
                            ("#4B2E83", "Roxo Profundo"),
                        ],
                        help_text="Será usada na estilização do site.",
                        max_length=7,
                    ),
                ),
                (
                    "legado",
                    models.BooleanField(
                        default=False,
                        help_text="Em caso de flag inativa, esse recurso será utilizado nos filtros.",
                        verbose_name="Legado?",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recurso",
                "verbose_name_plural": "20.0) Recursos",
            },
        ),
        migrations.AddConstraint(
            model_name="recurso",
            constraint=models.UniqueConstraint(
                condition=models.Q(("legado", True)),
                fields=("legado",),
                name="unique_recurso_legado",
                violation_error_message="Já existe um recurso marcado como legado.",
            ),
        ),      
        migrations.RunPython(criar_recurso_legado, reverse_code=migrations.RunPython.noop)
    ]
