# Generated by Django 4.2.20 on 2026-01-23 13:54

from django.db import migrations, models
import django.db.models.deletion


def atualiza_recurso_periodos(apps, schema_editor):
    Recurso = apps.get_model('core', 'Recurso')
    Periodo = apps.get_model('core', 'Periodo')

    recurso_legado = Recurso.objects.get(legado=True)

    Periodo.objects.filter(recurso__isnull=True).update(recurso=recurso_legado)

class Migration(migrations.Migration):

    dependencies = [
        ("core", "0421_recurso_recurso_unique_recurso_legado"),
    ]

    operations = [
        migrations.AddField(
            model_name="periodo",
            name="recurso",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.recurso",
                verbose_name="Recurso",
            ),
        ),
        migrations.RunPython(atualiza_recurso_periodos, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name="periodo",
            name="recurso",
            field=models.ForeignKey(
                blank=False,
                null=False,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.recurso",
                verbose_name="Recurso",
            ),
        ),        
    ]
