# Generated by Django 4.2.20 on 2026-01-26 00:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


def criar_periodos_iniciais_por_recurso(apps, schema_editor):
    Recurso = apps.get_model('core', 'Recurso')
    Associacao = apps.get_model('core', 'Associacao')
    PeriodoInicialAssociacao = apps.get_model('core', 'PeriodoInicialAssociacao')

    recurso_legado = Recurso.objects.get(legado=True)

    associacoes = Associacao.objects.filter(periodo_inicial__isnull=False)

    objetos = [
        PeriodoInicialAssociacao(
            associacao=a,
            periodo_inicial=a.periodo_inicial,
            recurso=recurso_legado,
        )
        for a in associacoes
    ]

    PeriodoInicialAssociacao.objects.bulk_create(objetos, batch_size=1000)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0423_periodo_recurso"),
    ]

    operations = [
        migrations.CreateModel(
            name="PeriodoInicialAssociacao",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "alterado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Alterado em"),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "associacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="periodos_iniciais",
                        to="core.associacao",
                        verbose_name="Associação",
                    ),
                ),
                (
                    "periodo_inicial",
                    models.ForeignKey(
                        help_text="O período inicial informado é uma referência e indica que o período a ser habilitado para a associação será o período posterior ao período informado.",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.periodo",
                        verbose_name="Período inicial",
                    ),
                ),
                (
                    "recurso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.recurso",
                        verbose_name="Recurso",
                    ),
                ),
            ],
            options={
                "verbose_name": "Período Inicial de Associação",
                "verbose_name_plural": "07.7) Períodos Iniciais de Associação",
            },
        ),
        migrations.AddConstraint(
            model_name="periodoinicialassociacao",
            constraint=models.UniqueConstraint(
                fields=("associacao", "recurso"),
                name="uniq_periodo_inicial_associacao_recurso",
            ),
        ),
        migrations.RunPython(criar_periodos_iniciais_por_recurso, reverse_code=migrations.RunPython.noop),
    ]
