# Generated by Django 4.2.20 on 2026-01-21 15:12

from django.db import migrations, models
import django.db.models.deletion

def atualiza_recurso_acoes(apps, schema_editor):
    Recurso = apps.get_model('core', 'Recurso')
    Acao = apps.get_model('core', 'Acao')

    recurso_legado = Recurso.objects.get(legado=True)

    Acao.objects.filter(recurso__isnull=True).update(recurso=recurso_legado)

class Migration(migrations.Migration):

    dependencies = [
        ("core", "0423_periodoinicialassociacao"),
    ]

    operations = [
        migrations.AddField(
            model_name="acao",
            name="recurso",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.recurso",
            ),
        ),
        migrations.RunPython(atualiza_recurso_acoes, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name="acao",
            name="recurso",
            field=models.ForeignKey(
                null=False,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.recurso",
            )
        )
    ]
