# Generated by Django 4.2.20 on 2026-01-28 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0424_acao_recurso"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="periodoinicialassociacao",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="acao",
            name="recurso",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="core.recurso",
                verbose_name="Recurso",
            ),
        ),
        migrations.AddConstraint(
            model_name="periodoinicialassociacao",
            constraint=models.UniqueConstraint(
                fields=("associacao", "recurso"),
                name="uniq_periodo_inicial_associacao_recurso",
            ),
        ),
    ]
