# Generated by Django 4.2.20 on 2026-01-26 11:35

from django.db import migrations, models
import django.db.models.deletion

def atualiza_recurso_tipos_de_conta(apps, schema_editor):
    Recurso = apps.get_model('core', 'Recurso')
    TipoConta = apps.get_model('core', 'TipoConta')

    recurso_legado = Recurso.objects.get(legado=True)

    TipoConta.objects.filter(recurso__isnull=True).update(recurso=recurso_legado)

class Migration(migrations.Migration):

    dependencies = [
        ("core", "0424_acao_recurso"),
    ]

    operations = [
        migrations.AddField(
            model_name="tipoconta",
            name="recurso",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.recurso"
            ),
        ),
        migrations.RunPython(atualiza_recurso_tipos_de_conta, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name="tipoconta",
            name="recurso",
            field=models.ForeignKey(
                null=False,
                verbose_name="Recurso",
                on_delete=django.db.models.deletion.PROTECT,
                to="core.recurso"
            )
        )
    ]
