# Generated by Django 4.2.20 on 2026-01-28 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0425_alter_periodoinicialassociacao_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recurso",
            name="cor",
            field=models.CharField(
                choices=[
                    ("#3982AC", "Azul"),
                    ("#01585E", "Verde"),
                    ("#0D3B66", "Azul Marinho"),
                    ("#C65A1E", "Laranja"),
                    ("#4B2E83", "Roxo Profundo"),
                ],
                help_text="Será usada na estilização do site.",
                max_length=7,
            ),
        ),
    ]
