# Generated by Django 4.2.20 on 2026-01-29 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0421_parametros_tipos_unidades_professor_gremio"),
        ("core", "0426_alter_recurso_cor"),
    ]

    operations = []
