# Generated by Django 4.2.20 on 2026-02-06 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0427_alter_parametros_tipos_unidades_professor_gremio"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="periodoinicialassociacao",
            options={
                "verbose_name": "Período Inicial de Associação",
                "verbose_name_plural": "08.1) Períodos Iniciais de Associações",
            },
        ),
        migrations.AlterField(
            model_name="associacao",
            name="periodo_inicial",
            field=models.ForeignKey(
                blank=True,
                help_text="O período inicial informado é uma referência para o recurso PTRF e indica que o período a ser habilitado para a associação será o período posterior ao período informado.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="associacoes_iniciadas_no_periodo",
                to="core.periodo",
                verbose_name="período inicial",
            ),
        ),
    ]
