# Generated by Django 4.2.20 on 2026-02-06 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0427_alter_parametros_tipos_unidades_professor_gremio"),
    ]

    operations = [
        
    ]
