# Generated by Django 4.2.20 on 2026-02-06 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0427_alter_parametros_tipos_unidades_professor_gremio"),
    ]

    operations = [
        migrations.AddField(
            model_name="prestacaoconta",
            name="processando_demonstrativo",
            field=models.BooleanField(
                default=False, verbose_name="Processando Relatório Demonstrativo"
            ),
        ),
        migrations.AddField(
            model_name="prestacaoconta",
            name="processando_demonstrativo_desde",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
