# Generated by Django 4.2.20 on 2026-02-09 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0428_prestacaoconta_processando_demonstrativo_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="prestacaoconta",
            name="processando_demonstrativo",
        ),
        migrations.RemoveField(
            model_name="prestacaoconta",
            name="processando_demonstrativo_desde",
        ),
    ]
