# Generated by Django 4.2.20 on 2026-02-12 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0428_alter_periodoinicialassociacao_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="associacao",
            name="periodo_inicial",
            field=models.ForeignKey(
                blank=True,
                help_text="O período inicial informado é uma referência para o recurso legado e indica que o período a             ser habilitado para a Associação será o período imediatamente posterior ao informado. No caso da             SME/SP o recurso legado refere-se ao PTRF.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="associacoes_iniciadas_no_periodo",
                to="core.periodo",
                verbose_name="período inicial",
            ),
        ),
    ]
