# Generated by Django 4.2.20 on 2026-02-12 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0428_alter_periodoinicialassociacao_options_and_more"),
        ("core", "0428_prestacaoconta_processando_demonstrativo_and_more"),
    ]

    operations = []
