# Generated by Django 4.2.20 on 2026-03-03 09:18

from django.db import migrations, models
import django.db.models.deletion


def atualiza_recurso_processos_associacao(apps, schema_editor):
    Recurso = apps.get_model('core', 'Recurso')
    ProcessoAssociacao = apps.get_model('core', 'ProcessoAssociacao')

    recurso_legado = Recurso.objects.get(legado=True)

    ProcessoAssociacao.objects.filter(recurso__isnull=True).update(recurso=recurso_legado)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0429_alter_associacao_periodo_inicial"),
    ]

    operations = [
        migrations.AddField(
            model_name="processoassociacao",
            name="recurso",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.recurso",
                verbose_name="Recurso",
            ),
        ),
        migrations.RunPython(atualiza_recurso_processos_associacao, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name="processoassociacao",
            name="recurso",
            field=models.ForeignKey(
                blank=False,
                null=False,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.recurso",
                verbose_name="Recurso",
            ),
        ),
    ]
