# Generated by Django 4.2.20 on 2026-03-23 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0430_processoassociacao_recurso"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="funcueplanoanualdeatividade",
            options={
                "default_permissions": (),
                "managed": False,
                "permissions": (
                    ("access_paa", "[UE] Pode acessar Plano Anual de Atividade."),
                    ("custom_change_paa", "[UE] Pode editar Plano Anual de Atividade"),
                ),
                "verbose_name": "[UE] Plano anual de atividade",
                "verbose_name_plural": "[UE] Plano anual de atividade",
            },
        ),
    ]
