# Generated by Django 4.2.20 on 2026-03-23

from django.db import migrations


def remove_change_paa_permission(apps, schema_editor):
    """
    Remove apenas a permissão change_paa com typo do core | [UE] Plano anual de atividade.
    Mantém: custom_change_paa (core) e change_paa (paa | PAA - permissão default do modelo PAA).
    """
    Permission = apps.get_model("auth", "Permission")
    ContentType = apps.get_model("contenttypes", "ContentType")

    content_type = ContentType.objects.filter(
        app_label="core",
        model="funcueplanoanualdeatividade",
    ).first()

    if content_type:
        Permission.objects.filter(
            content_type=content_type,
            codename="change_paa",
        ).delete()


def reverse_remove_change_paa(apps, schema_editor):
    """Reversão: recriar a permissão change_paa se necessário."""
    Permission = apps.get_model("auth", "Permission")
    ContentType = apps.get_model("contenttypes", "ContentType")

    content_type = ContentType.objects.filter(
        app_label="core",
        model="funcueplanoanualdeatividade",
    ).first()

    if content_type and not Permission.objects.filter(
        content_type=content_type,
        codename="change_paa",
    ).exists():
        Permission.objects.create(
            content_type=content_type,
            codename="change_paa",
            name='[UE] Pode editar Plano Anual de Atividade".',
        )


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0431_alter_funcueplanoanualdeatividade_options"),
    ]

    operations = [
        migrations.RunPython(remove_change_paa_permission, reverse_remove_change_paa),
    ]
