# Generated by Django 4.2.20 on 2026-04-01 17:06

from django.db import migrations, models

def atualiza_recurso_exibe_valores_reprogramados(apps, schema_editor):
    Recurso = apps.get_model('core', 'Recurso')
    Recurso.objects.filter(legado=True).update(exibe_valores_reprogramados=True)

class Migration(migrations.Migration):

    dependencies = [
        ("core", "0432_remove_change_paa_permission"),
    ]

    operations = [
        migrations.AddField(
            model_name="recurso",
            name="exibe_valores_reprogramados",
            field=models.BooleanField(
                default=False, verbose_name="Exibir valores reprogramados?"
            ),
        ),
        migrations.RunPython(atualiza_recurso_exibe_valores_reprogramados),
    ]
