# Generated by Django 4.2.20 on 2026-04-15 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0433_recurso_exibe_valores_reprogramados"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recurso",
            name="logo",
        ),
        migrations.AlterField(
            model_name="recurso",
            name="legado",
            field=models.BooleanField(
                default=False,
                help_text="Em caso de flag inativa, esse recurso será utilizado nos filtros. No caso da SME/SP, o recurso legado refere-se ao PTRF.",
                verbose_name="Legado?",
            ),
        ),
    ]
