# Generated by Django 4.2.20 on 2026-04-29 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0434_remove_recurso_logo_alter_recurso_legado"),
    ]

    operations = [
        migrations.CreateModel(
            name="FuncDrePaa",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "[DRE] Acessar PAA",
                "verbose_name_plural": "[DRE] Acessar PAA",
                "permissions": (("custom_access_paa_dre", "[DRE] Pode acessar PAA"),),
                "managed": False,
                "default_permissions": (),
            },
        ),
    ]
