# Generated by Django 4.2.20 on 2026-04-23 17:28

from django.db import migrations, models

def atualiza_recurso_legado_permite_saldo_acoes_negativo(apps, schema_editor):
    Recurso = apps.get_model('core', 'Recurso')
    Recurso.objects.filter(legado=True).update(permite_saldo_acoes_negativo=True)

class Migration(migrations.Migration):

    dependencies = [
        ("core", "0434_remove_recurso_logo_alter_recurso_legado"),
    ]

    operations = [
        migrations.AddField(
            model_name="recurso",
            name="permite_saldo_acoes_negativo",
            field=models.BooleanField(
                default=False, verbose_name="Permite saldo negativo em ações?"
            ),
        ),
        migrations.AddField(
            model_name="recurso",
            name="permite_saldo_conta_negativo",
            field=models.BooleanField(
                default=False, verbose_name="Permite saldo negativo em contas?"
            ),
        ),
        migrations.RunPython(atualiza_recurso_legado_permite_saldo_acoes_negativo),
    ]
