# Generated by Django 4.2.20 on 2026-04-16 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0434_remove_recurso_logo_alter_recurso_legado"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificacao",
            name="recurso",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.recurso",
                verbose_name="recurso",
            ),
        ),
    ]
