# Generated by Django 4.2.20 on 2026-04-27 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0435_notificacao_recurso"),
        ("core", "0436_recurso_tipo_conta_um_recurso_tipo_conta_dois"),
    ]

    operations = []
