# Generated by Django 4.2.20 on 2026-04-28 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0435_recurso_permite_saldo_acoes_negativo_and_more"),
        ("core", "0437_merge_20260427_0706"),
    ]

    operations = []
