# Generated by Django 4.2.20 on 2026-04-29 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0435_funcdrepaa"),
        ("core", "0438_merge_20260428_0940"),
    ]

    operations = []
