# Generated by Django 4.2.20 on 2026-05-08

from django.db import migrations, models


def habilita_aprovacao_com_ressalvas_recurso_legado(apps, schema_editor):
    recurso = apps.get_model("core", "Recurso")
    recurso.objects.filter(legado=True).update(habilita_aprovacao_com_ressalvas=True)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0439_merge_0435_funcdrepaa_0438_merge_20260428_0940"),
    ]

    operations = [
        migrations.AddField(
            model_name="recurso",
            name="habilita_aprovacao_com_ressalvas",
            field=models.BooleanField(
                default=False,
                help_text="Define se o recurso exibe a opção de aprovação com ressalvas.",
                verbose_name="Habilitar Aprovação com ressalvas",
            ),
        ),
        migrations.RunPython(
            habilita_aprovacao_com_ressalvas_recurso_legado,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
