# Generated by Django 4.2.20 on 2026-05-13 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0440_recurso_habilita_aprovacao_com_ressalvas"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="tipoconta",
            unique_together={("nome", "recurso")},
        ),
    ]
