# Generated by Django 4.2.20 on 2026-05-27 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0441_alter_tipoconta_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recurso",
            name="exibe_valores_reprogramados",
            field=models.BooleanField(
                default=False,
                help_text="Os valores reprogramados iniciais, quando necessário, são indicados no período inicial de referência.",
                verbose_name="Exibir valores reprogramados iniciais?",
            ),
        ),
    ]
