# Generated by Django 4.2.20 on 2026-06-10 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0442_alter_recurso_exibe_valores_reprogramados"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="parametros",
            name="permite_saldo_acoes_negativo",
        ),
        migrations.RemoveField(
            model_name="parametros",
            name="permite_saldo_conta_negativo",
        ),
    ]
