# Generated by Django 4.2.20 on 2026-06-18 10:34

from django.db import migrations, models

def habilita_exibicao_de_lauda_recurso_legado(apps, schema_editor):
    recurso = apps.get_model("core", "Recurso")
    recurso.objects.filter(legado=True).update(habilita_exibicao_de_lauda=True)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0443_remove_parametros_permite_saldo_acoes_negativo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="recurso",
            name="habilita_exibicao_de_lauda",
            field=models.BooleanField(
                default=False,
                help_text="Define se o recurso segue o fluxo de lauda, caso não esteja marcado, seguirá o fluxo de relatório.",
                verbose_name="Habilitar exibição de lauda?",
            ),
        ),
        migrations.RunPython(
            habilita_exibicao_de_lauda_recurso_legado,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
