# Generated by Django 4.2.20 on 2026-06-30 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0444_recurso_habilita_exibicao_de_lauda"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recurso",
            name="habilita_exibicao_de_lauda",
            field=models.BooleanField(
                default=False,
                help_text="Define se o recurso deve exibir o documento de Lauda no Consolidado das PCs. Caso não esteja marcado, o documento de Lauda não será exibido e a nomenclatura utilizada é Relatório.",
                verbose_name="Habilitar exibição de lauda?",
            ),
        ),
    ]
