# Generated by Django 4.2.20 on 2026-07-02 09:26

from django.db import migrations, models
import django.db.models.deletion

def atualiza_recurso_tipo_acerto_documento(apps, schema_editor):
    Recurso = apps.get_model('core', 'Recurso')
    TipoAcertoDocumento = apps.get_model('core', 'TipoAcertoDocumento')

    recurso_legado = Recurso.objects.get(legado=True)

    TipoAcertoDocumento.objects.filter(recurso__isnull=True).update(recurso=recurso_legado)

def migra_documentos_prestacao(apps, schema_editor):
    Recurso = apps.get_model('core', 'Recurso')
    TipoAcertoDocumento = apps.get_model('core', 'TipoAcertoDocumento')
    
    try:
        recurso_premio = Recurso.objects.get(nome="Prêmio Excelência Educacional")
    except Recurso.DoesNotExist:
        return
    
    tipo_acertos = TipoAcertoDocumento.objects.filter(recurso__legado=True)
    for tipo_acerto in tipo_acertos:
        existe_acerto_premio = TipoAcertoDocumento.objects.filter(
            nome=tipo_acerto.nome,
            categoria=tipo_acerto.categoria,
            recurso__nome="Prêmio Excelência Educacional"
        )
        
        if not existe_acerto_premio.exists():
            novo_tipo_acerto = TipoAcertoDocumento.objects.create(
                nome=tipo_acerto.nome,
                categoria=tipo_acerto.categoria,
                ativo=tipo_acerto.ativo,
                recurso=recurso_premio,
                pode_alterar_saldo_conciliacao=tipo_acerto.pode_alterar_saldo_conciliacao
            )
            novo_tipo_acerto.tipos_documento_prestacao.set(
                tipo_acerto.tipos_documento_prestacao.all()
            )

class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ("core", "0445_alter_recurso_habilita_exibicao_de_lauda"),
    ]

    operations = [
        migrations.AddField(
            model_name="tipoacertodocumento",
            name="recurso",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.recurso",
                verbose_name="Recurso",
            ),
        ),
        migrations.RunPython(atualiza_recurso_tipo_acerto_documento, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name="tipoacertodocumento",
            name="recurso",
            field=models.ForeignKey(
                null=False,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.recurso",
                verbose_name="Recurso",
            )
        ),
        migrations.RunPython(migra_documentos_prestacao, reverse_code=migrations.RunPython.noop),
    ]
