# Generated by Django 4.2.20 on 2026-07-20 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0449_corrige_tipo_acerto_lancamento_solicitacoes_premio"),
    ]

    operations = [
        migrations.AddField(
            model_name="recurso",
            name="texto_ata_introducao",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Este texto é exibido antes do texto complementar: ___ dias do mês de ___ de ___, às zero hora, reuniu-se a <exibe nome da comissão responsável pelaanálise de PC do recurso> da Diretoria Regional de Educação <exibe a DRE correspondente do consolidado>, instituída pela Portaria DRE-<exibe a DRE correspondente do consolidado> nº _______ de __________, para análise das prestações de contas dos recursos transferidos pelo <exibe o recurso correspondente>, período de <exibe o período correspondente do consolidado>",
                max_length=256,
                verbose_name="Introdução da ata",
            ),
        ),
        migrations.AddField(
            model_name="recurso",
            name="texto_ata_letra_a",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Este texto é exibido antes do texto complementar: <p style='display: inline;'><strong style='color: #297805;'>APROVAR</strong> as prestações de contas das Associações das unidades abaixo relacionadas</p>",
                max_length=256,
                verbose_name="Letra A",
            ),
        ),
        migrations.AddField(
            model_name="recurso",
            name="texto_ata_letra_b",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Este texto é exibido antes do texto complementar: <p style='display: inline;'><strong style='color: #297805;'>APROVAR COM RESSALVAS</strong> as prestações de contas das Associações das unidades abaixo relacionadas</p>",
                max_length=256,
                verbose_name="Letra B",
            ),
        ),
        migrations.AddField(
            model_name="recurso",
            name="texto_ata_letra_c",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Este texto é exibido antes do texto complementar: <p style='display: inline;'><strong style='color: #b40c02;'>REJEITAR</strong> as prestações de contas das Associações das unidades abaixo relacionadas</p>",
                max_length=256,
                verbose_name="Letra C",
            ),
        ),
        migrations.AddField(
            model_name="recurso",
            name="texto_ata_letra_d",
            field=models.CharField(
                blank=True, default="", max_length=256, verbose_name="Letra D"
            ),
        ),
    ]
