# Generated by Django 4.2.20 on 2026-07-20 15:19

from django.db import migrations


def populate_data(apps, schema_editor):
    Recurso = apps.get_model("core", "Recurso")

    recurso_legado = Recurso.objects.filter(legado=True).first()

    if recurso_legado:
        recurso_legado.texto_ata_introducao = "conforme incisos III e IV do art. 34 da Portaria SME nº 6.634/2021 e deliberou:"
        recurso_legado.texto_ata_letra_a = "analisadas sob aspecto de exatidão numérica e obediência à legislação, conforme inciso I do art. 36 da Portaria SME nº 6.634/2021:"
        recurso_legado.texto_ata_letra_b = "analisadas sob aspecto de exatidão numérica e obediência à legislação, conforme inciso II do art. 36 da Portaria SME nº 6.634/2021:"
        recurso_legado.texto_ata_letra_c = "conforme inciso III do art. 36 da Portaria SME nº 6.634/2021:"
        recurso_legado.texto_ata_letra_d = "Submeter ao Sr. Diretor Regional de Educação, a presente Ata, com o parecer conclusivo desta Comissão " \
                                            "atendendo ao inciso IV, do art. 34 da Portaria SME nº 6.634/2021, manter sob custódia até a publicação do " \
                                            "despacho no DOC."
        recurso_legado.save()

def reverse_populate_data(apps, schema_editor):
    Recurso = apps.get_model("core", "Recurso")

    recurso_legado = Recurso.objects.filter(legado=True).first()

    if recurso_legado:
        recurso_legado.texto_ata_introducao = ""
        recurso_legado.texto_ata_letra_a = ""
        recurso_legado.texto_ata_letra_b = ""
        recurso_legado.texto_ata_letra_c = ""
        recurso_legado.texto_ata_letra_d = ""
        recurso_legado.save()

class Migration(migrations.Migration):

    dependencies = [
        ("core", "0450_recurso_texto_ata_introducao_and_more"),
    ]

    operations = [
        migrations.RunPython(
            populate_data,
            reverse_populate_data,
        ),
    ]
