# Generated by Django 4.2.20 on 2026-07-27 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0451_populate_recurso_textos_ata_recurso_legado"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recurso",
            name="texto_ata_introducao",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Este texto é exibido antes do texto complementar: ___ dias do mês de ___ de ___, às zero hora, reuniu-se a [exibe nome da comissão responsável pelaanálise de PC do recurso] da Diretoria Regional de Educação [exibe a DRE correspondente do consolidado], instituída pela Portaria DRE-[exibe a DRE correspondente do consolidado] nº _______ de __________, para análise das prestações de contas dos recursos transferidos pelo [exibe o recurso correspondente], período de [exibe o período correspondente do consolidado]",
                max_length=256,
                verbose_name="Introdução",
            ),
        ),
        migrations.AlterField(
            model_name="recurso",
            name="texto_ata_letra_a",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Este texto é exibido antes do texto complementar: <p style='display: inline;'>a) <strong style='color: #297805;'>APROVAR</strong> as prestações de contas das Associações das unidades abaixo relacionadas.</p>",
                max_length=256,
                verbose_name="Texto PCs aprovadas",
            ),
        ),
        migrations.AlterField(
            model_name="recurso",
            name="texto_ata_letra_b",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Este texto é exibido antes do texto complementar: <p style='display: inline;'>b) <strong style='color: #297805;'>APROVAR COM RESSALVAS</strong> as prestações de contas das Associações das unidades abaixo relacionadas.</p>",
                max_length=256,
                verbose_name="Texto PCs aprovadas com ressalvas",
            ),
        ),
        migrations.AlterField(
            model_name="recurso",
            name="texto_ata_letra_c",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Este texto é exibido antes do texto complementar: <p style='display: inline;'>b) <strong style='color: #b40c02;'>REJEITAR</strong> as prestações de contas das Associações das unidades abaixo relacionadas.</p>",
                max_length=256,
                verbose_name="Texto PCs reprovadas",
            ),
        ),
        migrations.AlterField(
            model_name="recurso",
            name="texto_ata_letra_d",
            field=models.CharField(
                blank=True, default="", max_length=256, verbose_name="Item complementar"
            ),
        ),
    ]
