# Generated by Django 4.2.20 on 2026-08-05 09:23

from django.db import migrations, models
import django.db.models.deletion

def migrate_existings_tags_to_recurso_legado(apps, schema_editor):
    Recurso = apps.get_model('core', 'Recurso')
    Tag = apps.get_model('core', 'Tag')

    recurso_legado = Recurso.objects.get(legado=True)

    Tag.objects.filter(recurso__isnull=True).update(recurso=recurso_legado)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0452_alter_recurso_texto_ata_introducao_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="recurso",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.recurso",
                verbose_name="Recurso",
            ),
        ),
        migrations.RunPython(migrate_existings_tags_to_recurso_legado, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name="tag",
            name="recurso",
            field=models.ForeignKey(
                null=False,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.recurso",
                verbose_name="Recurso",
            )
        ),
        migrations.AlterUniqueTogether(
            name="tag",
            unique_together={("nome", "recurso")},
        ),
    ]
