# Generated by Django 4.2.20 on 2026-08-07 17:48

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0452_alter_recurso_texto_ata_introducao_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FiqueDeOlho",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "alterado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Alterado em"),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "texto",
                    ckeditor.fields.RichTextField(
                        null=True, verbose_name="Texto do fique de olho"
                    ),
                ),
                (
                    "tipo_texto",
                    models.CharField(
                        choices=[
                            (
                                "associacoes_prestacao_contas",
                                "ASSOCIAÇÕES - Prestação de Contas",
                            ),
                            (
                                "diretorias_consolidado_das_pcs",
                                "DIRETORIAS - Consolidado das PCs",
                            ),
                        ],
                        max_length=35,
                        verbose_name="Tipo de texto",
                    ),
                ),
                (
                    "recurso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.recurso",
                        verbose_name="Recurso",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fique de olho",
                "verbose_name_plural": "01.1) Fique de olho",
                "unique_together": {("tipo_texto", "recurso")},
            },
        ),
    ]
