# Generated by Django 4.2.20 on 2026-08-04 16:56

from django.db import migrations


def populate_data(apps, schema_editor):
    Recurso = apps.get_model("core", "Recurso")
    FiqueDeOlho = apps.get_model("core", "FiqueDeOlho")
    ParametroFiqueDeOlhoPc = apps.get_model("core", "ParametroFiqueDeOlhoPc")
    ParametroFiqueDeOlhoRelDre = apps.get_model("dre", "ParametroFiqueDeOlhoRelDre")

    recurso_legado = Recurso.objects.filter(legado=True).first()

    parametro_fique_de_olho_pc = ParametroFiqueDeOlhoPc.objects.first()
    if parametro_fique_de_olho_pc and recurso_legado:
        FiqueDeOlho.objects.create(
            tipo_texto="associacoes_prestacao_contas",
            recurso=recurso_legado,
            texto=parametro_fique_de_olho_pc.fique_de_olho,
        )

    parametro_fique_de_olho_rel_dre = ParametroFiqueDeOlhoRelDre.objects.first()
    if parametro_fique_de_olho_rel_dre and recurso_legado:
        FiqueDeOlho.objects.create(
            tipo_texto="diretorias_consolidado_das_pcs",
            recurso=recurso_legado,
            texto=parametro_fique_de_olho_rel_dre.fique_de_olho,
        )


def reverse_populate_data(apps, schema_editor):
    FiqueDeOlho = apps.get_model("core", "FiqueDeOlho")

    FiqueDeOlho.objects.filter(recurso__legado=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0453_fiquedeolho"),
    ]

    operations = [
        migrations.RunPython(
            populate_data,
            reverse_populate_data,
        ),
    ]
