# Generated by Django 4.2.20 on 2026-08-10 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0453_tag_recurso"),
        ("core", "0454_populate_fique_de_olho_recurso_legado"),
    ]

    operations = []
