# Generated by Django 4.2.20 on 2026-08-19 11:52

from django.db import migrations, models

def popular_ordem_exibicao_por_recurso(apps, schema_editor):
    Acao = apps.get_model('core', 'Acao')
    Recurso = apps.get_model('core', 'Recurso')
 
    acoes_para_atualizar = []
 
    # Para cada recurso, gera a sequência 1, 2, 3... ordenada por nome
    for recurso in Recurso.objects.all():
        acoes_do_recurso = Acao.objects.filter(recurso=recurso).order_by('nome')
        
        for posicao, acao in enumerate(acoes_do_recurso, start=1):
            acao.ordem_exibicao = posicao
            acoes_para_atualizar.append(acao)
 
    if acoes_para_atualizar:
        Acao.objects.bulk_update(acoes_para_atualizar, ['ordem_exibicao'])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0455_merge_20260810_1104"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="acao",
            unique_together={("nome", "recurso")},
        ),
        migrations.AddField(
            model_name="acao",
            name="ordem_exibicao",
            field=models.PositiveIntegerField(
                db_index=True,
                default=0,
                help_text="Define a ordem de exibição das ações.",
                verbose_name="Ordem de exibição",
            ),
        ),
        migrations.RunPython(popular_ordem_exibicao_por_recurso, reverse_code=migrations.RunPython.noop),
    ]
