# Generated by Django 4.2.20 on 2026-08-26 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0456_alter_acao_unique_together_acao_ordem_exibicao"),
        ("core", "0456_alter_associacao_cargo_substituto_presidente_ausente_and_more"),
    ]

    operations = []
