# Generated by Django 4.2.20 on 2026-08-27 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0457_merge_20260826_0911"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="acao",
            name="posicao_nas_pesquisas",
        ),
        migrations.AlterField(
            model_name="acao",
            name="ordem_exibicao",
            field=models.PositiveIntegerField(
                db_index=True,
                default=0,
                help_text="Define a ordem de exibição das ações para o recurso vinculado.",
                verbose_name="Ordem de exibição",
            ),
        ),
    ]
