# Generated by Django 4.2.20 on 2026-09-02 09:16

from django.db import migrations, models

def migra_permite_consulta_integracao_bb(apps, schema_editor):
    TipoConta = apps.get_model("core", "TipoConta")

    conta_bb_agil_premio = TipoConta.objects.filter(
        nome__iexact="BB Ágil",
        recurso__nome="Prêmio Excelência Educacional"
    ).first()

    if conta_bb_agil_premio:
        conta_bb_agil_premio.permite_consulta_integracao_bb = True
        conta_bb_agil_premio.save()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0458_remove_acao_posicao_nas_pesquisas_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tipoconta",
            name="permite_consulta_integracao_bb",
            field=models.BooleanField(
                default=False,
                verbose_name="Permite consulta via integração com o Banco do Brasil?",
            ),
        ),
        migrations.RunPython(migra_permite_consulta_integracao_bb, reverse_code=migrations.RunPython.noop),
    ]
