# Generated by Django 4.2.20 on 2026-09-09 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0459_auto_20260904_1457"),
        ("core", "0459_tipoconta_permite_consulta_integracao_bb"),
    ]

    operations = []
