# Generated by Django 4.2.20 on 2026-09-09 15:20

from django.db import migrations, models

def migra_existe_saldo_reprogramado_recurso_legado(apps, schema_editor):
    Recurso = apps.get_model("core", "Recurso")

    recurso_legado = Recurso.objects.filter(
        legado=True
    ).first()

    if recurso_legado:
        recurso_legado.existe_saldo_reprogramado = True
        recurso_legado.save()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0460_merge_20260909_1328"),
    ]

    operations = [
        migrations.AddField(
            model_name="recurso",
            name="existe_saldo_reprogramado",
            field=models.BooleanField(
                default=False,
                help_text="Caso a opção seja marcada, será considerada a nomenclatura Saldo reprogramado para exibição e indica que o saldo será reprogramado para os próximos períodos. Caso não seja marcada, a nomenclatura de exibição será Saldo.",
                verbose_name="O recurso possui saldo reprogramado?",
            ),
        ),
        migrations.RunPython(migra_existe_saldo_reprogramado_recurso_legado, reverse_code=migrations.RunPython.noop),
    ]
