# Generated by Django 4.2.20 on 2026-09-18 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0461_recurso_existe_saldo_reprogramado"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fiquedeolho",
            name="tipo_texto",
            field=models.CharField(
                choices=[
                    (
                        "associacoes_prestacao_contas",
                        "ASSOCIAÇÕES - Prestação de Contas",
                    ),
                    (
                        "associacoes_historico_membros",
                        "ASSOCIAÇÕES - Histórico de Membros",
                    ),
                    (
                        "diretorias_consolidado_das_pcs",
                        "DIRETORIAS - Consolidado das PCs",
                    ),
                ],
                max_length=35,
                verbose_name="Tipo de texto",
            ),
        ),
    ]
