# Generated by Django 4.2.20 on 2026-09-22 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0462_alter_fiquedeolho_tipo_texto"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="funcuerecebimentodenotificacoes",
            options={
                "default_permissions": (),
                "managed": False,
                "permissions": (
                    (
                        "recebe_notificacao_inicio_periodo_prestacao_de_contas",
                        "[UE] Pode receber Notificação Início Período Prestação De Contas.",
                    ),
                    (
                        "recebe_notificacao_pendencia_envio_prestacao_de_contas",
                        "[UE] Pode receber Notificação pendência envio Prestação De Contas.",
                    ),
                    (
                        "recebe_notificacao_proximidade_inicio_prestacao_de_contas",
                        "[UE] Pode receber Notificação Proximidade Início Prestação De Contas.",
                    ),
                    (
                        "recebe_notificacao_prestacao_de_contas_devolvida_para_acertos",
                        "[UE] Pode receber Notificação Prestação de Contas Devolvida para Acertos",
                    ),
                    (
                        "recebe_notificacao_proximidade_fim_periodo_prestacao_de_contas",
                        "[UE] Pode receber Notificação Proximidade Fim Período Prestação de Contas",
                    ),
                    (
                        "recebe_notificacao_atraso_entrega_ajustes_prestacao_de_contas",
                        "[UE] Pode receber Notificação Atraso Entrega Ajustes Prestação de Contas",
                    ),
                    (
                        "recebe_notificacao_proximidade_fim_prazo_ajustes_prestacao_de_contas",
                        "[UE] Pode receber Notificação Proximidade Fim Prazo Ajustes Prestação de Contas",
                    ),
                    (
                        "recebe_notificacao_comentario_em_pc",
                        "[UE] Pode receber Notificação de Comentários",
                    ),
                    (
                        "recebe_notificacao_aprovacao_pc",
                        "[UE] Pode receber Notificação Prestação de Contas Aprovada",
                    ),
                    (
                        "recebe_notificacao_reprovacao_pc_nao_incluindo_motivos",
                        "[UE] Pode receber Notificação Prestação de Contas Rejeitada Não Incluindo Motivos",
                    ),
                    (
                        "recebe_notificacao_reprovacao_pc_incluindo_motivos",
                        "[UE] Pode receber Notificação Prestação de Contas Rejeitada Incluindo Motivos",
                    ),
                    (
                        "recebe_notificacao_automatica_inativacao_conta",
                        "[UE] Pode receber Notificação Encerramento de Conta Bancária",
                    ),
                    (
                        "recebe_notificacao_resultado_encerramento_conta",
                        "[UE] Pode receber Notificação Resultado Encerramento de Conta Bancária",
                    ),
                    (
                        "recebe_notificacao_geracao_ata_apresentacao",
                        "[UE] Pode receber Notificação Geração Ata de Apresentação",
                    ),
                    (
                        "recebe_notificacao_geracao_ata_retificacao",
                        "[UE] Pode receber Notificação Geração Ata de Retificação",
                    ),
                    (
                        "recebe_notificacao_conclusao_reprovada_pc_nao_apresentada",
                        "[UE] Pode receber Notificação Prestação de Contas Rejeitada Não Apresentação",
                    ),
                ),
                "verbose_name": "[UE] Recebimento de notificações",
                "verbose_name_plural": "[UE] Recebimento de notificações",
            },
        ),
        migrations.AlterModelOptions(
            name="prestacaocontareprovadanaoapresentacao",
            options={
                "verbose_name": "Prestação de conta rejeitada não apresentação",
                "verbose_name_plural": "09.0.1) Prestações de contas rejeitadas não apresentação",
            },
        ),
        migrations.AlterField(
            model_name="analiseprestacaoconta",
            name="status",
            field=models.CharField(
                choices=[
                    ("EM_ANALISE", "Em análise"),
                    ("DEVOLVIDA", "Devolvida para acertos"),
                    ("APROVADA", "Aprovada"),
                    ("APROVADA_RESSALVA", "Aprovada com ressalvas"),
                    ("REPROVADA", "Rejeitada"),
                ],
                default="EM_ANALISE",
                max_length=20,
                verbose_name="status",
            ),
        ),
        migrations.AlterField(
            model_name="notificacao",
            name="categoria",
            field=models.CharField(
                choices=[
                    ("COMENTARIO_PC", "Comentário na prestação de contas"),
                    ("ELABORACAO_PC", "Elaboração de PC"),
                    ("ANALISE_PC", "Análise de PC"),
                    ("DEVOLUCAO_PC", "Devolução de PC para ajustes"),
                    ("APROVACAO_PC", "Aprovação de PC"),
                    ("APROVACAO_RESSALVAS_PC", "Aprovação de PC com ressalvas"),
                    ("REPROVACAO_PC", "Rejeição de PC"),
                    ("ERRO_AO_CONCLUIR_PC", "Erro ao concluir PC"),
                    ("DEVOLUCAO_CONSOLIDADO", "Devolução de relatório consolidado"),
                    (
                        "COMENTARIO_CONSOLIDADO_DRE",
                        "Comentário no relatório consolidado",
                    ),
                    ("ENCERRAMENTO_CONTA_BANCARIA", "Encerramento de Conta Bancária"),
                    ("GERACAO_ATA", "Geração de Ata"),
                    ("CONCLUSAO_PC", "Conclusão da PC"),
                ],
                default="COMENTARIO_PC",
                max_length=40,
                verbose_name="Categoria",
            ),
        ),
        migrations.AlterField(
            model_name="prestacaoconta",
            name="status",
            field=models.CharField(
                choices=[
                    ("NAO_APRESENTADA", "Não apresentada"),
                    ("NAO_RECEBIDA", "Não recebida"),
                    ("RECEBIDA", "Recebida"),
                    ("EM_ANALISE", "Em análise"),
                    ("DEVOLVIDA", "Devolvida para acertos"),
                    ("DEVOLVIDA_RETORNADA", "Apresentada após acertos"),
                    ("DEVOLVIDA_RECEBIDA", "Recebida após acertos"),
                    ("APROVADA", "Aprovada"),
                    ("APROVADA_RESSALVA", "Aprovada com ressalvas"),
                    ("REPROVADA", "Rejeitada"),
                    ("EM_PROCESSAMENTO", "Em processamento"),
                    ("A_PROCESSAR", "A processar"),
                    ("CALCULADA", "PC calculada. Gerando relatórios"),
                    ("DEVOLVIDA_CALCULADA", "PC calculada. Gerando relatórios"),
                ],
                default="NAO_APRESENTADA",
                max_length=20,
                verbose_name="status",
            ),
        ),
        migrations.AlterField(
            model_name="recurso",
            name="texto_ata_letra_c",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Este texto é exibido antes do texto complementar: <p style='display: inline;'>b) <strong style='color: #b40c02;'>REJEITAR</strong> as prestações de contas das Associações das unidades abaixo relacionadas.</p>",
                max_length=256,
                verbose_name="Texto PCs rejeitadas",
            ),
        ),
    ]
